### ISSUE TITLE
table_notify function causing slow perfomance on large data inserts

### ISSUE THREAD

**Issue by samgreenwood** [toluaina/pgsync#104]
PGSync version: 1.1.27

Postgres version: 12.6

Elasticsearch version: 7.11.1

Redis version: 5.0.3

Python version: 2.7.16

Problem Description: 

Large data sets are causing the INSERT query in Postgres to take quite a long time to complete, due to the trigger that is being called after every row insert.

With Trigger + notifications, 11,000~ rows takes approximately 9 seconds

Without trigger + notifications, 11,000 rows takes approximately 1 second

This grows quite exponentially with large data sets being imported.  

Schema and pgsync configuration can be found in #88 

Error Message (if any): 

```


```

**Comment by samgreenwood** [comment]
Thanks @toluaina 

Import time is now 1/4 on that test data set, approximately 3 seconds.

I have tried a larger data set, 90,000~ rows which takes approx 246 seconds now which is workable.

I note that the polling count does not go down after these being inserted.

----------
 [==================================================] 100.0%
200)
Pkeys: [19137646]
{'_meta': {},
 'address': '214/25 REGENT HONEYEATER GROVE KELLYVILLE NSW 2155',
 'carrier': 'LB',
 'carrier_id': '212849',
 'gnaf': None,
 'id': 19137646,
 'technology': 'FTTP'}
----------
Polling db sq: 108,308 item(s)
Polling db sq: 108,308 item(s)
Polling db sq: 108,308 item(s)

However these records are present in ElasticSearch.

**Comment by toluaina** [comment]
Good to know thr performance has improved.

This log statement has been causing a bit of confusion lately I admit.

`Polling db sq: 108,308 item(s)` is simply a log indicating that 108,308 records have been synced so far from db to es.

Perhaps we should re-word this in a different way

**Comment by toluaina** [comment]
Closing this for now. Feel free to reopen if you feel there is an area that needs attention. There is potential for other performance improvements in future
