### ISSUE TITLE
Error psycopg2.errors.DuplicateTable: relation "_pkey_view" already exists if database have more schemas than one

### ISSUE THREAD

**Issue by LubomirIgonda1** [toluaina/pgsync#108]
PGSync version: master branch commit a7a52399c773698fca0478a6d298548e188e75e0

Postgres version: 13.1

Elasticsearch version: 7.10.1

Redis version: 6.2.1

Python version: 3.9.2

Problem Description: 

I have more schemas in database and after last changes i got this error

my schema.json
```
[
	{
		"database": "myDB",
		"index": "index",
		"nodes": [
			{
				"table": "tableName",
                "label": "customLabel",
                "columns": [
                    "id",
                    "name"
                ]
            }
		]
	}
]
```

![image](https://user-images.githubusercontent.com/9303146/115352499-b56f7600-a1b7-11eb-89d2-8cfc59e31ba4.png)

Error Message (if any): 

![image](https://user-images.githubusercontent.com/9303146/115352128-47c34a00-a1b7-11eb-848e-9d976f4ca5b6.png)

If I can help with debugging let me know thanks for any help

**Comment by fdeschenes** [comment]
I'm also having the same issue as @LubomirIgonda1. This issue seems to be caused by https://github.com/toluaina/pgsync/blob/master/pgsync/sync.py#L152 when there is more than 1 schema in a database because the views are always created in the default schema.

**Comment by toluaina** [comment]
Sorry about this. @fdeschenes has created a PR to resolve this. thanks
