### ISSUE TITLE
Sync not working if foreign key is updated in child table

### ISSUE THREAD

**Issue by LubomirIgonda1** [toluaina/pgsync#115]
PGSync version: commit 545906da64832584d62636c7c59ffc0345939955

Postgres version: 13.1

Elasticsearch version: 7.10.1

Redis version: 6.2.1

Python version: 3.9.2 

Problem Description: 

Synchronization not working if in childTable changed foreign key to middleTable. Or I would tell in globally that the if change association from bottom to top hierarchy it is not working until it will something changed in parent table then it will sync properly

It looks like the data from DB to redis comes properly but then do not show in elasticsearch until something change in parent hierarchy table

If you need more information or I can help you somehow let me know thanks 

```
[{
	"database": "test",
	"index": "myindex",
	"nodes": [{
		"table": "top_table",
		"schema": "public",
		"children": [{
			"table": "middle_table",
			"relationship": {
				"variant": "object",
				"type": "one_to_one"
			},
			"children": [{
					"table": "child_table",
					"relationship": {
						"variant": "object",
						"type": "one_to_many"
					}
				}]
			}]
		}]
}]
```

here is db model 

![image](https://user-images.githubusercontent.com/9303146/115828606-3a53cd00-a40e-11eb-807d-55026b961fb4.png)

**Comment by toluaina** [comment]
Is the current schema doing what you expect at all?
For a middle table, you need to define a through_table relationship
as indicated in the [docs](https://pgsync.com/tutorial/relationship-with-through-tables/) in the section on relationships

```
[
    {
        "database": "test",
        "index": "myindex",
        "nodes": [
            {
                "table": "top_table",
                "schema": "public",
                "children": [
                    {
                        "table": "child_table",
                        "relationship": {
                            "variant": "object",
                            "type": "one_to_many",
                             "through_tables": [
                                "middle_table"
                            ]
                        }
                    }
                ]
            }
        ]
    }
]
```

**Comment by LubomirIgonda1** [comment]
Hi but the middle table it is not just a junction table in my case the result index looks like this. What is exactly what I want in your suggest scheme it is without middle_table but the middle_table also contain relevant data for me so I want this data in index also. This is only test example but my real case is more complex. It is kind of weird that in the first init time works well but the next sync event not.

````
{
	"_index": "myindex",
	"_type": "_doc",
	"_id": "1",
	"_version": 1,
	"_seq_no": 0,
	"_primary_term": 1,
	"found": true,
	"_source": {
		"id": 1,
		"name": "test1",
		"middleTableID": 1,
		"middle_table": {
			"id": 1,
			"name": "test1",
			"child_table": [
				{
					"mddleTableID": 1,
					"name": "test"
				}
			]
		},
		"_meta": {
			"middle_table": {
				"id": [
					1
				]
			},
			"child_table": {
				"mddleTableID": [
					1
				]
			}
		}
	}
}
````

**Comment by toluaina** [comment]
- I am unable to repeoduce this.
- I created. a branch that is similar to what you described here 
- Can you checkout he branch `foreign_key_is_updated_in_child_table`
- setup your .env 
- run `./examples/bootstrap.sh sandbox`
- then you can run ` pgsync -c examples/sandbox/schema.json -d`
- then you can make changes to the sandbox database and see if it is propagated to elasticsearch.
- This should be a complete working example

**Comment by LubomirIgonda1** [comment]
- at the beginning between middle_table and child_table in my case is one_to_many association but in your sandbox example it is one_to_one in schema.json but anyway the issues is in both scenarios
- the test scenario is:

1. change for record id=1 in child_table->middle_id from 1 to 2
```
before:
child_table
id; name; middle_id;
1; child 1; 1

after
child_table
id; name; middle_id;
1; child 1; 2
```

2. in elasticsearch child record for middle_table id=1 change to null that is correct
3. in elasticsearch child record for middle_table id=2 should have 2 children with ID 1 and 2 but this is not happen
4. I revers the process so I set  for record id=1 in child_table->middle_id from 2 to 1
```
child_table
before:
id; name; middle_id;
1; child 1; 2

after
child_table
id; name; middle_id;
1; child 1; 1
```
5. and expect that the result would be the same as after initialize elasticsearch for the first time but nothing changed

I observer that the "Polling db sandbox: " print increase after every change in database

**Comment by toluaina** [comment]
Thanks, this helps a lot. Taking a closer look at this

**Comment by DanielZavacky** [comment]
@toluaina Hi, I have same problem. I tried master branch with commit you made yesterday (where you made some fixes related to this issue). It looks that it updates first level of nested structure, bud it does not update deeper levels. I made a fork of this project, where I added **shop** example, where you can try it [(pgsync fork)](https://github.com/DanielZavacky/pgsync).

Just run bootstrap and then pgsync. It will create products index in your elasticsearch. When you look up document with id 3, you will see, that it does not have saleServices.
Then after running  `INSERT INTO "public"."service_product_category_sellers"("productCategoryID", "serviceID", "sellerID") VALUES (2, 1, 1);` it will add item to saleServices (which will have one serviceItem).
But after running `INSERT INTO "public"."service_items"("id", "name", "serviceID") VALUES (5, 'saleService1 item', 1);` it should add another serviceItem, but it will not.

If there is anything I can help you with, let me know

**Comment by toluaina** [comment]
This turned out to be a lot of effort. Can you try the master branch now please.
PS: The master branch now uses a different schema format. 

You can migrate using the migration tool
`scripts/migrate_schema_v2 -c /path/to/schema.json`

**Comment by toluaina** [comment]
This has also been resolved in the latest release
