### ISSUE TITLE
Duplicate triggers throwing errors

### ISSUE THREAD

**Issue by meetri** [toluaina/pgsync#127]
PGSync version:  2.0

used the docker-compose.yml in the master branch.

sorry, too lazy to fill in a full bug report... I had issues where there postgres was throwing errors trying to recreate triggers... I did a simple fix. You may have a better way to fix it.

If you really need more details let me know and i'll dig through the steps...

```
diff --git a/pgsync/base.py b/pgsync/base.py
index 2a035a8..1cdcaf2 100644
--- a/pgsync/base.py
+++ b/pgsync/base.py
@@ -56,6 +56,7 @@ class Base(object):
         self.models = {}
         self.__metadata = {}
         self.verbose = verbose
+        self.duplist = []
 
     def connect(self):
         """Connect to database."""
@@ -607,14 +608,18 @@ class Base(object):
                 ("notify", "ROW", ["INSERT", "UPDATE", "DELETE"]),
                 ("truncate", "STATEMENT", ["TRUNCATE"]),
             ]:
-                queries.append(
-                    sa.DDL(
-                        f"CREATE TRIGGER {table}_{name} "
-                        f'AFTER {" OR ".join(tg_op)} ON "{schema}"."{table}" '
-                        f"FOR EACH {for_each} EXECUTE PROCEDURE "
-                        f"{TRIGGER_FUNC}()",
+                if f"{table}_{schema}" not in self.duplist:
+                    self.duplist.append(f"{table}_{schema}")
+                    queries.append(
+                        sa.DDL(
+                            f"CREATE TRIGGER {table}_{name} "
+                            f'AFTER {" OR ".join(tg_op)} ON "{schema}"."{table}" '
+                            f"FOR EACH {for_each} EXECUTE PROCEDURE "
+                            f"{TRIGGER_FUNC}()",
+                        )
                     )
-                )
+                else:
+                    logger.debug(f"{table}_{schema} found in duplist: {self.duplist}")
 
         for query in queries:
             self.execute(query)


```
i just did a check for duplicates and skipped it if it was.

**Comment by y-cherdantsev** [comment]
Same problem, waiting for fix in the next release

`
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/bootstrap", line 68, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/bin/bootstrap", line 63, in main
    sync.setup()
  File "/usr/local/lib/python3.7/dist-packages/pgsync/sync.py", line 190, in setup
    self.create_triggers(schema, tables=tables)
  File "/usr/local/lib/python3.7/dist-packages/pgsync/base.py", line 665, in create_triggers
    self.execute(query)
  File "/usr/local/lib/python3.7/dist-packages/pgsync/base.py", line 844, in execute
    conn.execute(statement, values)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1201, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/sql/ddl.py", line 78, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1297, in _execute_ddl
    compiled,
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1750, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1931, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1707, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DuplicateObject) trigger "entities_notify" for relation "entities" already exists
`

**Comment by toluaina** [comment]
Can you please share your schema.json ?

**Comment by meetri** [comment]
[
    {
        "database": "pg_db",
        "index": "es_index",
        "nodes": {
            "table": "entity",
            "schema": "er",
            "columns": [
                "entity_id",
                "name"
            ],
            "children": [
                {
                    "table": "address",
                    "schema": "er",
                    "columns": [
                        "city",
                        "state",
                        "country"
                    ],
                    "relationship": {
                        "variant": "object",
                        "type": "one_to_many",
                        "foreign_key": {
                            "child": ["entity_id"],
                            "parent": ["entity_id"]
                        }
                    }
                }
            ]
        }
    }
]

when i shuffled around the pivot table, it worked. For example, when I made address to the top level i didn't get the duplicate entity_notify issue, but when I move it back with entity at the head, it tried to create the entity_notify trigger twice. --- I'm sure you'll need the schema to the db, i've been pretty busy lately ( in the middle of a move ) but if I can get some time, i'll post the db schema as well

**Comment by y-cherdantsev** [comment]
> Can you please share your schema.json ?

I've sent old and new version for 2.0.0 release at your email 'toluaina@hotmail.com'. 

Thanks

**Comment by toluaina** [comment]
Sorry about the delay on this. 
I think this is as a result of running different versions.
I think ideally we should do a teardown, upgrade and then bootstrap.

Can you please use the version on master and let me know if this still happens.
If it does then I'll need to make the triggers backward compatible. 

@y-cherdantsev @meetri

**Comment by y-cherdantsev** [comment]
> Sorry about the delay on this.
> I think this is as a result of running different versions.
> I think ideally we should do a teardown, upgrade and then bootstrap.
> 
> Can you please use the version on master and let me know if this still happens.
> If it does then I'll need to make the triggers backward compatible.
> 
> @y-cherdantsev @meetri

Hi, I found that even in 1.3.3 I have same error.
[Terminal output.txt](https://github.com/toluaina/pgsync/files/6514756/Terminal.output.txt)

After bootstrap with teardown this request in DB returned 0 lines:
```
SELECT * FROM pg_trigger
WHERE NOT tgisinternal
AND tgname LIKE '%notify%' OR tgname LIKE '%truncate%';
```

After second bootstrap without teardown I got 40 triggers. 20 'notify' and 20 'truncate', but DB still have no PG_REPLICATION_SLOTS and I've got same error again. You can see verbose trace from my terminal.

**Comment by toluaina** [comment]
@y-cherdantsev 

This should be resolved now in the master branch. Would you mind giving it another try.

**Comment by y-cherdantsev** [comment]
> @y-cherdantsev 
> 
> This should be resolved now in the master branch. Would you mind giving it another try.
> 
> 

K, I'll try tomorrow and will give you reply after that

**Comment by y-cherdantsev** [comment]
> @y-cherdantsev
> 
> This should be resolved now in the master branch. Would you mind giving it another try.

Gosh, It works!!!

Thanks a lot. Can you please make release in shortest period that you can if all of your changes are final in this issue. I would appreciate that a lot.

Thanks in advance.

**Comment by y-cherdantsev** [comment]
> > @y-cherdantsev
> > This should be resolved now in the master branch. Would you mind giving it another try.
> 
> Gosh, It works!!!
> 
> Thanks a lot. Can you please make release in shortest period that you can if all of your changes are final in this issue. I would appreciate that a lot.
> 
> Thanks in advance.

I'm sorry. Yes, It created all triggers but now I've got new error. While trying to insert into tables with table_notify() trigger.
```
[42P01] ERROR: relation "_view" does not exist Where: PL/pgSQL function table_notify() line 32 at SQL statement
```

**Comment by toluaina** [comment]
Sorry about the delay on this. Can you try once more please with usgint the master branch.

**Comment by y-cherdantsev** [comment]
> Sorry about the delay on this. Can you try once more please with usgint the master branch.

It seems that it worked for me, Thanks.
Another bug that I've found is that if I use non public schema even if I declare postgres schema name in start of pgsync schema file I have this error while bootstrapping:
```
File "_bootstrap", line 66, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "_bootstrap", line 57, in main
    sync = Sync(document, verbose=verbose, repl_slots=False, **params)
  File "/home/echerdantsev/pgsync_master/pgsync/pgsync/sync.py", line 82, in __init__
    self.validate(repl_slots=repl_slots)
  File "/home/echerdantsev/pgsync_master/pgsync/pgsync/sync.py", line 149, in validate
    root = self.tree.build(self.nodes)
  File "/home/echerdantsev/pgsync_master/pgsync/pgsync/node.py", line 255, in build
    model=self.base.model(table, schema=schema),
  File "/home/echerdantsev/pgsync_master/pgsync/pgsync/base.py", line 133, in model
    f'Table "{name}" not found in registry'
pgsync.exc.TableNotFoundError: 'Table "public.entities" not found in registry'
```

This occurs if not to declare schema in **each** node.
### Example:
Not working:
```
[
  {
    "database": "counterparty",
    "index": "counterparties_dev",
    "schema": "counterparty_data",
    "nodes": {
      "table": "entities",
      "children": [...]
    }
  }
]
```

Working:
```
[
  {
    "database": "counterparty",
    "index": "counterparties_dev",
    "schema": "counterparty_data",
    "nodes": {
      "table": "entities",
      "schema": "counterparty_data",
      "children": [...]
    }
  }
]
```

I thought that all child nodes should use parent schema if another one wasn't declared. Tell me if I'm wrong.

Thank you for attention.

**Comment by toluaina** [comment]
@y-cherdantsev 

Sorry about the delay again. 
The node actually defaults to `public` schema if not specified. I thought this was easier to remember. 
Although I can see the reason for them to inherit from the parent.

**Comment by toluaina** [comment]
Hopefully resolved
