### ISSUE TITLE
Don`t work daemon

### ISSUE THREAD

**Issue by Maxdzy** [toluaina/pgsync#132]
PGSync version: 2.0.1

Postgres version: PostgreSQL 11.11 (Debian 11.11-0+deb10u1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit

Elasticsearch version: 7.11.2,

Redis version: Redis server v=5.0.3 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=1b271fe49834c463

Python version: 3.7

Problem Description: 
At the first start, the daemon works fine, but further changes are displayed in the terminal as an increment of the index, but they are not loaded into the elastic or do it with a long delay, about 30-50 minutes add 100 lines.

What to do?

We have chunk size 15000
The schema includes 11 tables
Rows in the database about 100 - 10,000 in each table
~~~
{
    "database": "work_test",
    "index": "vacancies",
    "nodes": {
        "table": "vacancies",
        "children": [
            {
                "table": "company_profile_users",
                "label": "vacancies_manager_info",
                "columns": [
                    "id",
                    "surname",
                    "name",
                    "middle_name",
                    "email",
                    "is_active",
                    "user_id",
                    "role_id",
                    "company_profile_id"
                ],
                "relationship": {
                    "variant": "object",
                    "type": "one_to_one"
                }
            },
            {
                "table": "experiences",
                "label": "vacancies_experiences_info",
                "columns": [
                    "id",
                    "code",
                    "name"
                ],
                "relationship": {
                    "variant": "object",
                    "type": "one_to_one"
                }
            },
            {
                "table": "taxes",
                "label": "vacancies_taxes_info",
                "columns": [
                    "id",
                    "code",
                    "name"
                ],
                "relationship": {
                    "variant": "object",
                    "type": "one_to_one"
                }
            },
            {
                "table": "company_profiles",
                "label": "vacancies_company_profile_info",
                "columns": [
                    "id",
                    "biin",
                    "name",
                    "logo",
                    "email",
                    "description",
                    "site",
                    "is_verified",
                    "is_active",
                    "region_id"
                ],
                "relationship": {
                    "variant": "object",
                    "type": "one_to_one"
                }
            },
            {
                "table": "specializations",
                "label": "vacancies_specialization_info",
                "columns": [
                    "id",
                    "category_id",
                    "name",
                    "code"
                ],
                "relationship": {
                    "variant": "object",
                    "type": "one_to_one",
                    "through_tables": [
                        "vacancy_specializations"
                    ]
                },
                "children": [
                    {
                        "table": "specialization_categories",
                        "label": "vacancies_categories_info",
                        "columns": [
                            "id",
                            "name",
                            "code"
                        ],
                        "relationship": {
                            "variant": "object",
                            "type": "one_to_one"
                        }
                    }
                ]
            },
            {
                "table": "cities",
                "label": "vacancies_city_info",
                "columns": [
                    "name"
                ],
                "relationship": {
                    "variant": "scalar",
                    "type": "one_to_one"
                }
            },
            {
                "table": "languages",
                "label": "vacancy_languages_info",
                "columns": [
                    "id",
                    "code",
                    "name"
                ],
                "relationship": {
                    "variant": "object",
                    "type": "one_to_many",
                    "through_tables": [
                        "vacancy_languages"
                    ]
                }
            },
            {
                "table": "schedules",
                "label": "vacancy_schedules_info",
                "columns": [
                    "id",
                    "code",
                    "name"
                ],
                "relationship": {
                    "variant": "object",
                    "type": "one_to_many",
                    "through_tables": [
                        "vacancy_schedules"
                    ]
                }
            },
            {
                "table": "employments",
                "label": "vacancy_employments_info",
                "columns": [
                    "id",
                    "code",
                    "name"
                ],
                "relationship": {
                    "variant": "object",
                    "type": "one_to_many",
                    "through_tables": [
                        "vacancy_employments"
                    ]
                }
            }
        ]
    }
}
~~~

**Comment by toluaina** [comment]
Can you provide more information.

> Do you have a lot of data in your db and is this the initial sync?
> Did you run the booststrap successfully?
> Can you run with -v option and provide some logs?

**Comment by Maxdzy** [comment]
Do you have a lot of data in your db and is this the initial sync?
- In the main table (vacancies) no more than 1000 lines

Did you run the booststrap successfully?
- Successfull:
~~~
bootstrap -c vacancy_schema.json
 - vacancies
   |- company_profile_users
   |- experiences
   |- taxes
   |- company_profiles
   |- specializations
   |   - specialization_categories
   |- cities
   |- languages
   |- schedules
    - employments
~~~

Can you run with -v option and provide some logs?

- there are logs only when I enable pgsynck, then no changes need to be restarted
run: pgsync -c vacancy_schema.json -d -v

~~~
Polling db module_work_test: 24 cache items
Polling db module_work_test: 24 cache items
Polling db module_work_test: 24 cache items
Polling db module_work_test: 24 cache items
Polling db module_work_test: 24 cache items
Polling db module_work_test: 29 cache items
Polling db module_work_test: 29 cache items
Polling db module_work_test: 29 cache items
~~~

**Comment by Maxdzy** [comment]
Maybe this is due to the fact that 4 daemons pgsync are running in parallel ?

**Comment by y-cherdantsev** [comment]
Ah shit, the same shit

**Comment by y-cherdantsev** [comment]
What to do?

**Comment by y-cherdantsev** [comment]
I've the same problem with large tables. But even with small tables I've large delay between data synchronization. 60 changes can load into elastic nearly 10 minutes. Can you explain, how backend processes works. Maybe you have some block diagram of an application processes?
Please 😢

**Comment by toluaina** [comment]
Running 4 daemons in parallel would be the the cause. 
You can't parallelize in this way. Each daemon would overwite the `.checkpoint`t file which is used for internal housekeeping.

**Comment by toluaina** [comment]
> I've the same problem with large tables. But even with small tables I've large delay between data synchronization. 60 changes can load into elastic nearly 10 minutes. Can you explain, how backend processes works. Maybe you have some block diagram of an application processes?
> Please 😢
> 
> Firstly after change in DB I instantly see incrementation into cached items. After 5-10 minutes I see loading progress bar. What can be reason of such behavior?

Are you also running multiple processes?

**Comment by Maxdzy** [comment]
I am using a different schema, each daemon processes different tables.

Can't run multiple daemons at the same time even with different schemes?

**Comment by Maxdzy** [comment]
I am using a different schema, each daemon processes different tables.

Can't run multiple daemons at the same time even with different schemes?

**Comment by y-cherdantsev** [comment]
> ances of pgsync

Yes, the same thing. I am running one instance of daemon to each schema. Overall 5 schemas running at the same time in one DB. But I don't think that it's a problem, because even if only one instance is running I have huge delay between relatively large updates.

**Comment by toluaina** [comment]
Ok do the schemas have unique database and index pairs?
pgsync maintains a checkpoint/state file for each database/index pair.
If you have multiple schema.json pointing to the same database/index then then each daemon could overwrite the .checkpoint file .
Perhaps you could share with me your schema.json.
During each sync cycle pgsync writes a transaction id to the checkpoint file to maintain the current state.

**Comment by toluaina** [comment]
Perhaps I could get a a description of your use case to get a better understanding. You might be better off creating a separate index. Unless I am missing your point

**Comment by Maxdzy** [comment]
There are 4 schemes for different entities
4 different database tables postgresql, and 4 different elastic indexes, each schema refers to different tables and indexes.

Each of the daemons creates its own unique checkpoint file.

Even if you run only one daemon with one schema in one index, it does not work correctly (60 changes can load into elastic nearly 10-100 minutes), the schema is attached above.
