### ISSUE TITLE
URL not constructed properly incase of AWS hosted elasticsearch

### ISSUE THREAD

**Issue by harish-everest** [toluaina/pgsync#133]
PGSync version: 2.1.

Postgres version: 12.5

Elasticsearch version: 7.10

Redis version: 4.0.10

Python version: 3.7

Problem Description: URL is being wrongly constructed if the env variable `ELASTICSEARCH_AWS_HOSTED` set to `True`.

See in the line instead of using the `ELASTICSEARCH_HOST` as host we are using url constructed.

https://github.com/toluaina/pgsync/blob/2620059723afe167276098dc13d49f50b3176453/pgsync/elastichelper.py#L222

Error Message (if any): 

```
requests.exceptions.InvalidURL: Failed to parse: https://[http://XXXX:443]:443/

```

**Comment by harish-everest** [comment]
#134

**Comment by harish-everest** [comment]
@toluaina can you review it? We are using this in our application and need to test it with AWS elaticsearch.

**Comment by toluaina** [comment]
Hmm If we go this route, I think it makes sense to support this `ELASTICSEARCH_HOST` in both AWS managed and self hosted services. Right now it appears to be specific to AWS. 

Did you se the individual parts of the URL. I am trying to understand why the url was not constructed properly

- ELASTICSEARCH_SCHEME
- ELASTICSEARCH_HOST 
- ELASTICSEARCH_PORT 
- ELASTICSEARCH_USER  
- ELASTICSEARCH_PASSWORD

**Comment by harish-everest** [comment]
I had provided individual parts of the URL. 

```
ELASTICSEARCH_SCHEME = https
ELASTICSEARCH_HOST = xxxx.aws.com
ELASTICSEARCH_PORT = 443
```


If you can see here`hosts=[{"host": url, "port": 443}]` we are passing `url` as host.

We can solve this with two approaches. One is passing the URL constructed directly to the `hosts` list or using `ELASTICSEARCH_HOST` variable.

```
hosts=[url]

or

hosts=[{"host": ELASTICSEARCH_HOST, "port": 443}]

```

From elasticsearch python client docs

> hosts – list of nodes, or a single node, we should connect to. Node should be a dictionary ({“host”: “localhost”, “port”: 9200}), the entire dictionary will be passed to the Connection class as kwargs, or a string in the format of host[:port] which will be translated to a dictionary automatically. If no value is given the Connection class defaults will be used.

**Comment by toluaina** [comment]
Thansk for that. This makes sense. I prefer the 
`hosts=[url]`
as this is more intuitive. 

Can you update that MR please. 
thanks again

**Comment by harish-everest** [comment]
@toluaina I have updated the PR. Please check it.

Can you also release a new patch?
