### ISSUE TITLE
Not syncing postgres and elasticsearch if run in daemon mode without restart.

### ISSUE THREAD

**Issue by jibinmannanal** [toluaina/pgsync#137]
PGSync version: 2.0.0

Postgres version: 13.2

Elasticsearch version: 7.13.3

Redis version: 5.0.7

Python version: 3.8.10

Problem Description:  If I run pgsync --config in daemon mode and update a record to postgres, 
Polling db postgres: 1 item(s) is showing and not indexing elastic search. After rerun pgsync --config  then only reflecting the changes in elasticsearch.

Error Message (if any): 
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  
TypeError: 'NoneType' object is not subscriptable

**Comment by toluaina** [comment]
Can you provide a sample `schema.json` config and/or db schema would help too.

**Comment by jibinmannanal** [comment]
Hi Tolu,
Thanks for your quick response. Please find  schema.json and db schema for
your reference.

[{
         "database": "postgres",
        "index": "pgsync",
         "nodes":
       {
            "table": "georgia1",
            "schema": "public",
            "columns": [
                "gid",
                "STATEFP10",
                "COUNTYFP10",
                "TRACTCE10",
                "BLOCKCE10",
                "GEOID10",
                "NAME10",
                "MTFCC10",
                "UR10",
                "UACE10",
                "UATYPE",
                "FUNCSTAT10",
                "MaxAdDown",
                "hu2019",
                "pop2019",
                "hh2019",
                "LF_RDOF_El",
                "RDOF_Eligi",
                "CAF2_Eligi",
                "bidder",
                "census_id",
                 "cc_down",
                "cc_up"
            ]
        }

}
]



thanks and regards....

jibin scaria
ph:8197467042

**Comment by jibinmannanal** [comment]
One more query ,
Is it possibile to index each table with diffrent index name within a schema(one db each table different different  index )?

**Comment by jibinmannanal** [comment]
Hi 
if add geometry column in a table, then pgsync not working.

**Comment by jesseomega** [comment]
I observe the same behavior as the poster (per the ticket title) on master. pgsync detects changes, but never forces indexing of elastic search until pgsync is restarted when launched in daemon mode.

**Comment by toluaina** [comment]
> One more query ,
> Is it possibile to index each table with diffrent index name within a schema(one db each table different different index )?

Yes you can certainly do this.
@jibinmannanal

**Comment by toluaina** [comment]
> I observe the same behavior as the poster (per the ticket title) on master. pgsync detects changes, but never forces indexing of elastic search until pgsync is restarted when launched in daemon mode.

Can you confirm that this issue still exists 
als did the bootstratp run successfully. Sorry I would need more details to get to the bottom of this. Might be work creating a separate issue to track this

**Comment by jibinmannanal** [comment]
> > I observe the same behavior as the poster (per the ticket title) on master. pgsync detects changes, but never forces indexing of elastic search until pgsync is restarted when launched in daemon mode.
> 
> Can you confirm that this issue still exists
> als did the bootstratp run successfully. Sorry I would need more details to get to the bottom of this. Might be work creating a separate issue to track this

Hi @toluaina ,
Latest version of pgsync working fine for me.

**Comment by EgoPingvina** [comment]
I still havethe  same problem on Book example.
