### ISSUE TITLE
If index  2core records, ram memory is increasing and after some time server is stuck.

### ISSUE THREAD

**Issue by jibinmannanal** [toluaina/pgsync#140]

**Comment by jibinmannanal** [comment]
@toluaina ,
Thanks for this update. I will check this.

**Comment by jibinmannanal** [comment]
@toluaina ,
If stop and start pgsync daemon is it again index record?(Already indexed)

**Comment by toluaina** [comment]
I have added support for streaming bulk index mode.
This is however not the default.
Streaming bulk is more lenient on memory usage.
You can enable it by defining 
This is available in the master branch

`ELASTICSEARCH_STREAMING_BULK=True
`

**Comment by toluaina** [comment]
I have added support for streaming bulk index mode.
This is however not the default.
Streaming bulk is more lenient on memory usage.
You can enable it by defining 
This is available in the master branch

`ELASTICSEARCH_STREAMING_BULK=True
`
