### ISSUE TITLE
How to use custom queries

### ISSUE THREAD

**Issue by prashantbiraris** [toluaina/pgsync#144]
PGSync version:   2.1.1

Postgres version:  12

Elasticsearch version: elasticsearch-7.13.2 

Redis version: 

Python version: 3.7

Problem Description: 

                             **How sync data through custom conditional queries like using where clause?**

Error Message (if any): 

```


```

**Comment by toluaina** [comment]
This seems like a very reasonable and typical use case and I considered this for some time.
I couldn't think of an easy way for specifying generic queries in a 
JSON config without re-implementing what Elasticsearch supports in some ways
or a simplified/intuitive language for declaring this in the schema config.

This would also increase the complexity from a usability point of view.
I think you can move this type of functionality into Elasticsearch itself.


- PGSync has support for [pipelines](https://www.elastic.co/guide/en/elasticsearch/reference/7.13/ingest.html) and this might be the best option.
- You can also use PGSync's support for [plugins](https://pgsync.com/tutorial/plugins/) to perform more advanced transformation operations to achieve this

**Comment by toluaina** [comment]
closing as resolved.
`WHERE` queries are best implemented as plugins for better generalization
