### ISSUE TITLE
cannot use pgsync on table with many (83) columns (pgsync.sync: Exception (psycopg2.errors.TooManyArguments) cannot pass more than 100 arguments to a function)

### ISSUE THREAD

**Issue by d2a-raudenaerde** [toluaina/pgsync#149]
PGSync version: 2.1.1

Postgres version: 12.5

Elasticsearch version: 7.13.2

Redis version: ?

Python version: 3.8

Problem Description: 

I cannot use pgsync on table with very many colums.

Error Message (if any): 

```
[SQL: SELECT anon_1."JSON_BUILD_ARRAY_1", anon_1."JSON_BUILD_OBJECT_1" 
FROM (SELECT JSON_BUILD_ARRAY() AS "JSON_BUILD_ARRAY_1", JSON_BUILD_OBJECT(%(JSON_BUILD_OBJECT_2)s, actions_dbc_1.id, %(JSON_BUILD_OBJECT_3)s, actions_dbc_1.tcn, %(JSON_BUILD_OBJECT_4)s, actions_dbc_1.patientnr, %(JSON_BUILD_OBJECT_5)s, actions_dbc_1.patient_naam, %(JSON_BUILD_OBJECT_6)s, actions_dbc_1.dbcnr, %(JSON_BUILD_OBJECT_7)s, actions_dbc_1.dbc_datum, %(JSON_BUILD_OBJECT_8)s, actions_dbc_1.prestatie_code, %(JSON_BUILD_OBJECT_9)s, actions_dbc_1.specialisme, %(JSON_BUILD_OBJECT_10)s, actions_dbc_1.toelichting, %(JSON_BUILD_OBJECT_11)s, actions_dbc_1.rule_code, %(JSON_BUILD_OBJECT_12)s, actions_dbc_1.task_status, %(JSON_BUILD_OBJECT_13)s, actions_dbc_1.regel, %(JSON_BUILD_OBJECT_14)s, actions_dbc_1.actie, %(JSON_BUILD_OBJECT_15)s, actions_dbc_1.oplosser, %(JSON_BUILD_OBJECT_16)s, actions_dbc_1.event_status, %(JSON_BUILD_OBJECT_17)s, actions_dbc_1.event_datum, %(JSON_BUILD_OBJECT_18)s, actions_dbc_1.tasklist_criteria, %(JSON_BUILD_OBJECT_19)s, actions_dbc_1.created_by_user, %(JSON_BUILD_OBJECT_20)s, actions_dbc_1.create_date, %(JSON_BUILD_OBJECT_21)s, actions_dbc_1.modified_by_user, %(JSON_BUILD_OBJECT_22)s, actions_dbc_1.modify_date, %(JSON_BUILD_OBJECT_23)s, actions_dbc_1.valuation, %(JSON_BUILD_OBJECT_24)s, actions_dbc_1.specialist_code, %(JSON_BUILD_OBJECT_25)s, actions_dbc_1.kostenplaats_code, %(JSON_BUILD_OBJECT_26)s, actions_dbc_1.specialisme_code, %(JSON_BUILD_OBJECT_27)s, actions_dbc_1.oplosser_code, %(JSON_BUILD_OBJECT_28)s, actions_dbc_1.kosten_deel, %(JSON_BUILD_OBJECT_29)s, actions_dbc_1.honorarium_deel, %(JSON_BUILD_OBJECT_30)s, actions_dbc_1.patient_geboortedatum, %(JSON_BUILD_OBJECT_31)s, actions_dbc_1.username, %(JSON_BUILD_OBJECT_32)s, actions_dbc_1.dbc_typering, %(JSON_BUILD_OBJECT_33)s, actions_dbc_1.ste_dbc_id, %(JSON_BUILD_OBJECT_34)s, actions_dbc_1.task_count, %(JSON_BUILD_OBJECT_35)s, actions_dbc_1.dbc_einddatum, %(JSON_BUILD_OBJECT_36)s, actions_dbc_1.zis_ziektegevalnr, %(JSON_BUILD_OBJECT_37)s, actions_dbc_1.dbc_segment, %(JSON_BUILD_OBJECT_38)s, actions_dbc_1.ind_medisch, %(JSON_BUILD_OBJECT_39)s, actions_dbc_1.vc_lokatie_code, %(JSON_BUILD_OBJECT_40)s, actions_dbc_1.kleur_code, %(JSON_BUILD_OBJECT_41)s, actions_dbc_1.vc_laatste_uitvoerder_code, %(JSON_BUILD_OBJECT_42)s, actions_dbc_1.task_role, %(JSON_BUILD_OBJECT_43)s, actions_dbc_1.condition_nr, %(JSON_BUILD_OBJECT_44)s, actions_dbc_1.task_allocation, %(JSON_BUILD_OBJECT_45)s, actions_dbc_1.vc_bedrijf, %(JSON_BUILD_OBJECT_46)s, actions_dbc_1.reference, %(JSON_BUILD_OBJECT_47)s, actions_dbc_1.commentary, %(JSON_BUILD_OBJECT_48)s, actions_dbc_1.operateur_naam, %(JSON_BUILD_OBJECT_49)s, actions_dbc_1.event_details, %(JSON_BUILD_OBJECT_50)s, actions_dbc_1.task_revenue_code, %(JSON_BUILD_OBJECT_51)s, actions_dbc_1.verbandscombinatie_nr, %(JSON_BUILD_OBJECT_52)s, actions_dbc_1.declaratie_code, %(JSON_BUILD_OBJECT_53)s, actions_dbc_1.vc_debiteur_code, %(JSON_BUILD_OBJECT_54)s, actions_dbc_1.characteristics, %(JSON_BUILD_OBJECT_55)s, actions_dbc_1.agenda_code, %(JSON_BUILD_OBJECT_56)s, actions_dbc_1.vgn_zorgproduct, %(JSON_BUILD_OBJECT_57)s, actions_dbc_1.afgeleid_zorgproduct, %(JSON_BUILD_OBJECT_58)s, actions_dbc_1.contact_email, %(JSON_BUILD_OBJECT_59)s, actions_dbc_1.zorgverzekeraar, %(JSON_BUILD_OBJECT_60)s, actions_dbc_1.rule_priority, %(JSON_BUILD_OBJECT_61)s, actions_dbc_1.event_priority, %(JSON_BUILD_OBJECT_62)s, actions_dbc_1.event_reference_date, %(JSON_BUILD_OBJECT_63)s, actions_dbc_1.vc_afwijkend_zp_reden, %(JSON_BUILD_OBJECT_64)s, actions_dbc_1.specialist_naam, %(JSON_BUILD_OBJECT_65)s, actions_dbc_1.zis_validatie_fout_omschr, %(JSON_BUILD_OBJECT_66)s, actions_dbc_1.rule_status, %(JSON_BUILD_OBJECT_67)s, actions_dbc_1.user_priority, %(JSON_BUILD_OBJECT_68)s, actions_dbc_1.hoofdbehandelaar_code, %(JSON_BUILD_OBJECT_69)s, actions_dbc_1.loid, %(JSON_BUILD_OBJECT_70)s, actions_dbc_1.uitvoerende_oe, %(JSON_BUILD_OBJECT_71)s, actions_dbc_1.status_code, %(JSON_BUILD_OBJECT_72)s, actions_dbc_1.checksum, %(JSON_BUILD_OBJECT_73)s, actions_dbc_1.zis_validatie_fout_datum, %(JSON_BUILD_OBJECT_74)s, actions_dbc_1.oplosser_d2a, %(JSON_BUILD_OBJECT_75)s, actions_dbc_1.task_allocation_d2a, %(JSON_BUILD_OBJECT_76)s, actions_dbc_1.username_d2a, %(JSON_BUILD_OBJECT_77)s, actions_dbc_1.sub_specialisme_code, %(JSON_BUILD_OBJECT_78)s, actions_dbc_1.vc_commentary, %(JSON_BUILD_OBJECT_79)s, actions_dbc_1.hix_fout_opmerking, %(JSON_BUILD_OBJECT_80)s, actions_dbc_1.type_verwijzer, %(JSON_BUILD_OBJECT_81)s, actions_dbc_1.zis_validatie_fout_status, %(JSON_BUILD_OBJECT_82)s, actions_dbc_1.zis_validatie_fout_code, %(JSON_BUILD_OBJECT_83)s, actions_dbc_1.zis_validatie_datum_gevalideerd, %(JSON_BUILD_OBJECT_84)s, actions_dbc_1.task_event_allocation) AS "JSON_BUILD_OBJECT_1" 
FROM sd.actions_dbc AS actions_dbc_1 
WHERE CAST(CAST(actions_dbc_1.xmin AS TEXT) AS BIGINT) < %(param_1)s) AS anon_1]
[parameters: {'JSON_BUILD_OBJECT_2': 'id', 'JSON_BUILD_OBJECT_3': 'tcn', 'JSON_BUILD_OBJECT_4': 'patientnr', 'JSON_BUILD_OBJECT_5': 'patient_naam', 'JSON_BUILD_OBJECT_6': 'dbcnr', 'JSON_BUILD_OBJECT_7': 'dbc_datum', 'JSON_BUILD_OBJECT_8': 'prestatie_code', 'JSON_BUILD_OBJECT_9': 'specialisme', 'JSON_BUILD_OBJECT_10': 'toelichting', 'JSON_BUILD_OBJECT_11': 'rule_code', 'JSON_BUILD_OBJECT_12': 'task_status', 'JSON_BUILD_OBJECT_13': 'regel', 'JSON_BUILD_OBJECT_14': 'actie', 'JSON_BUILD_OBJECT_15': 'oplosser', 'JSON_BUILD_OBJECT_16': 'event_status', 'JSON_BUILD_OBJECT_17': 'event_datum', 'JSON_BUILD_OBJECT_18': 'tasklist_criteria', 'JSON_BUILD_OBJECT_19': 'created_by_user', 'JSON_BUILD_OBJECT_20': 'create_date', 'JSON_BUILD_OBJECT_21': 'modified_by_user', 'JSON_BUILD_OBJECT_22': 'modify_date', 'JSON_BUILD_OBJECT_23': 'valuation', 'JSON_BUILD_OBJECT_24': 'specialist_code', 'JSON_BUILD_OBJECT_25': 'kostenplaats_code', 'JSON_BUILD_OBJECT_26': 'specialisme_code', 'JSON_BUILD_OBJECT_27': 'oplosser_code', 'JSON_BUILD_OBJECT_28': 'kosten_deel', 'JSON_BUILD_OBJECT_29': 'honorarium_deel', 'JSON_BUILD_OBJECT_30': 'patient_geboortedatum', 'JSON_BUILD_OBJECT_31': 'username', 'JSON_BUILD_OBJECT_32': 'dbc_typering', 'JSON_BUILD_OBJECT_33': 'ste_dbc_id', 'JSON_BUILD_OBJECT_34': 'task_count', 'JSON_BUILD_OBJECT_35': 'dbc_einddatum', 'JSON_BUILD_OBJECT_36': 'zis_ziektegevalnr', 'JSON_BUILD_OBJECT_37': 'dbc_segment', 'JSON_BUILD_OBJECT_38': 'ind_medisch', 'JSON_BUILD_OBJECT_39': 'vc_lokatie_code', 'JSON_BUILD_OBJECT_40': 'kleur_code', 'JSON_BUILD_OBJECT_41': 'vc_laatste_uitvoerder_code', 'JSON_BUILD_OBJECT_42': 'task_role', 'JSON_BUILD_OBJECT_43': 'condition_nr', 'JSON_BUILD_OBJECT_44': 'task_allocation', 'JSON_BUILD_OBJECT_45': 'vc_bedrijf', 'JSON_BUILD_OBJECT_46': 'reference', 'JSON_BUILD_OBJECT_47': 'commentary', 'JSON_BUILD_OBJECT_48': 'operateur_naam', 'JSON_BUILD_OBJECT_49': 'event_details', 'JSON_BUILD_OBJECT_50': 'task_revenue_code', 'JSON_BUILD_OBJECT_51': 'verbandscombinatie_nr', 'JSON_BUILD_OBJECT_52': 'declaratie_code', 'JSON_BUILD_OBJECT_53': 'vc_debiteur_code', 'JSON_BUILD_OBJECT_54': 'characteristics', 'JSON_BUILD_OBJECT_55': 'agenda_code', 'JSON_BUILD_OBJECT_56': 'vgn_zorgproduct', 'JSON_BUILD_OBJECT_57': 'afgeleid_zorgproduct', 'JSON_BUILD_OBJECT_58': 'contact_email', 'JSON_BUILD_OBJECT_59': 'zorgverzekeraar', 'JSON_BUILD_OBJECT_60': 'rule_priority', 'JSON_BUILD_OBJECT_61': 'event_priority', 'JSON_BUILD_OBJECT_62': 'event_reference_date', 'JSON_BUILD_OBJECT_63': 'vc_afwijkend_zp_reden', 'JSON_BUILD_OBJECT_64': 'specialist_naam', 'JSON_BUILD_OBJECT_65': 'zis_validatie_fout_omschr', 'JSON_BUILD_OBJECT_66': 'rule_status', 'JSON_BUILD_OBJECT_67': 'user_priority', 'JSON_BUILD_OBJECT_68': 'hoofdbehandelaar_code', 'JSON_BUILD_OBJECT_69': 'loid', 'JSON_BUILD_OBJECT_70': 'uitvoerende_oe', 'JSON_BUILD_OBJECT_71': 'status_code', 'JSON_BUILD_OBJECT_72': 'checksum', 'JSON_BUILD_OBJECT_73': 'zis_validatie_fout_datum', 'JSON_BUILD_OBJECT_74': 'oplosser_d2a', 'JSON_BUILD_OBJECT_75': 'task_allocation_d2a', 'JSON_BUILD_OBJECT_76': 'username_d2a', 'JSON_BUILD_OBJECT_77': 'sub_specialisme_code', 'JSON_BUILD_OBJECT_78': 'vc_commentary', 'JSON_BUILD_OBJECT_79': 'hix_fout_opmerking', 'JSON_BUILD_OBJECT_80': 'type_verwijzer', 'JSON_BUILD_OBJECT_81': 'zis_validatie_fout_status', 'JSON_BUILD_OBJECT_82': 'zis_validatie_fout_code', 'JSON_BUILD_OBJECT_83': 'zis_validatie_datum_gevalideerd', 'JSON_BUILD_OBJECT_84': 'task_event_allocation', 'param_1': 62355721}]
 0:00:02.510704 (2.51 sec)

```

**Comment by d2a-raudenaerde** [comment]
The table ddl:

```
CREATE TABLE sd.actions_dbc (
	id int8 NULL,
	tcn int8 NULL,
	patientnr text NULL,
	patient_naam varchar(50) NULL,
	dbcnr text NULL,
	dbc_datum timestamp NULL,
	prestatie_code varchar(128) NULL,
	specialisme text NULL,
	toelichting text NULL,
	rule_code varchar(16) NULL,
	task_status int4 NULL,
	regel varchar(128) NULL,
	actie varchar(128) NULL,
	oplosser text NULL,
	event_status int4 NULL,
	event_datum timestamp NULL,
	tasklist_criteria varchar(128) NULL,
	created_by_user varchar(128) NULL,
	create_date timestamp NULL,
	modified_by_user varchar(128) NULL,
	modify_date timestamp NULL,
	valuation numeric(9, 2) NULL,
	specialist_code varchar(10) NULL,
	kostenplaats_code varchar(10) NULL,
	specialisme_code text NULL,
	oplosser_code text NULL,
	kosten_deel numeric(9, 2) NULL,
	honorarium_deel numeric(9, 2) NULL,
	patient_geboortedatum timestamp NULL,
	username text NULL,
	dbc_typering varchar(25) NULL,
	ste_dbc_id int8 NULL,
	task_count int4 NULL,
	dbc_einddatum timestamp NULL,
	zis_ziektegevalnr text NULL,
	dbc_segment varchar(1) NULL,
	ind_medisch varchar(1) NULL,
	vc_lokatie_code text NULL,
	kleur_code varchar(20) NULL,
	vc_laatste_uitvoerder_code varchar(8) NULL,
	task_role text NULL,
	condition_nr int4 NULL,
	task_allocation text NULL,
	vc_bedrijf text NULL,
	reference varchar(512) NULL,
	commentary text NULL,
	operateur_naam text NULL,
	event_details varchar(4096) NULL,
	task_revenue_code text NULL,
	verbandscombinatie_nr text NULL,
	declaratie_code varchar(7) NULL,
	vc_debiteur_code varchar(30) NULL,
	"characteristics" text NULL,
	agenda_code varchar(50) NULL,
	vgn_zorgproduct varchar(128) NULL,
	afgeleid_zorgproduct varchar(128) NULL,
	contact_email text NULL,
	zorgverzekeraar varchar(60) NULL,
	rule_priority text NULL,
	event_priority int4 NULL,
	event_reference_date date NULL,
	vc_afwijkend_zp_reden varchar(50) NULL,
	specialist_naam text NULL,
	zis_validatie_fout_omschr text NULL,
	rule_status text NULL,
	user_priority int4 NULL,
	hoofdbehandelaar_code varchar(10) NULL,
	loid text NULL,
	uitvoerende_oe varchar(8) NULL,
	status_code text NULL,
	checksum text NULL,
	zis_validatie_fout_datum timestamp NULL,
	oplosser_d2a text NULL,
	task_allocation_d2a text NULL,
	username_d2a text NULL,
	sub_specialisme_code text NULL,
	vc_commentary text NULL,
	hix_fout_opmerking text NULL,
	type_verwijzer text NULL,
	zis_validatie_fout_status text NULL,
	zis_validatie_fout_code text NULL,
	zis_validatie_datum_gevalideerd date NULL,
	task_event_allocation text NULL
);
```

**Comment by d2a-raudenaerde** [comment]
Seems related to: https://www.postgresql.org/message-id/E0EF3255-BC7C-4368-84CD-DF75325901B9%40inf-it.com

**Comment by toluaina** [comment]
Yes this was reported previously [here](https://github.com/toluaina/pgsync/issues/93)
Afraid I can't think of an easy work around.

**Comment by toluaina** [comment]
I can document that as a limitation. Do you really need all those columns though ? If you only need a subset you can list the columns you need and this will work.

**Comment by d2a-raudenaerde** [comment]
I do need that. I'm investigating tooling for migrating our search-based BI (currently built directly on Lucene and uses custom code that does the DB extraction)  to a ES based solution with a more-realtime-data-push architecture. We need to filter/sort on all the given fields in different scenarios.

**Comment by cocinfar** [comment]
Hello,

In my case I need a way to index tables with more than 50 fields as we have flat representations of inherited tables in ES. One of them has up to 600 fields in the same ElasticSearch index. We have it setup as a view.

I have done some investigation and found out that we could use ROW_TO_JSON instead of JSON_OBJECT. The changes needed don't seem to be too much. We would need to convert someting like this:

`
select JSON_OBJECT(array['id', cast(id as character varying), 'name', cast(name as character varying)])
from sdccs_gui_types_sd_object
limit 10;
`

Into this:

`
select ROW_TO_JSON(o)
from (select * from sdccs_gui_types_cms_migrated_document_v3_es_view) o
limit 10;
`

This way we would support any number of columns from Postgres into ElasticSearch.

@toluaina I want to help! Where should I start? I am not very versed in sqlalchemy but very experienced in python and other development languages. I have been going over the code but it would seem I would need to do changes in a lot of places...

**Comment by smokedsalmonbagel** [comment]
Just ran into this issue.  We have created a deformalized table for pgsync to solve out of disk space errors on postgres.  Now we are seeing this issue with 59 columns.  Two questions:
-What is the limit on columns (I am stuck with brute forcing it by slowly reducing the # of cols. )
-@cocinfar - I like your approach.  Going to try it out.  What version of pgsync are  you using?  From what you said it sounds like this only works with bootstrap (bulk inserts to ES).
-@toluaina -  any chance this could be added to the main branch?

**Comment by toluaina** [comment]
Sorry for the delay. I feel this suggestion increases complexity in an already complex function. This also needs to be applied in a few areas.

**Comment by toluaina** [comment]
The limit is 100 as described [here](https://www.postgresql.org/docs/current/runtime-config-preset.html#max_function_args)

**Comment by 5221txp** [comment]
I update for the change if it does not have any performance penalty 
We had to run a patched version of 2.1.9 with the fix from @cocinfar 
I think it's pretty common to have more than 100 columns table so this will be  limitation for many users

**Comment by rafaelvascc** [comment]
@5221txp Hi. Could you please provide the steps of how to implement your solution? I'm not very good with python but we need this tool running for you dbs.
Thanks.

**Comment by cocinfar** [comment]
> @5221txp Hi. Could you please provide the steps of how to implement your solution? I'm not very good with python but we need this tool running for you dbs. Thanks.

You just need to git clone the most recent version of pgsync and then in the file pgsync/querybuilder.py search for "def _root". Replace the whole thing with what I placed above:

def _root(self, node):
    # Create batches of 100 columns and concat them into a single JSON object inside Postgresql.
    # This is necessary because Postgresql has a limit of 100 parameters per function call. This means that we could only have up to 50 fields in a table to be synchronized.
    # This way we can support an "unlimited" number of fields (up to postgres' 1600 field limit per table).
    concat_columns = sa.func.JSONB_BUILD_OBJECT(*node.columns[:100])
    concat_array = sa.func.JSONB_BUILD_ARRAY(
        *[
            child._subquery.c._keys
            for child in node.children[:100]
            if hasattr(
                child._subquery.c,
                "_keys",
            )
        ])
    if len(node.columns) > 100:
        n = 100
        while n < len(node.columns):
            concat_columns = concat_columns.concat(sa.func.JSONB_BUILD_OBJECT(*node.columns[n:n+100]))
            concat_array = concat_array.concat(sa.func.JSONB_BUILD_ARRAY(
                    *[
                        child._subquery.c._keys
                        for child in node.children[n:n+100]
                        if hasattr(
                            child._subquery.c,
                            "_keys",
                        )
                    ]
                ))
            n += 100

    columns = [
        concat_array,
        concat_columns,
        *node.primary_keys,
    ]

    node._subquery = sa.select(columns)

For a quick and dirty fix here is the whole file already changed:

[querybuilder.py.txt](https://github.com/toluaina/pgsync/files/7850073/querybuilder.py.txt)

You need to remove .txt in the end of the filename.

Hope it works!

**Comment by cocinfar** [comment]
> Just ran into this issue. We have created a deformalized table for pgsync to solve out of disk space errors on postgres. Now we are seeing this issue with 59 columns. Two questions: -What is the limit on columns (I am stuck with brute forcing it by slowly reducing the # of cols. ) -@cocinfar - I like your approach. Going to try it out. What version of pgsync are you using? I get a `ImportError: cannot import name 'get_primary_keys' from 'pgsync.base'` From what you said it sounds like this only works with bootstrap (bulk inserts to ES). -@toluaina - any chance this could be added to the main branch?

I am using the most recent version from master branch.

**Comment by rafaelvascc** [comment]
@ansersolutions Unfortunately that didin't work for us we got hits error:

pgsync_1  | --------------------------------------------------------------------------------
pgsync_1  | {'_auto_correlate': True, '_raw_columns': [<sqlalchemy.sql.elements.BinaryExpression object at 0x7fc17213d990>, <sqlalchemy.sql.elements.BinaryExpression object at 0x7fc17213d890>, Column('Id', UUID(), table=<anon_1>, primary_key=True, nullable=False)], '_label_style': symbol('LABEL_STYLE_DISAMBIGUATE_ONLY'), '_bind': None, '_all_selected_columns': [<sqlalchemy.sql.elements.BinaryExpression object at 0x7fc17213d990>, <sqlalchemy.sql.elements.BinaryExpression object at 0x7fc17213d890>, Column('Id', UUID(), table=<anon_1>, primary_key=True, nullable=False)], '_memoized_keys': frozenset({'_all_selected_columns'})}
pgsync_1  | --------------------------------------------------------------------------------
pgsync_1  |  0:00:00.978280 (0.98 sec)
pgsync_1  | Traceback (most recent call last):
pgsync_1  |   File "/usr/local/bin/pgsync", line 7, in <module>
pgsync_1  |     sync.main()
pgsync_1  |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
pgsync_1  |     return self.main(*args, **kwargs)
pgsync_1  |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1053, in main
pgsync_1  |     rv = self.invoke(ctx)
pgsync_1  |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
pgsync_1  |     return ctx.invoke(self.callback, **ctx.params)
pgsync_1  |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 754, in invoke
pgsync_1  |     return __callback(*args, **kwargs)
pgsync_1  |   File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 1139, in main
pgsync_1  |     sync.pull()
pgsync_1  |   File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 1006, in pull
pgsync_1  |     self.sync(self._sync(txmin=txmin, txmax=txmax))
pgsync_1  |   File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 875, in sync
pgsync_1  |     self.es.bulk(self.index, docs)
pgsync_1  |   File "/usr/local/lib/python3.7/site-packages/pgsync/elastichelper.py", line 133, in bulk
pgsync_1  |     raise_on_error=raise_on_error,
pgsync_1  |   File "/usr/local/lib/python3.7/site-packages/elasticsearch/helpers/actions.py", line 484, in parallel_bulk
pgsync_1  |     actions, chunk_size, max_chunk_bytes, client.transport.serializer
pgsync_1  |   File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 748, in next
pgsync_1  |     raise value
pgsync_1  |   File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 121, in worker
pgsync_1  |     result = (True, func(*args, **kwds))
pgsync_1  |   File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 140, in _helper_reraises_exception
pgsync_1  |     raise ex
pgsync_1  |   File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 292, in _guarded_task_generation
pgsync_1  |     for i, x in enumerate(iterable):
pgsync_1  |   File "/usr/local/lib/python3.7/site-packages/elasticsearch/helpers/actions.py", line 155, in _chunk_actions
pgsync_1  |     for action, data in actions:
pgsync_1  |   File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 818, in _sync
pgsync_1  |     count: int = self.fetchcount(node._subquery)
pgsync_1  |   File "/usr/local/lib/python3.7/site-packages/pgsync/base.py", line 896, in fetchcount
pgsync_1  |     statement.original.with_only_columns(
pgsync_1  | AttributeError: 'Select' object has no attribute 'original'

Our schema is something like this

[
    {
        "database": "integrationdb",
        "index": "es.somestuff",
        "nodes": {
            "table": "Stuff",
            "children": [                
                {
                    "table": "StuffProgress",
                    "relationship": {
                        "variant": "object",
                        "type": "one_to_many"
                    }
                },
                {
                    "table": "NestedStuff",
                    "relationship": {
                        "variant": "object",
                        "type": "one_to_many"
                    }
                }
            ]
        }
    }
]

**Comment by ansersolutions** [comment]
Hello @rafaelvascc. First of all: Greetings to Brazil! I am from Portugal! Oi cara, tudo bem? :)

I only tested this in plain tables without any relations... You are using nested tables so you will need to implement my changes elsewhere in the code. Like @toluaina said: This is a complex problem that needs to be addressed in multiple locations in the code. For plain tables, it works fine. That is the only change I did, because it was my need. For more complex scenarios, more code analysis and changes is needed in multiple locations.
What I tried to do was to show how "easy" it is to change the limit of 100 fields using batches. But someone needs to replicate this in the other places where this limitation happens.
Unfortunately I have found another way to solve my problem so I no longer needed to change the source code. I can, however, dedicate some time to this but I think I will need @toluaina help to know where to change this as I do not have the time to analyse ALL of the code... @toluaina  Could you give me some pointers as to where I should look to replicate my changes?

@rafaelvascc Is there a way you could sync all of the tables as single tables, without any relations? Maybe the change in your code would be easier than pgsync.
What I did was sync all the SQL joins as a single index. This helped speed up me searches even with more fields in each index, because they are super simple... I have indexes with around 1600 fields working just fine with my changes to pgsync.

Maybe if you explain your need in more detail we can help you. If you want, you can obfuscate the table and field names or send me a direct message with your data. My email is fernando.gomes@anser.solutions.

**Comment by toluaina** [comment]
I implemented a potential solution in the master branch. This hasn't thoroughly been tested. Can you try this and let me know.

**Comment by rafaelvascc** [comment]
@toluaina Thanks for the change. I tested here and look like using my schema, on the the first child collection "StuffProgress" was synced in elasticsearch , the second one "NestedStuff" seems to be ignored.
Also i'm not seeing pgsync's output in the console, so i can't keep track of what it is doing.

@ansersolutions Hi Fernando. We can't change our schema. We are already using it in production and changing it will break dynamic queries some clients sends to us.

**Comment by toluaina** [comment]
@rafaelvascc 

- is there any output in the console at all?
- Is the first collection working with > 100 columns. 
- Can I see the structure of the schema?
- It might be more efficient to run multiple instances of pgsync with different collections.
- Althought both in the same should work.

**Comment by rafaelvascc** [comment]
@toluaina 
- The only console output i was able to see was an error connecting to elasticsearch before i started it, nothing else
- The schema is like this
[
{
"database": "integrationdb",
"index": "es.somestuff",
"nodes": {
"table": "Stuff",
"children": [
{
"table": "StuffProgress",
"relationship": {
"variant": "object",
"type": "one_to_many"
}
},
{
"table": "NestedStuff",
"relationship": {
"variant": "object",
"type": "one_to_many"
}
}
]
}
}
]

- Stuff has 150 columns, StuffProgres has 10, and NestedStuff has 60

Thanks.

**Comment by 5221txp** [comment]
@rafaelvascc Sorry I didn't have time to check github the last two weeks 
I need to sync a table with more than 100 columns, its child tables have only 3 or 4 columns and it works fine with the patch suggested by cocinfar
I'll test the change in master branch next weed
Thanks @toluaina

**Comment by toluaina** [comment]
@rafaelvascc 
@d2a-raudenaerde 
@smokedsalmonbagel 
@ansersolutions 
please let me know if this resolves this issue.

**Comment by toluaina** [comment]
This has been resolved. Feel free to reopen if you need to

**Comment by Dipesh-Aspire** [comment]
@toluaina Somehow I started getting this issue after upgrading the version to 3.1.0.
Is there any dependency of psql engine version or any python version?
Actually I don't want to spend time in re-arranging my schema jsons as they were already working and the 
project is stable.
So just want this to be working without making any changes in the files.

<img width="1680" alt="Screenshot 2024-02-01 at 16 10 56" src="https://github.com/toluaina/pgsync/assets/67418733/4c049878-2b94-4684-bbaf-0cdee8423128">
