### ISSUE TITLE
Redis version and necessary?

### ISSUE THREAD

**Issue by EgoPingvina** [toluaina/pgsync#157]
In `Quickstart` block written that `Redis 3.1.0` is needed
![image](https://user-images.githubusercontent.com/9804340/129680570-72b64a69-2fc2-470c-be7e-e85add3add10.png)
but this version [doesn`t exist ](https://download.redis.io/releases/)
![image](https://user-images.githubusercontent.com/9804340/129681514-4e37ece0-0ccd-48a0-b2f3-b5efec0d7ef4.png)

And I have 2 questions: which version should I install and for what redis needed?

**Comment by EgoPingvina** [comment]
In addition, I work on `windows server` and there is no port of `Redis` above the version [3.0.504](https://github.com/microsoftarchive/redis/releases/tag/win-3.0.504)

**Comment by toluaina** [comment]
You can also use the latest redis version.

**Comment by EgoPingvina** [comment]
I can`t use lates version, because I can`t find last release ported for windows server

**Comment by toluaina** [comment]
I have no experience with windows server. 
I don't think this would be an issue. 
The requirements is only a guideline for the version tested with. 
You can try the version of Redis available to you.

**Comment by EgoPingvina** [comment]
Ok, thx.
For another searchers, I found 3.2.100 [here](https://github.com/microsoftarchive/redis/releases)
