### ISSUE TITLE
pgsync.exc.SchemaError: 'Incompatible schema. Please run v2 schema migration' on Book example

### ISSUE THREAD

**Issue by EgoPingvina** [toluaina/pgsync#158]
PGSync version: 
2.1.1
Postgres version: 
PostgreSQL 13.1, compiled by Visual C++ build 1914, 64-bit
Elasticsearch version: 
7.13.4
Redis version: 
3.2.100
Python version: 
3.9.6
Problem Description: 
I invoke `python C:\Users\Administrator\AppData\Local\Programs\Python\Python39\Scripts\bootstrap --config C:\pgsync\schema.json`

`schema.json` based on book example:

> [
> 	{
>         "database": "pgsync-test",
>         "index": "books",
>         "nodes": [
> 			{
> 				"table": "book",
> 				"columns": [
> 	    			"isbn",
> 	    			"title",
> 	    			"description"
> 				],
> 				"children": [
> 	    			{
> 	    				"table": "author",
> 	    				"columns": [
> 	        				"name"
> 	    				]
> 	    			}
> 				]
> 			}
> 		]
> 	}
> ]

the database created according to your example for clarity
![image](https://user-images.githubusercontent.com/9804340/129698767-14f6f36b-aea4-43a4-900c-7fa0957d27d5.png)

Error Message (if any): 

> Traceback (most recent call last):
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\Scripts\bootstrap", line 66, in <module>
>     main()
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1137, in __call__
>     return self.main(*args, **kwargs)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1062, in main
>     rv = self.invoke(ctx)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1404, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 763, in invoke
>     return __callback(*args, **kwargs)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\Scripts\bootstrap", line 57, in main
>     sync = Sync(document, verbose=verbose, repl_slots=False, **params)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\pgsync\sync.py", line 82, in __init__
>     self.validate(repl_slots=repl_slots)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\pgsync\sync.py", line 91, in validate
>     raise SchemaError(
> pgsync.exc.SchemaError: 'Incompatible schema. Please run v2 schema migration'

**Comment by toluaina** [comment]
Thats the old schema format. It should be something like 
```
[
    {
        "database":"pgsync-test",
        "index":"books",
        "nodes":{
            "table":"book",
            "columns":[
                "isbn",
                "title",
                "description"
            ],
            "children":[
                {
                    "table":"author",
                    "columns":[
                        "name"
                    ]
                }
            ]
        }
    }
]
```

**Comment by EgoPingvina** [comment]
Ok. Also it is needed to change table names to upper case. But it gives an error again:

> C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\elasticsearch\connection\base.py:208: ElasticsearchWarning: Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.13/security-minimal-setup.html to enable security.
>   warnings.warn(message, category=ElasticsearchWarning)
> Traceback (most recent call last):
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\Scripts\bootstrap", line 66, in <module>
>     main()
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1137, in __call__
>     return self.main(*args, **kwargs)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1062, in main
>     rv = self.invoke(ctx)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1404, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 763, in invoke
>     return __callback(*args, **kwargs)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\Scripts\bootstrap", line 57, in main
>     sync = Sync(document, verbose=verbose, repl_slots=False, **params)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\pgsync\sync.py", line 82, in __init__
>     self.validate(repl_slots=repl_slots)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\pgsync\sync.py", line 149, in validate
>     root = self.tree.build(self.nodes)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\pgsync\node.py", line 278, in build
>     node.add_child(self.build(child))
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\pgsync\node.py", line 204, in add_child
>     raise RelationshipError(
> pgsync.exc.RelationshipError: 'Relationship not present on "public.Author"'

**Comment by toluaina** [comment]
Sorry the doc is not accurate. author requires a relationship because it does not have a direct relationship with book.
Can you use the [example](https://github.com/toluaina/pgsync/blob/master/examples/book/schema.json) in the repo

**Comment by EgoPingvina** [comment]
It's too big for newbe, how can i reproduce it (many tables, plugins(what is it?), etc)?

I append `relationship` to `children`

`[
    {
        "database":"pgsync_test",
        "index":"bookstest",
        "nodes":{
            "table":"Book",
            "columns":[
                "isbn",
                "title",
                "description"
            ],
            "children":[
                {
                    "table":"Author",
                    "columns":[
                        "name"
                    ],
		            "relationship": {
		                "variant": "object",
		                "type": "one_to_many",
                        "through_tables": [
                            "BookAuthor"
                        ]
		            }
                }
            ]
        }
    }
]`

`bootstrap` is now working,  I start `python C:\Users\Administrator\AppData\Local\Programs\Python\Python39\Scripts\pgsync --config C:\Credion\pgsync\schema.json --daemon` and when I add entity to any table it gives me an exception like here:
#137

**Comment by toluaina** [comment]
There are some simpler examples in the examples directory such as [quiz](https://github.com/toluaina/pgsync/tree/master/examples/quiz)

For the book example you can just try this schema

```
[
    {
        "database": "pgsync-test",
        "index": "books",
        "nodes": {
            "table": "book",
            "columns": [
                "isbn",
                "title",
                "description"
            ]
        }
    }
]
```

**Comment by EgoPingvina** [comment]
Db with one table works fine and elasticsearch work too, thx!

But why thouble happens when DB has any table with relations? 
Constraints for FK are correct:
![image](https://user-images.githubusercontent.com/9804340/129886272-7a517ce5-d3e7-4df4-91a3-01e048a40ff4.png)
![image](https://user-images.githubusercontent.com/9804340/129886309-73aa96e2-b040-4c53-b27b-6b7e869d4ada.png)
![image](https://user-images.githubusercontent.com/9804340/129886343-9cae42ff-f664-4b09-8fcd-414b25914260.png)

What could be wrong?

**Comment by EgoPingvina** [comment]
an attempt to downgrade to version 2.0.0 did not help either

**Comment by toluaina** [comment]
Can you provide your current schema?
The book example is a complete working example. 
Can you also provide the error message

**Comment by EgoPingvina** [comment]
schema:
`[
    {
        "database":"pgsync_test",
        "index":"bookstest",
        "nodes":{
            "table":"Book",
            "columns":[
                "isbn",
                "title",
                "description"
            ],
            "children":[
                {
                    "table":"Author",
                    "columns":[
                        "name"
                    ],
		            "relationship": {
		                "variant": "object",
		                "type": "one_to_many",
                        "through_tables": [
                            "BookAuthor"
                        ]
		            }
                }
            ]
        }
    }
]`

Error message was above:
> :\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\elasticsearch\connection\base.py:208: ElasticsearchWarning: Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.13/security-minimal-setup.html to enable security.
> warnings.warn(message, category=ElasticsearchWarning)
> Traceback (most recent call last):
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\Scripts\bootstrap", line 66, in
> main()
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1137, in **call**
> return self.main(*args, **kwargs)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1062, in main
> rv = self.invoke(ctx)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1404, in invoke
> return ctx.invoke(self.callback, **ctx.params)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 763, in invoke
> return __callback(*args, **kwargs)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\Scripts\bootstrap", line 57, in main
> sync = Sync(document, verbose=verbose, repl_slots=False, **params)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\pgsync\sync.py", line 82, in **init**
> self.validate(repl_slots=repl_slots)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\pgsync\sync.py", line 149, in validate
> root = self.tree.build(self.nodes)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\pgsync\node.py", line 278, in build
> node.add_child(self.build(child))
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\pgsync\node.py", line 204, in add_child
> raise RelationshipError(
> pgsync.exc.RelationshipError: 'Relationship not present on "public.Author"'

**Comment by toluaina** [comment]
Your schema is incorrect. Database tables names should be case sensitive and there is no such table as BookAuthor.
Perhaps book_author?

**Comment by EgoPingvina** [comment]
@toluaina https://github.com/toluaina/pgsync/issues/158#issuecomment-901018091
I know, that it is case sensitive, names are correst, see sreenshots.

**Comment by toluaina** [comment]
Closing as the original issue has already been resolved.
