### ISSUE TITLE
How can I use a custom mapping for the fields posted to by pgsync

### ISSUE THREAD

**Issue by jsindos** [toluaina/pgsync#170]
PGSync version: 
2.1.1
Postgres version: 
13.3
Elasticsearch version: 
7.14.0
Redis version: 
6.2.5
Python version: 
3.9.6
Problem Description: 
How can I use a custom mapping for the fields posted to by pgsync? I want to use the `edge_ngram` filter on the `name` field, as shown below:

```
curl -X PUT "localhost:9200/products?pretty" -H 'Content-Type: application/json' -d'
{
    "mappings": {
         "properties": {
             "name": {
                 "analyzer": "edge_ngram_analyzer",
                 "search_analyzer": "standard",
                 "type": "text"
             }
         }
    },
    "settings": {
        "analysis": {
            "filter": {
                "edge_ngram": {
                "type": "edge_ngram",
                "min_gram": "2",
                "max_gram": "25",
                "token_chars": ["letter", "digit"]
                }
            },
            "analyzer": {
                "edge_ngram_analyzer": {
                "filter": ["lowercase", "edge_ngram"],
                "tokenizer": "standard"
                }
            }
        }
    }
}
'
```

Here is my schema.json file used by pgsync:

```
[
    {
        "database": "pope",
        "index": "products",
        "nodes": {
            "table": "products",
            "columns": [
                "name"
            ]
        }
    }
]
```

However, when I sync Postgres with Elasticsearch using pgsync the `name` field is not present in the document (only in `_source`):

```
curl -X GET "localhost:9200/products/_search?pretty" 
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 2,
      "relation" : "eq"
    },
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "products",
        "_type" : "_doc",
        "_id" : "1",
        "_score" : 1.0,
        "_source" : {
          "id" : 1,
          "name" : "Shampoo"
        }
      }
    ]
}
```

I am going to investigate if it has anything to do with `"_type": "_doc"` on the document, as I read [mapping types have been removed in Elasticsearch 7](https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html#_migrating_multi_type_indices_to_single_type).

Error Message (if any): 

```


```

**Comment by jsindos** [comment]
Great thank you @toluaina it is now creating the mappings for the name field:

```
curl -X GET "localhost:9200/products/_mapping?pretty"
{
  "products" : {
    "mappings" : {
      "properties" : {
        "_meta" : {
          "type" : "object"
        },
        "name" : {
          "type" : "text",
          "analyzer" : "edge_ngram_analyzer",
          "search_analyzer" : "standard"
        }
      }
    }
  }
}
```

**Comment by jsindos** [comment]
Hi @toluaina I am also wondering if it is possible to apply the same mapping for a children field? I am trying the following, and have also tried re-naming `name` of the `categories` mapping to others, like `categories`, and `categories.name`, but when I query `curl -X GET "localhost:9200/products/_mapping?pretty"` it doesn't appear to be working.

```
[
    {
        "database": "pope",
        "index": "products",
        "settings": {
            "analysis": {
                "filter": {
                    "edge_ngram": {
                        "type": "edge_ngram",
                        "min_gram": "2",
                        "max_gram": "25",
                        "token_chars": ["letter", "digit"]
                    }
                },
                "analyzer": {
                    "edge_ngram_analyzer": {
                        "filter": ["lowercase", "edge_ngram"],
                        "tokenizer": "standard"
                    }
                }
            }
        },
        "nodes": {
            "table": "products",
            "columns": [
                "name"
            ],
            "transform": {
                "mapping": {
                    "name": {
                        "type": "text",
                        "analyzer": "edge_ngram_analyzer",
                        "search_analyzer": "standard"
                    }
                }
            },
            "children": [
                {
                    "table": "categories",
                    "label": "category",
                    "columns": [
                        "name"
                    ],
                    "relationship": {
                        "variant": "scalar",
                        "type": "one_to_one"
                    },
                    "transform": {
                        "mapping": {
                            "name": {
                                "type": "text",
                                "analyzer": "edge_ngram_analyzer",
                                "search_analyzer": "standard"
                            }
                        }
                    }
                }
            ]
        }
    }
]
```

**Comment by jsindos** [comment]
Oh I see in the [example](https://github.com/toluaina/pgsync/blob/master/examples/book/schema.json) that you do underscore case (`publisher_id`), I'll try that now.

**Comment by jsindos** [comment]
Hi @toluaina, I tried doing re-naming the mapping field to `categories_name` and `category_name` and neither worked, it also seems in the [example](https://github.com/toluaina/pgsync/blob/master/examples/book/schema.json) there is an inconsistency. `continent` using the mapping `name` directly of its column name, while `publisher` uses underscore case like `{tableName}_{columnName}`.

                                    "children": [
                                        {
                                            "table": "continent",
                                            "columns": [
                                                "name"
                                            ],
                                            "transform": {
                                                "mapping": {
                                                    "name": {
                                                        "type": "keyword"
                                                    }
                                                }
                                            },

**Comment by jsindos** [comment]
It seems I can get it to work if I pre-emptively create the mappings before I run `pgsync`, however it is throwing an error for the `tags` which use a `one_to_many` relationship with a through table, I'll investigate this next.

```
curl -X PUT "localhost:9200/products?pretty" -H 'Content-Type: application/json' -d'
{
   "mappings":{
      "properties":{
         "name":{
            "analyzer":"edge_ngram_analyzer",
            "search_analyzer":"standard",
            "type":"text"
         },
         "category":{
            "analyzer":"edge_ngram_analyzer",
            "search_analyzer":"standard",
            "type":"text"
         },
         "maker":{
            "analyzer":"edge_ngram_analyzer",
            "search_analyzer":"standard",
            "type":"text"
         },
         "tags":{
            "analyzer":"edge_ngram_analyzer",
            "search_analyzer":"standard",
            "type":"text"
         }
      }
   },
   "settings":{
      "analysis":{
         "filter":{
            "edge_ngram":{
               "type":"edge_ngram",
               "min_gram":"2",
               "max_gram":"25",
               "token_chars":[
                  "letter",
                  "digit"
               ]
            }
         },
         "analyzer":{
            "edge_ngram_analyzer":{
               "filter":[
                  "lowercase",
                  "edge_ngram"
               ],
               "tokenizer":"standard"
            }
         }
      }
   }
}
'
```

**Comment by jsindos** [comment]
I solved this problem by first posting my custom mapping (turns out it was working all along). For anyone that is curious, here is the mapping and schema that I used.

mapping:

```
curl -X PUT "localhost:9200/products?pretty" -H 'Content-Type: application/json' -d'
{
   "mappings":{
      "properties":{
         "name":{
            "analyzer":"edge_ngram_analyzer",
            "search_analyzer":"standard",
            "type":"text"
         },
         "category":{
            "analyzer":"edge_ngram_analyzer",
            "search_analyzer":"standard",
            "type":"text"
         },
         "maker":{
            "analyzer":"edge_ngram_analyzer",
            "search_analyzer":"standard",
            "type":"text"
         },
         "tags":{
            "type":"object",
            "properties":{
               "name":{
                  "type":"text",
                  "analyzer":"edge_ngram_analyzer",
                  "search_analyzer":"standard"
               }
            }
         }
      }
   },
   "settings":{
      "analysis":{
         "filter":{
            "edge_ngram":{
               "type":"edge_ngram",
               "min_gram":"2",
               "max_gram":"25",
               "token_chars":[
                  "letter",
                  "digit"
               ]
            }
         },
         "analyzer":{
            "edge_ngram_analyzer":{
               "filter":[
                  "lowercase",
                  "edge_ngram"
               ],
               "tokenizer":"standard"
            }
         }
      }
   }
}
'
```

pgsync schema:

```
[
    {
        "database": "pope",
        "index": "products",
        "nodes": {
            "table": "products",
            "columns": [
                "name"
            ],
            "children": [
                {
                    "table": "categories",
                    "label": "category",
                    "columns": [
                        "name"
                    ],
                    "relationship": {
                        "variant": "scalar",
                        "type": "one_to_one"
                    }
                },
                {
                    "table": "makers",
                    "label": "maker",
                    "columns": [
                        "name"
                    ],
                    "relationship": {
                        "variant": "scalar",
                        "type": "one_to_one"
                    }
                },
                {
                    "table": "tags",
                    "columns": [
                        "name"
                    ],
                    "relationship": {
                        "variant": "object",
                        "type": "one_to_many",
                        "through_tables": [
                            "productsTags"
                        ]
                    }
                }
            ]
        }
    }
]
```

**Comment by toluaina** [comment]
You can now add the a custom mapping in the schema.json [directly](https://github.com/toluaina/pgsync/blob/master/examples/book/schema.json#L5-L8)

**Comment by joshuafernandes1996** [comment]
hi @toluaina , is it possible to add custom mapping something like below, look at customerAddress => type: "nested"

{
    "settings": {
        "analysis": {
            "analyzer": {
                "analyzer_keyword": {
                    "tokenizer": "whitespace",
                    "filter": [
                        "trim",
                        "lowercase"
                    ]
                }
            }
        },
        "mappings": {
            "properties": {
                "firstName": {
                    "type": "text",
                    "analyzer": "analyzer_keyword",
                    "fields": {
                        "raw": {
                            "type": "keyword",
                            "normalizer": "sorting"
                        }
                    }
                },
                "lastName": {
                    "type": "text",
                    "analyzer": "analyzer_keyword",
                    "fields": {
                        "raw": {
                            "type": "keyword",
                            "normalizer": "sorting"
                        }
                    }
                },
                "customerAddress": {
                    "type": "nested",  // @toluaina this particular nested type is what I need
                    "properties": {
                        "zipCode": {
                            "type": "text",
                            "analyzer": "analyzer_keyword",
                            "fields": {
                                "raw": {
                                    "type": "keyword",
                                    "normalizer": "sorting"
                                }
                            }
                        },
                        "street": {
                            "type": "text",
                            "analyzer": "analyzer_keyword",
                            "fields": {
                                "raw": {
                                    "type": "keyword",
                                    "normalizer": "sorting"
                                }
                            }
                        },
                        "city": {
                            "type": "text",
                            "analyzer": "analyzer_keyword",
                            "fields": {
                                "raw": {
                                    "type": "keyword",
                                    "normalizer": "sorting"
                                }
                            }
                        },
                        "state": {
                            "type": "text",
                            "analyzer": "analyzer_keyword",
                            "fields": {
                                "raw": {
                                    "type": "keyword",
                                    "normalizer": "sorting"
                                }
                            }
                        },
                        "country": {
                            "type": "text",
                            "analyzer": "analyzer_keyword",
                            "fields": {
                                "raw": {
                                    "type": "keyword",
                                    "normalizer": "sorting"
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

**Comment by toluaina** [comment]
Afraid you'd have to specify [mapping](https://github.com/toluaina/pgsync/blob/master/examples/book/schema.json#L5-L9) and [settings](https://github.com/toluaina/pgsync/blob/master/examples/book/schema.json#L10-L35) separately as done in the example

**Comment by joshuafernandes1996** [comment]
@toluaina , I tried, but I see customerAddress coming twice once without the "type" nested and another as root object with type nested.

Do you have an example where I can achieve customerAddress(which is a child table) to be of type nested.
