### ISSUE TITLE
Running pgsync without changing the wal_level on production

### ISSUE THREAD

**Issue by kaggrwal** [toluaina/pgsync#173]
I'm trying to implement this in my current company, I got the following response from DevOps team-:
 
"I have had a read about setting the wal_level in a running system.
 
here´s the Postgres docu:
https://www.postgresql.org/docs/9.6/runtime-config-wal.html
 
here is an example:
https://stackoverflow.com/questions/67490668/changing-wal-level-on-postgresql-13-via-client-session-is-not-being-respecte
 
seems that it is not changeable in the running system.
 
and since we use the standard docker container for Postgres 13.3,
I don’t see a way to change that parameter."

Is there any way to run pgsync without changing wal_level. Kindly guide me for the same.

**Comment by toluaina** [comment]
You need to enable logical replication to use pgsync.
`wal_level` can be changed but it requires a system restart. 
You will need to customize the docker image to enable this or  
you can also use the debezium/postgres:13 image which already has logical replication enabled.

**Comment by Amine27** [comment]
Hi,
It can be changed using docker `command` parameter. For instance, add to your docker-compose.yml: `command: [ "postgres", "-c", "wal_level=logical" ]` 
Hope it will help.

**Comment by kaggrwal** [comment]
Hi,

The problem is that the DB instance is shared by many teams within the organization, so they can't shut it down/restart or migrate to another image. 

They have suggested using pgq to get the events and push them to elastic DB.
Let me know if there's any other solution.
Thanks

**Comment by kaggrwal** [comment]
Hi,

Can we do it via triggers, notifying the pgsync?
is it possible ?

**Comment by toluaina** [comment]
Afraid this is will not fully work.
The triggers alone is insufficient. 
If the daemon is not running and you make changes to the db insert, update delete. those change will be lost.

**Comment by kaggrwal** [comment]
@toluaina kindly support here

**Comment by toluaina** [comment]
That line number in the traceback no longer exists so you are not using the latest changes.
Can you try the latest code in master?

**Comment by kaggrwal** [comment]
I'm using docker image, 
When building I got version 2.1.7

`"Successfully installed black-21.9b0 boto3-1.18.59 botocore-1.21.59 bump2version-1.0.1 bumpversion-0.6.0 certifi-2021.10.8 charset-normalizer-2.0.6 click-8.0.3 elasticsearch-7.13.4 elasticsearch-dsl-7.4.0 environs-9.3.4 faker-9.3.1 greenlet-1.1.2 idna-3.2 importlib-metadata-4.8.1 jmespath-0.10.0 marshmallow-3.13.0 mypy-extensions-0.4.3 newrelic-7.0.0.166 pathspec-0.9.0 pgsync-2.1.7 platformdirs-2.4.0 psycopg2-binary-2.9.1 python-dateutil-2.8.2 python-dotenv-0.19.1 redis-3.5.3 regex-2021.10.8 requests-2.26.0 requests-aws4auth-1.1.1 s3transfer-0.5.0 six-1.16.0 sqlalchemy-1.4.25 sqlparse-0.4.2 text-unidecode-1.3 tomli-1.2.1 typed-ast-1.4.3 typing-extensions-3.10.0.2 urllib3-1.26.7 zipp-3.6.0"`

and this is the latest version in the pip repository.

**Comment by toluaina** [comment]
The changes were commit to master but not published to pip.
I have published a new version to pip with these changes now.

**Comment by kaggrwal** [comment]
Thanks, that error is gone now. 
But on bootstrapping, the following error comes:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1800, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InvalidSchemaName: no schema has been selected to create in`


Where do I have to provide the schema name, I have already provided it in schema.json.

**Comment by toluaina** [comment]
- You don't always need to provide a schema unless it's not `public`. 
- [Here](https://github.com/toluaina/pgsync/blob/master/examples/airbnb/schema.json) is an example that includes a schema.
- Is that the full traceback. It looks incomplete

**Comment by kaggrwal** [comment]
Our schema is not public. So, I have mentioned it in the schema.json. I'm attaching the logs and schema.json both. 

[bootstrap_logs.txt](https://github.com/toluaina/pgsync/files/7460706/bootstrap_logs.txt)

`[{
   "database": "rlm",
   "index": "logicalresources_2",
   "nodes": {
      "table": "ip_resource",
      "schema": "ip",
      "columns": [

      ],
      "children": [{
            "table": "resource_relationship",
            "schema": "ip",
            "columns": [

            ],
            "transform": {
               "mapping": {
                  "created_date": {
                     "type": "date"
                  },
                  "update_date": {
                     "type": "date"
                  }
               }
            },
            "relationship": {
               "variant": "object",
               "type": "one_to_many",
               "foreign_key": {
                  "child": ["source_resource_instance_id"],
                  "parent": ["resource_instance_id"]
               }
            }
         },
         {
            "table": "resource_characteristics",
            "schema": "ip",
            "columns": [

            ],
            "transform": {
               "mapping": {
                  "created_date": {
                     "type": "date"
                  },
                  "update_date": {
                     "type": "date"
                  }
               }
            },
            "relationship": {
               "variant": "object",
               "type": "one_to_many"
            }
         }
      ],
      "transform": {
         "mapping": {
            "created_date": {
               "type": "date"
            },
            "update_date": {
               "type": "date"
            },
            "ip_from_hash": {
               "type": "keyword"
            },
            "ip_to_hash": {
               "type": "keyword"
            },
            "number_of_items": {
               "type": "keyword"
            },
            "number_of_free_items": {
               "type": "keyword"
            }
         }
      }
   }
}]
`

**Comment by kaggrwal** [comment]
@toluaina any findings?

**Comment by toluaina** [comment]
Can you re-run and print out the value of schema on this [line](https://github.com/toluaina/pgsync/blob/master/pgsync/sync.py#L215) ?

i.e `print(f'schema: {schema}')`

**Comment by kaggrwal** [comment]
@toluaina , schema is printed fine. 

schema: ip
2021-11-18 12:41:06.290:ERROR:pgsync.base: Exception (psycopg2.errors.InvalidSchemaName) no schema has been selected to create in


But it shows no schema has been selected, am I missing any configuration here?

**Comment by toluaina** [comment]
It's a bit hard to track the issues here because your original issue has now changed scope.
Can you please re-open with the issue you are having.  
I am guessing wal_level is no longer a concern.

**Comment by kaggrwal** [comment]
@toluaina sure
