### ISSUE TITLE
Daemon not propagating more than one change to ES after restart  

### ISSUE THREAD

**Issue by imdeaconu** [toluaina/pgsync#174]
PGSync version: 2.1.1

Postgres version: 12 

Elasticsearch version: 7.14.1

Redis version:  5

Python version:  3.7

Problem Description: 

My data is not getting updated after the first interaction with the db (so, if I insert one new record, it gets propagated to es, but everything else gets ignored unless I restart my pgsync conttainer) .

Error Message (if any): 

Polling db construct: 28 item(s)
SELECT xid,
       DATA
FROM PG_LOGICAL_SLOT_GET_CHANGES(%(PG_LOGICAL_SLOT_GET_CHANGES_1)s, NULL, NULL)Polling db construct: 28 item(s)
Polling db construct: 28 item(s)
Polling db construct: 28 item(s)
Polling db construct: 28 item(s)
Polling db construct: 28 item(s)
Polling db construct: 28 item(s)
Polling db construct: 28 item(s)
Polling db construct: 28 item(s)
Polling db construct: 28 item(s)
Polling db construct: 28 item(s)
Polling db construct: 28 item(s)
Polling db construct: 28 item(s)
Polling db construct: 28 item(s)
Polling db construct: 28 item(s)
Polling db construct: 28 item(s)
Polling db construct: 28 item(s)
Polling db construct: 28 item(s)
Polling db construct: 28 item(s)
Polling db construct: 28 item(s)
Polling db construct: 28 item(s)
Polling db construct: 28 item(s)
Polling db construct: 28 item(s)
Polling db construct: 28 item(s)
Polling db construct: 35 item(s)
Polling db construct: 35 item(s)
Polling db construct: 35 item(s)
Polling db construct: 35 item(s)
Polling db construct: 35 item(s)

My schema:
[
    {
        "database": "construct",
        "index": "pg_posts",
        "nodes": {
            "table": "post",
            "schema": "public",
            "columns": [
                "title"
            ],
            "children": [
                {
                    "table": "artist",
                    "columns": [
                        "artist_id",
                        "artist_name"
                    ],
                    "relationship": {
                        "variant": "object",
                        "type": "one_to_many",
                        "through_tables": [
                            "post_artists"
                        ]

                    }
                },

                {
                    "table": "file",
                    "columns": [
                        "file_id",
                        "path"
                    ],
                    "relationship": {
                        "variant": "object",
                        "type": "one_to_many",
                        "through_tables": [
                            "post_files"
                        ]

                    }
                },

                {
                    "table": "category",
                    "columns": [
                        "category_id",
                        "category_name"
                    ],
                    "relationship": {
                        "variant": "object",
                        "type": "one_to_one"

                    }
                }
            ]

             
        }
    }
]

**Comment by toluaina** [comment]
A little hard to tell whats is going on.
A couple of suggestions

- Did you run bootstrap successfully?
- did you alter the structure of the schema.json
- There is a checkpoint file which maintains the state.
- Try deleting `.construct_pg_posts` and rerun

**Comment by imdeaconu** [comment]
Thanks for your help! I think bootstrap ran successfully. I deleted the checkpoint file and got this after the syncing was complete
` 0:00:00.765764 (0.77 sec)
Traceback (most recent call last):
  File "/usr/local/bin/pgsync", line 7, in <module>
    sync.main()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 1093, in main
    sync.pull()
  File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 961, in pull
    self.logical_slot_changes(txmin=txmin, txmax=txmax)
  File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 289, in logical_slot_changes
    self.sync_payloads(payloads)
  File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 829, in sync_payloads
    for doc in self._payloads(payloads):
  File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 649, in _payloads
    payloads,
  File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 356, in _insert
    filters[node.parent.table] = []
AttributeError: 'NoneType' object has no attribute 'table'`

**Comment by toluaina** [comment]
Sorry this was fixed in master. II will publish a new package shortly

**Comment by toluaina** [comment]
version 2.1.2 has been published and should solve the error above.

**Comment by toluaina** [comment]
Error has been resolved
