### ISSUE TITLE
ERROR:pgsync.base: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by AnkitKundariya** [toluaina/pgsync#176]
PGSync version: 
lastest
Postgres version: 
latest
Elasticsearch version: 
as per requirements.txt
Redis version: 
as per requirements.txt
Python version: 
Pyhton = 3.8
Problem Description: 

I guess there is some syntax error when I'm trying to get whether the DB user has `usesuper` permission 

I think the error caused by this line https://github.com/toluaina/pgsync/blob/master/pgsync/base.py#L99
where we try to do None[0]  which causes  'NoneType' object is not subscriptable

Error Message (if any): 

```
>>> from pgsync import base
>>> B = base.Base("testdb")
>>> B.has_permission(permission="usesuper", username="postgres")
2021-09-20 13:38:33.804:ERROR:pgsync.base: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pgsync/base.py", line 95, in has_permission
    return self.fetchone(
TypeError: 'NoneType' object is not subscriptable
False
>>> B.has_permission(permission="userepl", username="postgres")
True
>>> 


```

**Comment by toluaina** [comment]
Thanks this is a bug. That exception should return False when caught

**Comment by toluaina** [comment]
This has now been fixed. thanks

**Comment by toluaina** [comment]
Fixed
