### ISSUE TITLE
Latest release is incompatible with AWS OpenSearch

### ISSUE THREAD

**Issue by voyc-jean** [toluaina/pgsync#178]
PGSync version: 2.1.2
Postgres version: 12
Elasticsearch version: Opensearch 7.10
Redis version: 5.0.6
Python version: 3.8
Problem Description: 

The latest version of pgsync (2.1.2) bumps the version of the `elasticsearch` package to `7.14.1`. This version of the `elasticsearch` package is no longer compatible with AWS's Opensearch (formally Elasticsearch) service, as Elastic's clients now [block any 'unofficial' distribution of Elasticsearch](https://github.com/elastic/elasticsearch-py/issues/1639#issuecomment-883319286).

The latest compatible client, as [recommended by AWS](https://opensearch.org/docs/clients/index/), is 7.13.4

Error Message (if any): 
```
$ bootstrap --config /pgsync_schema.json
...
elasticsearch.exceptions.NotElasticsearchError: The client noticed that the server is not Elasticsearch and we do not support this unknown product
```

When attempting to install version 7.13.4 of the client:
```
The conflict is caused by:
    The user requested elasticsearch==7.13.4
    pgsync 2.1.2 depends on elasticsearch==7.14.1
```

Is it necessary that pgsync pin the `elasticsearch` dependency? Until a stable Opensearch client is available, could pgsync allow versions of the `elasticsearch` package 7.13.4 or above?

Thank you.

**Comment by toluaina** [comment]
Oh boy! Here we go. Thanks for reporting this. Pinning the Elasticsearch client to 7.13.4

**Comment by toluaina** [comment]
Fixed in the latest release
