### ISSUE TITLE
Bulk insert rate-limiting.

### ISSUE THREAD

**Issue by voyc-jean** [toluaina/pgsync#180]
Hi,

Currently, it seems as though PGSync attempts to sync data as rapidly as possible upon the initial sync. This works well in most cases, but when indices need to be rebuilt in an environment with tight resource constraints, it tends to fall apart a bit.

On systems with limited CPU and memory, the initial sync often leads to 429 responses and timeouts from Elasticsearch. This means that when a new index is being built, even reading from the instance becomes extremely slow or even impossible.

A logical solution to this is to throw more resources at the Elasticsearch instance, but this also leads to wasting compute capacity as these resources are only needed during the initial sync once every now and then.

The current environment variables are of some help, but would it be possible to add a more advanced form of rate-limiting? Perhaps some way to control the number of requests made to the Elasticsearch server per second?

Thanks!

**Comment by toluaina** [comment]
Can you please try `ELASTICSEARCH_STREAMING_BULK` mode. This supports handling the 429 responses. 
The elasticsearch client already handles this very well and I would like to avoid duplicating the effort in pgsync.

**Comment by voyc-jean** [comment]
I managed to get things stable by tweaking the pgsync environment variables a fair amount to work with smaller AWS Opensearch servers.
