### ISSUE TITLE
AWS Secrets Manager Support (Custom Auth)

### ISSUE THREAD

**Issue by jbward1** [toluaina/pgsync#181]
PGSync version: 2.12

Postgres version: 11

Elasticsearch version: 7.10

Redis version: 6.2

Python version: 3.8

Problem Description: 
We currently use [AWS secret manager](https://docs.aws.amazon.com/secretsmanager/latest/userguide/intro.html) to store a RDS passwords. This requires a call to AWS secrets manager to retrieve a rotating password.

Proposal:
Would it be reasonable to enable an "auth plugin" to allow clients to inject their own python code to generically support different mechanisms of auth?

Error Message (if any): N/A

**Comment by toluaina** [comment]
I added support for this. You will need to create a custom Auth plugin like the one [here](https://github.com/toluaina/pgsync/blob/master/plugins/sample.py#L6) and include it in your python path. 
Let me know how this works for your needs

**Comment by toluaina** [comment]
This has been supported in the latest release.
