### ISSUE TITLE
Run specific entries in schemas.json

### ISSUE THREAD

**Issue by dg98** [toluaina/pgsync#193]
I'm trying to sync a large database and put the different tables into split schema files to be able to run them separately. Now when I want to put all of them in one schema.json, pgsync will likely want to resync all of them because the schema changed, right?
If so, could you introduce an argument that allows to run pgsync for specific entries in the schema file only?

**Comment by toluaina** [comment]
Closing as I don't think this is feasible. Feel free to re-open if you want to discuss this further.
