### ISSUE TITLE
Literals as concat transform pseudo-columns

### ISSUE THREAD

**Issue by eichmann** [toluaina/pgsync#194]
PGSync version: 2.1.6

Postgres version: 11.7

Elasticsearch version: 7.15.0

Redis version: 6.2.6

Python version: 3.9

Feature Request: 

It would be very handy in the concat transform to specify a literal as a pseudo-column:
`
	"concat": {
                    "columns": ["'http://'", "url"],
                    "destination": "full_url"
                }
`

**Comment by toluaina** [comment]
Thats a good idea. I have implemented this in the master branch

**Comment by eichmann** [comment]
Interesting side effect to this enhancement - you can now inject a literal into the document as a pseudo-column:

```
			"transform": {
				"concat": {
                    "columns": [ "instrument"],
                    "destination": "entity"
                }
			}

```
