### ISSUE TITLE
 elasticsearch.helpers.errors.BulkIndexError

### ISSUE THREAD

**Issue by AnkitKundariya** [toluaina/pgsync#201]
PGSync version: Latest

Postgres version: Latest

Elasticsearch version: Latest

Redis version: Latest

Python version: 3.8.x

Problem Description:

Currently, I'm trying to index a large database and there is some bulk index data error I'm getting.
due to the below error whole indexing process is stuck at one point can we handle the below as an exception and let other things get indexed. because stop indexing at one particular index due to below error is not good.

Error Message (if any): 

```
elasticsearch.helpers.errors.BulkIndexError: (‘2 document(s) failed to index.’, [{‘index’: {‘_index’: ‘search_index’, ‘_type’: ‘_doc’, ‘_id’: ‘5Xf’, ‘status’: 400, ‘error’: {‘type’: ‘mapper_parsing_exception’, ‘reason’: ‘object mapping for [x] tried to parse field [x] as object, but found a concrete value’}, ‘d
```

**Comment by toluaina** [comment]
Perhaps you can try the suggestion outlined [here](https://github.com/toluaina/pgsync/issues/198#issuecomment-950223155)?
I think skipping/ignoring an error during indexing might not be a preferred default behaviour.
