### ISSUE TITLE
multiple concat transforms in one node

### ISSUE THREAD

**Issue by eichmann** [toluaina/pgsync#204]
PGSync version: 2.1.8

Postgres version: 11.7

Elasticsearch version: 7.15.0

Redis version: 6.2.6

Python version: 3.9

Feature Request:

The rename transform clearly supports multiple renamings for a given node. I've not succeeded in doing the same with concat transforms. I've tried multiple transform clauses (each with a concat), multiple concat clauses in one transfer clause, pointing "concat" at an array of structs (ala rename), and repeating the concat fields in one concat. In all of these, the last one in the JSON wins, and the others are no-ops. Is this just not supported?  If not, could I suggest following the rename pattern and having concat be an array of structs, each as the current concat is defined?

**Comment by toluaina** [comment]
Thats a good suggestion. I didn't think of it.
This has been implemented in master. [Here](https://github.com/toluaina/pgsync/blob/master/examples/book/schema.json#L100-L111) is an example
It should also be backward compatible. Might need a bit of testing though.

**Comment by eichmann** [comment]
Just tested this out in 2.1.9 - looks great:

`				"concat": [
					{
						"columns": [
							"https://clinicaltrials.gov/ct2/show/",
							"nct_id"
						],
						"destination": "url"
					},
					{
						"columns": [
							"clinical trial"
						],
						"destination": "entity"
					}
				]
`

**Comment by eichmann** [comment]
Note that this is a slick way to inject a constant literal pseudo-column, as well.
