### ISSUE TITLE
KeyError on one_to_many relationship

### ISSUE THREAD

**Issue by jsonck** [toluaina/pgsync#205]
PGSync version: 2.1.8

Postgres version: 13.4

Elasticsearch version: 7.15.1

Redis version: 6.2.6

Python version: 

Problem Description: 
Getting KeyError on a has_many parent child relationship. The foreign key is set correctly in postgres. Although the exception occurs, the daemon continues to run, however no new entries are picked up by elasticsearch

Contacts have many events and events have a foreign key: "contact_id"

Schema:
```
[
    {
        "database": "postgres",
        "index": "contacts",
        "nodes": {
            "table": "contacts",
            "schema": "public",
            "columns": [
                    "id",
                    "unique_id",
                    "customer_id",
                    "first_name",
                    "last_name",
                    "email",
                    "phone",
                    "tags",
                    "accepts_marketing",
                    "created_at",
                    "updated_at"
            ],
            "children": [
                {
                    "table": "events",
                    "columns": [
                        "id",
                        "contact_id",
                        "unique_id",
                        "name",
                        "data",
                        "created_at",
                        "updated_at"
                    ],
                    "relationship": {
                        "variant": "object",
                        "type": "one_to_many"
                    }
                }
            ]
        }
    }
]
```

Error Message (if any): 

```
2021-11-07 18:19:08.110:ERROR:pgsync.sync: Exception 'contact_id'
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pgsync/sync.py", line 892, in sync
    self.es.bulk(self.index, docs)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pgsync/elastichelper.py", line 133, in bulk
    raise_on_error=raise_on_error,
  File "/home/ec2-user/.local/lib/python3.7/site-packages/elasticsearch/helpers/actions.py", line 484, in parallel_bulk
    actions, chunk_size, max_chunk_bytes, client.transport.serializer
  File "/usr/lib64/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
  File "/usr/lib64/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib64/python3.7/multiprocessing/pool.py", line 140, in _helper_reraises_exception
    raise ex
  File "/usr/lib64/python3.7/multiprocessing/pool.py", line 292, in _guarded_task_generation
    for i, x in enumerate(iterable):
  File "/home/ec2-user/.local/lib/python3.7/site-packages/elasticsearch/helpers/actions.py", line 155, in _chunk_actions
    for action, data in actions:
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pgsync/sync.py", line 698, in _payloads
    payloads,
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pgsync/sync.py", line 379, in _insert
    value = payload_data[key]
KeyError: 'contact_id'
Exception in thread Thread-6239:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pgsync/sync.py", line 921, in poll_redis
    self.on_publish(payloads)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pgsync/sync.py", line 1004, in on_publish
    self.sync(self._payloads(_payloads))
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pgsync/sync.py", line 892, in sync
    self.es.bulk(self.index, docs)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pgsync/elastichelper.py", line 133, in bulk
    raise_on_error=raise_on_error,
  File "/home/ec2-user/.local/lib/python3.7/site-packages/elasticsearch/helpers/actions.py", line 484, in parallel_bulk
    actions, chunk_size, max_chunk_bytes, client.transport.serializer
  File "/usr/lib64/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
  File "/usr/lib64/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib64/python3.7/multiprocessing/pool.py", line 140, in _helper_reraises_exception
    raise ex
  File "/usr/lib64/python3.7/multiprocessing/pool.py", line 292, in _guarded_task_generation
    for i, x in enumerate(iterable):
  File "/home/ec2-user/.local/lib/python3.7/site-packages/elasticsearch/helpers/actions.py", line 155, in _chunk_actions
    for action, data in actions:
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pgsync/sync.py", line 698, in _payloads
    payloads,
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pgsync/sync.py", line 379, in _insert
    value = payload_data[key]
KeyError: 'contact_id'


```

**Comment by toluaina** [comment]
Can you possibly provide details of your database schema please ?

**Comment by jsonck** [comment]
I've copied the schema below. We're running on RDS
`
--
-- PostgreSQL database dump
--

-- Dumped from database version 13.4
-- Dumped by pg_dump version 14.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: contacts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contacts (
    id integer NOT NULL,
    unique_id character varying,
    customer_id bigint,
    email character varying,
    tags text[] DEFAULT '{}'::text[],
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);


ALTER TABLE public.contacts OWNER TO postgres;

--
-- Name: contacts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.contacts_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.contacts_id_seq OWNER TO postgres;

--
-- Name: contacts_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.contacts_id_seq OWNED BY public.contacts.id;


--
-- Name: events; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.events (
    id bigint NOT NULL,
    unique_id character varying,
    contact_id integer,
    name character varying,
    data jsonb,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);


ALTER TABLE public.events OWNER TO postgres;

--
-- Name: events_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.events_id_seq OWNER TO postgres;

--
-- Name: events_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.events_id_seq OWNED BY public.events.id;


--
-- Name: contacts id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contacts ALTER COLUMN id SET DEFAULT nextval('public.contacts_id_seq'::regclass);


--
-- Name: events id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events ALTER COLUMN id SET DEFAULT nextval('public.events_id_seq'::regclass);


--
-- Name: contacts contacts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contacts
    ADD CONSTRAINT contacts_pkey PRIMARY KEY (id);


--
-- Name: events events_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_pkey PRIMARY KEY (id);


--
-- Name: index_contacts_on_customer_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX index_contacts_on_customer_id ON public.contacts USING btree (customer_id);


--
-- Name: index_contacts_on_email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX index_contacts_on_email ON public.contacts USING btree (email);


--
-- Name: index_contacts_on_unique_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX index_contacts_on_unique_id ON public.contacts USING btree (unique_id);


--
-- Name: index_events_on_contact_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX index_events_on_contact_id ON public.events USING btree (contact_id);


--
-- Name: index_events_on_contact_id_and_created_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX index_events_on_contact_id_and_created_at ON public.events USING btree (contact_id, created_at);


--
-- Name: index_events_on_contact_id_and_name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX index_events_on_contact_id_and_name ON public.events USING btree (contact_id, name);


--
-- Name: index_events_on_created_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX index_events_on_created_at ON public.events USING btree (created_at);


--
-- Name: index_events_on_unique_id_and_created_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX index_events_on_unique_id_and_created_at ON public.events USING btree (unique_id, created_at);


--
-- Name: index_events_on_unique_id_and_name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX index_events_on_unique_id_and_name ON public.events USING btree (unique_id, name);


--
-- Name: contacts contacts_notify; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER contacts_notify AFTER INSERT OR DELETE OR UPDATE ON public.contacts FOR EACH ROW EXECUTE FUNCTION public.table_notify();


--
-- Name: contacts contacts_truncate; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER contacts_truncate AFTER TRUNCATE ON public.contacts FOR EACH STATEMENT EXECUTE FUNCTION public.table_notify();


--
-- Name: events events_notify; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER events_notify AFTER INSERT OR DELETE OR UPDATE ON public.events FOR EACH ROW EXECUTE FUNCTION public.table_notify();


--
-- Name: events events_truncate; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER events_truncate AFTER TRUNCATE ON public.events FOR EACH STATEMENT EXECUTE FUNCTION public.table_notify();


--
-- Name: events fk_events_contacts; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT fk_events_contacts FOREIGN KEY (contact_id) REFERENCES public.contacts(id);


--
-- PostgreSQL database dump complete
--
`

**Comment by toluaina** [comment]
- My guess is that the database schema might have changed after running the initial bootstrap.
- There are some fields in your `schema.json` that are missing from the db dump above.
- One caveat of pgsync is that if you change your database structure, you might need to re-run bootstrap 

You should run:

1. `bootstrap -c /path/to/schema.json -t`
2. `bootstrap -c /path/to/schema.json`
3.  ... then run pgsync as normal

**Comment by toluaina** [comment]
Assuming this has been resolved. Feel free to re-open if it occurs again.
