### ISSUE TITLE
Feature Request: Usage of API Key of Elasticsearch

### ISSUE THREAD

**Issue by Aersoftler** [toluaina/pgsync#208]
PGSync version: 2.1.9

Elasticsearch version: 7.14.2

Elasticsearch supports the [usage of an API key](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-create-api-key.html). As far as I see, it is only possible to use [the username and password](https://pgsync.com/env-vars/) so that PGSync can connect to Elasticsearch.

Did I miss something or is it not possible to use an API key of Elasticearch? If not, it would be great, if it were possible.

**Comment by toluaina** [comment]
I added support for this in master. You will need to define [these](https://github.com/toluaina/pgsync/blob/master/pgsync/settings.py#L86-L87) two variables. Can you try it out and let me know

**Comment by toluaina** [comment]
This has been released in 2.1.10
