### ISSUE TITLE
Error in bootstrap (no schema has been selected) 

### ISSUE THREAD

**Issue by kaggrwal** [toluaina/pgsync#209]
I'm getting below error while bootstrapping

`Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1800, in _execute_context cursor, statement, parameters, context File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute cursor.execute(statement, parameters) psycopg2.errors.InvalidSchemaName: no schema has been selected to create in` 

I have defined the below schema 

```
[
    {
        "database": "rlm",
        "index": "logicalresources_2",
        "nodes": {
            "table": "ip_resource",
            "schema": "ip",
            "columns": [
                
            ],
            "children": [
                {
                    "table": "resource_relationship",
                    "schema": "ip",
                    "columns": [
                        
                    ],
                    "transform": {
                        "mapping": {
                            "created_date": {
                                "type": "date"
                            },
                            "update_date": {
                                "type": "date"
                            }
                        }
                    },
                    "relationship": {
                        "variant": "object",
                        "type": "one_to_many",
                        "foreign_key": {
                            "child": [
                                "source_resource_instance_id"
                            ],
                            "parent": [
                                "resource_instance_id"
                            ]
                        }
                    }
                },
                {
                    "table": "resource_characteristics",
                    "schema": "ip",
                    "columns": [
                        
                    ],
                    "transform": {
                        "mapping": {
                            "created_date": {
                                "type": "date"
                            },
                            "update_date": {
                                "type": "date"
                            }
                        }
                    },
                    "relationship": {
                        "variant": "object",
                        "type": "one_to_many"
                    }
                }
            ],
            "transform": {
                "mapping": {
                    "created_date": {
                        "type": "date"
                    },
                    "update_date": {
                        "type": "date"
                    },
                    "ip_from_hash": {
                        "type": "keyword"
                    },
                    "ip_to_hash": {
                        "type": "keyword"
                    },
                    "number_of_items": {
                        "type": "keyword"
                    },
                    "number_of_free_items": {
                        "type": "keyword"
                    }
                }
            }
        }
    }
]
```

I also tried to print the schema, and it has been printed fine. 

`schema: ip
2021-11-18 12:41:06.290:ERROR:pgsync.base: Exception (psycopg2.errors.InvalidSchemaName) no schema has been selected to create in
`

But it shows no schema has been selected, am I missing any configuration here?

**Comment by toluaina** [comment]
OK thanks for that. 
Can you please 
- provide the full traceback?
- does the current user have permission to create a view in the public schema
  - i.e connect to the db and run:
  - `CREATE MATERIALIZED VIEW someview AS SELECT 'Hi there';`
  - `SELECT * from someview;`

**Comment by kaggrwal** [comment]
Hi,

I checked for schema 'ip', which I have given in schema.json.

I got permission denied error

`ERROR:  permission denied for schema ip
`

Is this the reason, if yes, please tell me what all rights are required for the DB user as I will request all the rights from my infra team. 
and kindly help here ASAP, as we are stuck with migration/sync.

Thanks a lot

**Comment by toluaina** [comment]
You will need to full access to the database since bootstrap creates replication slot and triggers.
There is a reference [here](https://tableplus.com/blog/2018/04/postgresql-how-to-grant-access-to-users.html) 
You would probably need 1. 4 and 5.

**Comment by kaggrwal** [comment]
I tried giving all grants in that schema.
But still I'm getting the same error. 
I'm attaching the full stacktrace [
[stacktrace.txt](https://github.com/toluaina/pgsync/files/7608351/stacktrace.txt)
](URL)

Please guide here.

**Comment by kaggrwal** [comment]
This is resolved via search-path in postgresdb.
