### ISSUE TITLE
How i can set custom meta fields?

### ISSUE THREAD

**Issue by WebSofter** [toluaina/pgsync#210]
For example i want change field type or set own attr, but it is not any effect for change. I from [How i can change _type param in during import data into elasticsearch?](https://stackoverflow.com/questions/70143986/how-i-can-change-type-param-in-during-import-data-into-elasticsearchl)

```json
[
  {
    "database": "yii2advanced",
    "index": "sapfir",
    "type": "news",
    "source": {
      "meta": {
        "type": "news"
      }
    },
    "nodes": {
      "table": "news",
      "schema": "yii2advanced",
      "columns": []
    }
  },
...
]
```

**Comment by toluaina** [comment]
The SO suggestion is correct. `_type`  is pending deprecation. I don't think you can inject arbitrary metadata with pgsync.

**Comment by toluaina** [comment]
closing as this has been answered
