### ISSUE TITLE
Django ORM Support

### ISSUE THREAD

**Issue by blackPanther39** [toluaina/pgsync#218]
Does pgsync have support for Django ORM?

**Comment by toluaina** [comment]
pgsync's operation is not tied to any framework as such. is there any particular feature you need from Django?

**Comment by voyc-jean** [comment]
An issue that we had with Django is the lack of support for certain field types. For example, Django supports the `interval` Postgres datatype through `DurationField`. Elasticsearch, however, has no such type. The same goes for `TimeField`, `TimeField` etc.

In our case, we set the mapping to an integer field in the pgsync schema and used a pgsync plugin to convert the `interval` field to an integer.

**Comment by toluaina** [comment]
I think it's a good idea to delegate this to the plugin as that is what it is intended for.

**Comment by blackPanther39** [comment]
Thanks for the quick response. It worked now, initially thought it is based on a framework.  Closing this issue. 

I am not using DurationField for now. 

Thanks again for this very smart and nice plugin
