### ISSUE TITLE
Handling separate db roles

### ISSUE THREAD

**Issue by zacherkkila** [toluaina/pgsync#223]
PGSync version: 2.1.9

Postgres version: 13.x

Elasticsearch version: 7.16.2

Problem Description: 

I have multiple roles in my database. The sync and everything works perfect, however, when I try to insert data into postgres using one of the roles the trigger is giving me the permission error below

`Error: permission denied for materialized view _view`

And I have to manually grant select on the view with the command below

`grant select on _view to <my_role>`

Can you help me understand when this view is created, and what needs to happen to allow this configuration? Worried about users not being able to create data on any restart

**Comment by toluaina** [comment]
- The materialized view is created once when you run bootstrap.
- It stores the primary and foreign keys for each table
- This was done as an optimization strategy.
- Previously we calculated this on the fly. 
- Yes, that view is only created when you run bootstrap
- running bootstrap will not destroy anything. (in fact, it was designed to be re-run as many times as you like)
- it might however be suboptimal if you have large database objects as it needs to list and check these 
- The role needs to be able to create, drop and select from the `_view`
- Thank you!

**Comment by zacherkkila** [comment]
Awesome, thanks for the fast response!
