### ISSUE TITLE
Add option to suppress sync/status logs

### ISSUE THREAD

**Issue by zacherkkila** [toluaina/pgsync#225]
PGSync version: 2.1.10

Postgres version: 13

Problem Description: 

Can we add an option to suppress logs (or is there one already)? I can take a crack at a PR if you want to let me know what you would want.. Maybe just an environment variable or even a command line arg?

https://github.com/toluaina/pgsync/blob/a0bfdd98dcf2e00a72a31ee526d5337f2672e850/pgsync/sync.py#L998

These are good for debugging in many scenarios but in production they are pretty excessive

**Comment by zacherkkila** [comment]
<img width="784" alt="image" src="https://user-images.githubusercontent.com/14079163/148868695-878defb2-f487-432f-8698-a9674a474c79.png">

Also getting a lot of repeating logs in 2.1.10

**Comment by zacherkkila** [comment]
Thinking more on this, I think it would be nice to be able to set a `DEBUG_LOG_INTERVAL` and just set it to 0 or something to turn them off all together. I think they would be nice for us on a 10-30s interval but right now it is going so fast it is hard to figure out what is going on (ex. once I looked more at the screenshot above I am realized it is showing all of our indexes which is cool.. but it was zipping so fast with that many indexes I couldn't really easily debug what was going on).. Again, I am sure this isn't super high priority for you so happy to take a look at it if you are interested

**Comment by toluaina** [comment]
I think it would be good to have some sort of logging to let you know something is happening. 
We could also add a `--quiet` mode to turn of the logging altogether
I like the DEBUG_LOG_INTERVAL option as it allow you to control the frequency

**Comment by toluaina** [comment]
Turned out to be straightforward.
Added `LOG_INTERVAL` as an environment variable to control this.
This is currently in master branch

**Comment by zacherkkila** [comment]
Awesome! Thank you!
