### ISSUE TITLE
DELETE Operations are not synced on elastic

### ISSUE THREAD

**Issue by kaggrwal** [toluaina/pgsync#226]
PGSync version:  latest (installed from PIP)

Postgres version:  14.1 

Elasticsearch version:  6.8.6

Redis version:  5.0.8

Python version:  3.7

Problem Description:   When manually deleting from sql query, deleted rows are not synced to Elastic. 

Error Message (if any):  Nothing is in logs.

**Comment by kaggrwal** [comment]
@toluaina, the initial sync was successful and all other operations are also getting synced but when a delete operation is executed, nothing is captured/incremented in [db] as well as [redis].

**Comment by toluaina** [comment]
Can you provide more details. This appears to work ok. 
did you bootstrap successfully ? 
has the schema.json or database structure changed since the initial bootstrap. 
additionally, can you enable verbose logging and provide the output when you delete a record?

**Comment by kaggrwal** [comment]
checked and found something, If anytime elastic application is going down. pgsync stop syncing to elastic. Pending count in redis keeps increasing. 
I have attached the logs for the same.

[Pgsync_logs.txt](https://github.com/toluaina/pgsync/files/7882170/Pgsync_logs.txt)

**Comment by toluaina** [comment]
Thanks for this.
So it looks like there was an earlier error.
It also looks like there was a red timeout error.
You need to increse the env var `ELASTICSEARCH_TIMEOUT` as described [here](https://pgsync.com/env-vars/) 
pgsync should not really continue if theere is an unrecoverble error. 
I will improve this at some point. 
For now please increase `ELASTICSEARCH_TIMEOUT`

**Comment by niraj-ads** [comment]
Encountered the same issue! @toluaina thanks for the feedback! But there are deleted documents that can still be found in elastic due to the failure of the elastic application. Do you have a solution on how to resolve that?

**Comment by kaggrwal** [comment]
Closing this for right now will increase the elastic timeout
