### ISSUE TITLE
schema transformation is not picked at first time deployment

### ISSUE THREAD

**Issue by Eklavaya** [toluaina/pgsync#228]
PGSync version: latest (installed from PIP)

Postgres version: 14.1

Elasticsearch version: 6.8.6

Redis version: 5.0.8

Python version: 3.7

Problem Description: when I deploy pgsync on first time on k8 then it picks schema but provided transformation is not picked.. but when  follow below steps it picks transformation as well :

1. delete schema from elastic
2. delete pod (new pod respawn)
3. schema recreated by pgsync with correct transformation

schema transformation: 

`"transform": {
         "mapping": {
            "created_date": {
               "type": "date"
            },
            "update_date": {
               "type": "date"
            },
            "column1": {
               "type": "keyword"
            },
            "column2": {
               "type": "keyword"
            }
         }`

instead of `keyword`  type it picks long
date transformation is correct.

Error Message (if any): 

```


```

**Comment by toluaina** [comment]
Maybe its worth running this outside of k8 first to get a better understanding of what is going on.
Also can you provide the full schema.json to see if this is correct?

**Comment by Eklavaya** [comment]
outside the k8 working fine.
