### ISSUE TITLE
restrict pgsync to listen from specific schema instead of database

### ISSUE THREAD

**Issue by Eklavaya** [toluaina/pgsync#229]
PGSync version: latest (installed from PIP)

Postgres version: 14.1

Elasticsearch version: 6.8.6

Redis version: 5.0.8

Python version: 3.7

Problem Description: Here i am able to see if there any other schema also have trigger notify function, then pgsync listens those events as well. as it is not impacting anything as I have not configured any schema for them to push in elastic.. but it still listens.

Can we restricts it to listen from specific schema.

Error Message (if any): 

```


```

**Comment by toluaina** [comment]
You can already specify the `schema` in schema.json 
[Here](https://github.com/toluaina/pgsync/blob/master/examples/airline/schema.json#L7) is an example

**Comment by toluaina** [comment]
closing this for now
