### ISSUE TITLE
Handling type conflicts in user inputted JSON without a known structure

### ISSUE THREAD

**Issue by zacherkkila** [toluaina/pgsync#237]
PGSync version: Latest (building from master)

Problem Description: 

I am looking to sync user created json but often the same field names have different types and it is causing the Elastic json parser to fail

`Current token (VALUE_NUMBER_INT) not of boolean type`

I think that we ideally would be able to just sync the JSON key values as one delimited string and search based on that (something like the below)

Ex: `phValue:7.4 volume:30 name:Container1`

But, since I don't know how we would handle that pre-processing, (custom plugin maybe??) just storing the entire JSON object as text would be sufficient

I tried using a transform but it seems to still try to parse it as JSON

```
"columns": [
    "id",
    "created_at",
    "user_json_input"
],
"transform": {
   "mapping" : {
     "user_json_input": {
            "type": "text"
       }
   }
}
```

Any insight into how to handle this case would be awesome. Thank you very much!!

Error Message (if any): 

`Current token (VALUE_NUMBER_INT) not of boolean type`

**Comment by toluaina** [comment]
There is a very simple setting for this. 
Can you add this to your schema.json.

There is an example setting in the [book](https://github.com/toluaina/pgsync/blob/master/examples/book/schema.json#L10) sample
```
"setting": {
    "mapping.ignore_malformed": true,
    ...
}
```

**Comment by zacherkkila** [comment]
Super cool! Thank you!!
