### ISSUE TITLE
WARNING ModuleNotFoundError: No module named 'plugins'

### ISSUE THREAD

**Issue by kz-fincert** [toluaina/pgsync#242]
PGSync version:
2.1.11 

Postgres version: 
PostgreSQL 13.5 (Debian 13.5-1.pgdg110+1)

Elasticsearch version: 
7.16.3

Python version: 
3.10

Problem Description: 

When PGSync starts, the following warnings are issued
```
2022-02-08 13:47:43.165:WARNING:pgsync.urls: ModuleNotFoundError: No module named 'plugins'
2022-02-08 13:47:43.170:WARNING:pgsync.urls: ModuleNotFoundError: No module named 'plugins'
2022-02-08 13:47:43.176:WARNING:pgsync.urls: ModuleNotFoundError: No module named 'plugins'
```

PGSync run in docker with Dockerfile:
```
ARG PGSYNC_PYTHON_VERSION
FROM python:${PGSYNC_PYTHON_VERSION}
RUN apt-get update \
    && apt-get install -y gcc libpq-dev \
    && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir --upgrade pip pgsync
WORKDIR /usr/local/pgsync
ENTRYPOINT ["pgsync", "--config", "/usr/local/pgsync/schema.json", "--daemon"]
```

**Comment by kz-fincert** [comment]
Updated PGSync, warnings remained, another problem appeared. Now _view is not created and an error is received when trying to write to the database
```
Database Exception – yii\db\Exception
SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "public._view" does not exist
LINE 2: ... FROM public._vi...
^
QUERY: SELECT primary_keys, foreign_keys
FROM public._view
WHERE table_name = TG_TABLE_NAME
CONTEXT: PL/pgSQL function table_notify() line 32 at SQL statement
```

**Comment by toluaina** [comment]
The changes is in master and has not been published. 
The database user needs to have permissions to write to the database  and to create views. 
Changing the user privilege mid way is likely the cause of this.
The pg sync user needs elevated db privileges to work correctly.

**Comment by toluaina** [comment]
Hopefully this had been resolved, Feel free to reopen otherwise
