### ISSUE TITLE
Support for Postgres' built-in datetime values (infinity, -infinity)

### ISSUE THREAD

**Issue by hasancemreok** [toluaina/pgsync#247]
PGSync version: 2.1.12
Postgres version: 11.9
Elasticsearch version: 7.9
Redis version: -
Python version: -

Problem Description: 
Postgres has two types of datetime values (`infinity`, `-infinity`). Those data types seems not supported and getting parser exceptions because of that and sync process broken when this issue happened.

Error Message (if any): 
```
'error': {'type': 'mapper_parsing_exception', 'reason': "failed to parse field [createdAt] of type [date] in document with id '068172c1-2705-4828-8d0e-89149d34e6ef'. Preview of field's value: '-infinity'", 'caused_by': {'type': 'illegal_argument_exception', 'reason': 'failed to parse date field [-infinity] with format [strict_date_optional_time||epoch_millis]', 'caused_by': {'type': 'date_time_parse_exception', 'reason': 'date_time_parse_exception: Failed to parse with all enclosed parsers'}}}
```

**Comment by toluaina** [comment]
I think this is an Elasticsearch exception as the original field was already mapped to datetime.
Do you have a more complete example? 
It would be useful to know what your mapping looks like at the time your were trying to index infinity value

**Comment by hasancemreok** [comment]
Hi @toluaina, thank you for your response.

You're right this is an Elasticsearch exception and original field mapped to datetime by Pgsync.

We have some date columns in Postgres and those can have `infinity / -infinity` values. **infinity** meaning **later than all time stamps**. **-infinity** meaning **earliear than all time stamps** in Postgres. Basically those are can be formatted like `9999-12-31 23:59:59` and `0000-01-01 00:00:00`
(for more info: https://www.postgresql.org/docs/9.0/datatype-datetime.html#DATATYPE-DATETIME-SPECIAL-TABLE)

As official PG document says, `infinity` is a date/timestamp value but this is a text for ElasticSearch. This is why that error occurring. So Pgsync need to format like `YYYY-MM-DD HH:mm:ss` this type data before sending it to Elasticsearch.


Here is an example data from our Postgres:

<img src="https://user-images.githubusercontent.com/7186718/154264537-abdcb9d0-2ae5-45f7-b255-20310638b812.jpg" width=50% height=50%>

And that data causing error when syncing to ElasticSearch, trace in below:
`'error': {'type': 'mapper_parsing_exception', 'reason': "failed to parse field [createdAt] of type [date] in document with id '039eeb13-403d-4d06-96c5-1ff8e54dcb91'. Preview of field's value: '-infinity'", 'caused_by': {'type': 'illegal_argument_exception', 'reason': 'failed to parse date field [-infinity] with format [strict_date_optional_time||epoch_millis]', 'caused_by': {'type': 'date_time_parse_exception', 'reason': 'date_time_parse_exception: Failed to parse with all enclosed parsers'}}}`


If this information not enough for you, please ping me whenever you want here.

**Comment by toluaina** [comment]
There is no easy way to support this out of the box.
The easiest way would be to add a plugin to transform the infinity type.
I have added an example in the repo [here](https://github.com/toluaina/pgsync/blob/master/plugins/infinity.py)

Adding a plugin is easy and documented [here](https://pgsync.com/tutorial/plugins/)

**Comment by hasancemreok** [comment]
Thank you for response @toluaina 

I'll try to figure out this with a plugin. Other than that; I've found `replace` block in example schemas in repo, but it's not documented.

Could that be an alternative solution for this issue? Example in below.
```
"replace": {
      "CreatedAt": {
          "infinity": "9999-12-31 23:59:59"
      }
 }
```

**Comment by hasancemreok** [comment]
Thank you for response @toluaina 

We're using pgsync as containerized service.

- I've adopted that plugin into our structure and put that into plugins folder.
- added it to schema
- PYTHONPATH set with command below :
```
ADD ./plugins /plugins
RUN export PYTHONPATH="$PYTHONPATH:/plugins"
```

After this steps, we're getting exception below. I've seen same issues in other Github issues and you've marked it as solved but we're still getting that. Probably I couldn't set `PYTHONPATH` correct. P.S  Pgsync version 2.1.11

```
Traceback (most recent call last):
  File "/usr/local/bin/pgsync", line 7, in <module>
    sync.main()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 1231, in main
    sync = Sync(document, verbose=verbose, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 100, in __init__
    self.validate(repl_slots=repl_slots)
  File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 118, in validate
    self._plugins: Plugins = Plugins("plugins", self.plugins)
  File "/usr/local/lib/python3.7/site-packages/pgsync/plugin.py", line 26, in __init__
    self.reload()
  File "/usr/local/lib/python3.7/site-packages/pgsync/plugin.py", line 33, in reload
    self.walk(self.package)
  File "/usr/local/lib/python3.7/site-packages/pgsync/plugin.py", line 37, in walk
    plugins = import_module(package)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
```

**Comment by toluaina** [comment]
This will not work as expected as the changes are in the repo and not published yet. 
I will publish version 2.1.12 with these changes for you shortly.

**Comment by hasancemreok** [comment]
Thank you @toluaina, looking forward to work with 2.1.12

**Comment by toluaina** [comment]
This has been published in the latest version. Closing

**Comment by phsophea101** [comment]
I already made like this:

```
# echo $PYTHONPATH
/plugins
# ls
documents  plugins  runserver.sh  wait-for-it.sh
# cd plugins
# ls
__init__.py  activestatusplugin.py
```
but still got error:

```
pgsync-1         | Traceback (most recent call last):
pgsync-1         |   File "/usr/local/bin/bootstrap", line 70, in <module>
pgsync-1         |     main()
pgsync-1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
pgsync-1         |     return self.main(*args, **kwargs)
pgsync-1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1053, in main
pgsync-1         |     rv = self.invoke(ctx)
pgsync-1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
pgsync-1         |     return ctx.invoke(self.callback, **ctx.params)
pgsync-1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 754, in invoke
pgsync-1         |     return __callback(*args, **kwargs)
pgsync-1         |   File "/usr/local/bin/bootstrap", line 60, in main
pgsync-1         |     document, verbose=verbose, repl_slots=False, **kwargs
pgsync-1         |   File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 94, in __init__
pgsync-1         |     self.validate(repl_slots=repl_slots)
pgsync-1         |   File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 175, in validate
pgsync-1         |     root: Node = self.tree.build(self.nodes)
pgsync-1         |   File "/usr/local/lib/python3.7/site-packages/pgsync/node.py", line 251, in build
pgsync-1         |     raise NodeAttributeError(f"Unknown node attribute(s): {attrs}")
pgsync-1         | pgsync.exc.NodeAttributeError: "Unknown node attribute(s): {'plugins'}"
pgsync-1         |  0:00:00.038423 (0.04 sec)
pgsync-1         | Traceback (most recent call last):
pgsync-1         |   File "/usr/local/bin/pgsync", line 7, in <module>
pgsync-1         |     sync.main()
pgsync-1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
pgsync-1         |     return self.main(*args, **kwargs)
pgsync-1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1053, in main
pgsync-1         |     rv = self.invoke(ctx)
pgsync-1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
pgsync-1         |     return ctx.invoke(self.callback, **ctx.params)
pgsync-1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 754, in invoke
pgsync-1         |     return __callback(*args, **kwargs)
pgsync-1         |   File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 1248, in main
pgsync-1         |     sync: Sync = Sync(document, verbose=verbose, **kwargs)
pgsync-1         |   File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 94, in __init__
pgsync-1         |     self.validate(repl_slots=repl_slots)
pgsync-1         |   File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 175, in validate
pgsync-1         |     root: Node = self.tree.build(self.nodes)
pgsync-1         |   File "/usr/local/lib/python3.7/site-packages/pgsync/node.py", line 251, in build
pgsync-1         |     raise NodeAttributeError(f"Unknown node attribute(s): {attrs}")
pgsync-1         | pgsync.exc.NodeAttributeError: "Unknown node attribute(s): {'plugins'}"
```

please help
