### ISSUE TITLE
Custom Queries

### ISSUE THREAD

**Issue by goktugbati** [toluaina/pgsync#252]
I have a table that has an unusual parent-child relationship and I need pgsync to generate a query like the one below.  I couldn't do it using Schema and Plugin features. Is there a way to force pgsync to generate a query like this? 

Many thanks

`SELECT n1.id,
       n1.name,
       array_agg(n2.name) as category,
from node n1
         left join space s on n1.space_id = s.id
         left join node n2 on n2.space_id = s.id
where n1.type = 'FORM'
  and n2.state in (0, 1)
  and n2."left" <= n1."left"
  and n2."right" >= n1."right"
group by n1.id
`

**Comment by toluaina** [comment]
This query is quite specific.
The Plugin gives you greater flexibility and control over what you sync to Elasticsearch.
So you can implement this type of logic in a custom plugin.

[Here](https://github.com/toluaina/pgsync/blob/master/plugins/sample.py#L24-L42) is an example and [documentation](https://pgsync.com/tutorial/plugins/)

Here is a sample plugin

```
class MyFilterPlugin(plugin.Plugin):
    """Example Filter plugin."""

    name: str = "Filter"

    def transform(self, doc: dict, **kwargs) -> dict:
        """Demonstrates how to perform a filter."""
        doc_id = kwargs["_id"]
        doc_index = kwargs["_index"]
        if doc["id"] == 1:
            return None

        return doc
```

**Comment by goktugbati** [comment]
Hi thanks a lot but unfortunately I couldn't do it. I have to iterate over all the documents to find the matching document with the current document is it something I can do using plugins ?

**Comment by goktugbati** [comment]
Hi thanks a lot but unfortunately I couldn't do it. I have to iterate over all the documents to find the matching document with the current document is it something I can do using plugins ? I tried using the schema below so that I could iterate over the all the nodes based on their space id's using a plugin but elastic search shuts down when I use this schema.

``
[
  {
    "database": "tic",
    "index": "nodes",
    "plugin": [
      "CategoryPlugin"
    ],
    "nodes": {
      "table": "node",
      "label": "form",
      "columns": [
        "id",
        "name",
        "type",
        "description",
        "space_id"
      ],
      "transform": {
        "mapping": {
          "id": {
            "type": "integer"
          },
          "name": {
            "type": "text"
          },
          "type": {
            "type": "text"
          },
          "description": {
            "type": "text"
          },
          "space_id": {
            "type": "integer"
          }
        }
      },
      "children": [
        {
          "table": "tag",
          "label": "tags",
          "columns": [
            "name"
          ],
          "relationship": {
            "type": "one_to_many",
            "variant": "object",
            "through_tables": [
              "tag_node"
            ]
          }
        },
        {
          "table": "space",
          "columns": [
            "id",
            "alias"
          ],
          "relationship": {
            "type": "one_to_one",
            "variant": "object"
          },
          "children": [
            {
              "table": "node",
              "label": "categories",
              "columns": [
                "name",
                "left",
                "right"
              ],
              "relationship": {
                "type": "one_to_many",
                "variant": "object"
              }
            }
          ]
        }
      ]
    }
  }
]
