### ISSUE TITLE
PGsync changes show up on Redis, but are not reflected on Elasticsearch

### ISSUE THREAD

**Issue by MartinSchere** [toluaina/pgsync#254]
Hi @toluaina! First of all, thanks a lot for this amazing library. We are using it on our marketplace (jpg.store) and we have sponsored you because it saved us from doing a lot of manual work. 

We are having issues with the setup tho, where after the initial sync we are not seeing any real-time updates. They get pushed to Redis, but they don't reach Elasticsearch.

Since it may be very specific, I was thinking we could solve this in a pair programming session. Do you have any contact that I can reach out to you on?

**Comment by toluaina** [comment]
Hello Martin,

I am glad to know you are using PGSync and thank you for
your sponsorship and support. 

Certainly, you can reach me at `toluaina at hotmail dot com`

--Tolu

**Comment by MartinSchere** [comment]
@toluaina Just emailed you
