### ISSUE TITLE
Feature Request: Log Elasticsearch Bulk Exceptions Instead of Raising or Ignoring

### ISSUE THREAD

**Issue by rjdlee** [toluaina/pgsync#260]
pgsync supports `ELASTICSEARCH_RAISE_ON_EXCEPTION` and `ELASTICSEARCH_RAISE_ON_ERROR`. These can both be set to False so it doesn't crash while syncing. I was having issues syncing because Elasticsearch was raising on exception/error so I set these to False. However, I would like visibility into when there are errors. 

What if we actually let Elasticsearch raise on exceptions and errors, but wrap the contents of the `_bulk` function in a try/except and re-raise the exception or errors if `ELASTICSEARCH_RAISE_ON_EXCEPTION` or `ELASTICSEARCH_RAISE_ON_ERROR` are True. If they are not False, we will log in the except rather than re-raising.

https://github.com/toluaina/pgsync/blob/master/pgsync/elastichelper.py#L164

**Comment by toluaina** [comment]
Thats a good idea. I will look into this shortly

**Comment by toluaina** [comment]
this is now on master branch. closing this for now. will publish a new version soon once a few outstanding items have been resolved
