### ISSUE TITLE
Changing variant from scalar to object doesn't update results

### ISSUE THREAD

**Issue by niraj-ads** [toluaina/pgsync#265]
PGSync version: 2.2.1

Postgres version: 14 or 12

Elasticsearch version: 7.10.2 ( aws opensearch 1.1)

Redis version: 6.2.6

Python version: 3.7.12

Problem Description: 
When data is already syncing and you change the variant from `scalar` to `object`, re-run bootstrap and resync! the results stays the same.

Error Message (if any): 

```
No errors!

```

**Comment by toluaina** [comment]
Hi @niraj-ads 

You should re-index when either:

- The structure of pgsync's schema.json
- Your database schema changes (e.g adding/removing or altering a table definition)

Re-indexing involves re-creating the Elasticsearch index which is described [here](https://pgsync.com/advanced/re-indexing/)

**Comment by niraj-ads** [comment]
@toluaina, do you have an alternative way rather than deleting the elasticsearch index?

**Comment by toluaina** [comment]
Sorry about the delay. This is more of an Elasticsearch behaviour so you can't change the type of an existing field from list to dict.
This is explained [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html#updating-field-mappings)
