### ISSUE TITLE
JSONB arrays are sorted when using a rename transform

### ISSUE THREAD

**Issue by kingkupps** [toluaina/pgsync#266]
PGSync version: 2.2.1

Postgres version: 12.5

Elasticsearch version: Opensearch 1.2.4

Redis version: 6.0.10

Python version: 3.10

Problem Description: JSONB columns containing lists cannot be renamed without being sorted.

Steps to reproduce:

Schema:
```
[
  {
    "database": "mydb",
    "index": "myindex",
    "nodes": {
      "table": "mytable",
      "schema": "public",
      "columns": ["id", "array"],
      "transform": {
        "rename": {
          "array": "renamed_array"
        }
      }
    }
  }
]
```

Postgres Table
```
CREATE TABLE mytable (
    id SERIAL PRIMARY KEY,
    array JSONB NOT NULL
);
```

Some example rows
```
INSERT INTO mytable (array) VALUES ('[3, 2, 1]'), ('[19, 12, 13]');
```

Once those rows are synced with elastic you will see the array values have been sorted and do not match those in postgres.

This was very surprising behavior and took a while to debug. If sorting can't be removed, it should at least be called out in the documentation.

**Comment by toluaina** [comment]
Sorry about this. 

I can remove the sorting. I can see why this is not desirable as its modifying the result.
I will change this to **not sort**

PS: We also sort the output from Elasticsearch to make the tests more predictable. 
Is this an issue for you as well?

**Comment by kingkupps** [comment]
No problem! I appreciate you getting back to me.

I think it's completely reasonable for test code to sort output after it is retrieved from Elasticsearch. As long as it has no impact on the production behavior.

**Comment by kingkupps** [comment]
To be clear I mean that PGSync should not sort or mutate data in any way from postgres when using the `rename` transform. I don't care what happens in test code.

**Comment by toluaina** [comment]
PGSync no longer sorts the data returned from the db. 
This was originally done in **transform**
