### ISSUE TITLE
Checkpoint advances despite sync failure.

### ISSUE THREAD

**Issue by voyc-jean** [toluaina/pgsync#268]
PGSync version: 2.1.11
Postgres version: 12.7
Elasticsearch version: 7.10
Redis version: 5.0.6
Python version: 3.8.7
Problem Description:

In #267 I describe that PGSync crashes when resumed due to the database running out of disk space.

A side effect of this issue is that PGSync appears to advance the xid stored in the local dotfile despite the fact that the pgsync process crashed.

This leads to large chunks of data being missing.

I believe the issue lies here: https://github.com/toluaina/pgsync/blob/375dc455f7f99e5342a3aa9b9e226ac2a05cb9ca/pgsync/sync.py#L1074

The `self.checkpoint` attribute is set before the `self.logical_slot_changes` method runs. 

Therefor, if ` self.logical_slot_changes` fails for whatever reason, the checkpoint will have advanced before all changes have synced.

**Comment by toluaina** [comment]
Thanks for bringing this up and organizing the issues very clearly. You are right I have moved setting the checkpoint after the query

**Comment by toluaina** [comment]
closing as this has been resolved to manage the number of open issues
