### ISSUE TITLE
Feature Request: Support indexing multiple documents from a single postgres row

### ISSUE THREAD

**Issue by kingkupps** [toluaina/pgsync#270]
PGSync version: 2.2.1

Postgres version: 12.5

Elasticsearch version: Opensearch 1.2.4

Redis version: 6.0.10

Python version: 3.10

Problem Description:
Given some schema with children like:
```
[
  {
    "database": "mydb",
    "index": "myindex",
    "nodes": {
      "table": "parent",
      "schema": "public",
      "columns": ["id", "time"],
      "children": [
        {
          "table": "child",
          "schema": "public",
          "columns": ["id", "content"],
          "transform": {
            "rename": {
              "id": "child_id"
            }
          },
          "relationship": {
            "variant": "object",
            "type": "one_to_many"
          }
        }
      ]
    }
  }
]

```
Instead of a single document per row of `parent` like this:
```
{
    "id": "ID",
    "time": "2022-02-22",
    "child": [
        {
            "child_id": 1,
            "content": "first" 
        },
        {
            "child_id": 2,
            "content": "second" 
        },
        {
            "child_id": 3,
            "content": "third" 
        }
    ]
}
```
I'd like many documents (one per each row of `child`) like this:
```
[
    {
        "parent_id": "ID",
        "time": "2022-02-22",
        "id": 1,
        "content": "first"
    },
    {
        "parent_id": "ID",
        "time": "2022-02-22",
        "id": 2,
        "content": "second"
    },
    {
        "parent_id": "ID",
        "time": "2022-02-22",
        "id": 3,
        "content": "third"
    }
]
```

Proposal:
Can I add a method to `Plugin` that subclasses could optionally override to generate several documents from one?

**Comment by kingkupps** [comment]
I have a branch with work-in-progress changes to support this but don't have permission to push the branch.

**Comment by rjdlee** [comment]
@kingkupps You can create a fork and create a PR from that fork for @toluaina to review

**Comment by toluaina** [comment]
@kingkupps Yes feel free to create a PR. Can I get a better understanding how how the pluging would work.
are you trying to return multiple docs from a single doc?

I'm trying to understand the use case. Perhaps this is a limitation that can be adressed at the core level

**Comment by kingkupps** [comment]
Here is a draft implementation of the plugin support I'm talking about. https://github.com/toluaina/pgsync/pull/271

The specific use case I'd want something like this for is to have more control over how [k-NN indexed documents](https://opensearch.org/docs/latest/search-plugins/knn/index/) are scored. Today, if I use the above schema and the `child` documents have a k-NN vector, scoring is done at the parent and considers all children as part of the score. I would much rather score each child individually and determine in my application how to do grouping.

More generally, the use case would be to denormalize documents that contain nested relationships as a result of the Postgres structure.

**Comment by kingkupps** [comment]
Any thoughts here?

**Comment by kingkupps** [comment]
@toluaina Any thoughts here?

**Comment by kingkupps** [comment]
Turns out you can get what I'm looking for by manually specifying foreign keys. Ignore this

**Comment by niklhut** [comment]
@kingkupps I'm trying to achieve the same results. Would you mind to elaborate how exactly you did that?
