### ISSUE TITLE
Is there a way to define dynamic templates in the schema?

### ISSUE THREAD

**Issue by valearna** [toluaina/pgsync#272]
I'd like to add dynamic templates to my index mappings, as described in the elasticsearch official guide: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/dynamic-templates.html

Is there a way to define overall mappings properties in the pgsync schema?

**Comment by valearna** [comment]
I tried setting the "mapping" field in the schema as follows:

"mapping": {
    "dynamic_templates": [
      {
        "integers": {
          "match_mapping_type": "long",
          "mapping": {
            "type": "integer"
          }
        }
      },
      {
        "strings": {
          "match_mapping_type": "string",
          "mapping": {
            "type": "text",
            "fields": {
              "raw": {
                "type":  "keyword",
                "ignore_above": 256
              }
            }
          }
        }
      }
    ]
  }

but got this error: 

elasticsearch.exceptions.RequestError: RequestError(400, 'mapper_parsing_exception', 'Expected map for property [fields] on field [dynamic_templates] but got a class java.lang.String')

**Comment by toluaina** [comment]
this should be working now in the master branch.
