### ISSUE TITLE
Is there a way to sync Postgresql Views with Elasticsearch?

### ISSUE THREAD

**Issue by vijeandran** [toluaina/pgsync#275]
PGSync version: 2.2.1

Postgres version: 13.6

Elasticsearch version: 8.1.0

Redis version: 5.0.7

Python version: 3.8.3

Problem Description: 
I have created an index in Elasticsearch for Postgresql Views. Whenever I do changes in the Postgres View table, the same changes have to happen in the Elasticsearch index. I tried running the command pgsync with schema.json and got the below error.
Is there a way to sync Postgresql Views with Elasticsearch? Because this is my requirement.

Error Message (if any): 

```
$ pgsync --config /home/vijee/Elastic/schema.json
 - dept_cmpy


2022-03-29 12:50:09.632:ERROR:pgsync.elastichelper: Exception (psycopg2.errors.UndefinedColumn) column dept_cmpy_1.xmin does not exist
LINE 3: WHERE CAST(CAST(dept_cmpy_1.xmin AS TEXT) AS BIGINT) < 699
                        ^

[SQL: SELECT count(*) AS count_1 
FROM public.dept_cmpy AS dept_cmpy_1 
WHERE CAST(CAST(dept_cmpy_1.xmin AS TEXT) AS BIGINT) < %(param_1)s]
[parameters: {'param_1': 699}]
(Background on this error at: https://sqlalche.me/e/14/f405)
Traceback (most recent call last):
  File "/home/vijee/anaconda3/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/home/vijee/anaconda3/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column dept_cmpy_1.xmin does not exist
LINE 3: WHERE CAST(CAST(dept_cmpy_1.xmin AS TEXT) AS BIGINT) < 699


```

**Comment by trymkb** [comment]
Got the same issue, but believe it is not possible at this moment, it is not part of  the supported features.

I believe that if you can tweak the code a little you could make it use a view as the source table for the query, but it would only trigger on changes of 1 of the tables.

Adding a parameter for monitor table, which will have the the trigger logic, and the view could be in the source table could be a solution.

Also wish to thank @toluaina for the great work you have put into this.

**Comment by toluaina** [comment]
Yes I'm afraid views are not supported yet. I hope to do this whan I have a bit of time

**Comment by toluaina** [comment]
I've added support for views in the master branch.
This requires some addition to the schema.json.

For views, you need to include:
- [base_tables](https://github.com/toluaina/pgsync/blob/master/examples/book_view/schema.json#L7): Each node now requires this entry as a list of tables contributing to the view
- [primary_key](https://github.com/toluaina/pgsync/blob/master/examples/book_view/schema.json#L14): This is a list of primary_key for the view
- [foreign_key](https://github.com/toluaina/pgsync/blob/master/examples/book_view/schema.json#L29-L32): Child nodes should include this to indicate the relationship to the parent node

@trymkb

**Comment by phsophea101** [comment]
I faced this issue @toluaina 

```
pgsync         |  0:00:00.269252 (0.27 sec)
pgsync         | Traceback (most recent call last):
pgsync         |   File "/usr/local/bin/pgsync", line 7, in <module>
pgsync         |     sync.main()
pgsync         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
pgsync         |     return self.main(*args, **kwargs)
pgsync         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1053, in main
pgsync         |     rv = self.invoke(ctx)
pgsync         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
pgsync         |     return ctx.invoke(self.callback, **ctx.params)
pgsync         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 754, in invoke
pgsync         |     return __callback(*args, **kwargs)
pgsync         |   File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 1248, in main
pgsync         |     sync: Sync = Sync(document, verbose=verbose, **kwargs)
pgsync         |   File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 94, in __init__
pgsync         |     self.validate(repl_slots=repl_slots)
pgsync         |   File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 175, in validate
pgsync         |     root: Node = self.tree.build(self.nodes)
pgsync         |   File "/usr/local/lib/python3.7/site-packages/pgsync/node.py", line 276, in build
pgsync         |     raise NodeAttributeError(f"Unknown node attribute(s): {attrs}")
pgsync         | pgsync.exc.NodeAttributeError: "Unknown node attribute(s): {'base_tables'}"
```

**Comment by toluaina** [comment]
closed as resolved. thanks for your patience on this

**Comment by nikhilbadyal** [comment]
I looked into the implementation. Look like `pgsync` trigger an [mat view refresh](https://github.com/toluaina/pgsync/blob/0c58a657a15f989df87dbdff027e03b7c4c5b202/pgsync/sync.py#L1125) on any insert/update on the any of base table. 
Our case is a bit different. We have a`MatView` which combines multiple tables. We only update it once every hour as it's too costly to refresh on every update on the table. 

Any idea how we can table this ?

**Comment by Cognitus-Stuti** [comment]
@toluaina You mentioned views are supported now but it is still looking for the xmin column in the views

**Comment by douglasrehem** [comment]
I am still having issue too
