### ISSUE TITLE
json attribute rename

### ISSUE THREAD

**Issue by aarongundel** [toluaina/pgsync#286]
PGSync version: 2.2.1

Postgres version: 12

Elasticsearch version: 7.9.2

Redis version: 4.1.0

Python version: 3.10

Problem Description: 

I'm trying to rename a json child field created through a column specification, but it doesn't seem to be working.  I've tried a couple of things.  

My columns look like this...
`"columns": ["resourceinstanceid", "descriptors#>{name}", "descriptors#>{description}", "descriptors#>{map_popup}"]`

And my transform looks like this
```
"transform": {
        "rename": {
            "descriptors#>{name}": "name",
            "descriptors#>{description}": "description",
            "descriptors#>{map_popup}": "map_popup"

        }
    }
```

Or this 
```
"transform": {
        "rename": {
            "descriptors_{name}": "name",
            "descriptors_{description}": "description",
            "descriptors_{map_popup}": "map_popup"

        }
    }
```

Either way, the resulting column names are descriptors_{name}, descriptors_{description}, and descriptors_{map_popup} - they seem to be unaffected by the rename transform.  Is there something I'm missing on the rename?  

```

**Comment by toluaina** [comment]
You need to use the resulting name in the transform rename operation.
json fields are simply delimited by an underscore.

This should work:


```
"transform": {
    "rename": {
        "descriptors_name": "name",
        "descriptors_description": "description",
        "descriptors_map_popup": "map_popup"
    }
}
```

**Comment by aarongundel** [comment]
Thanks for the quick response!  Hmmm - that didn't seem to work for me.  Before I re-ran pgsync I deleted the old index, the sync file, and changed my transform per your comment.  The resulting json document still looks like this.

```json
{
"_index": "pgsync_test",
"_type": "_doc",
"_id": "1",
"_version": 1,
"_score": 1,
"_source": {
"descriptors_{name}": "The thing",
"resourceinstanceid": "2",
"descriptors_{map_popup}": "Undefined",
"descriptors_{description}": "Description Here",
"_meta": { }
}

```

**Comment by toluaina** [comment]
This has now been fixed in the master branch. Thanks for bringing that up.

**Comment by toluaina** [comment]
Closing as this has been resolved. thanks
