### ISSUE TITLE
Could not sync children table update after adding a plugin 

### ISSUE THREAD

**Issue by chuanma** [toluaina/pgsync#291]
PGSync version: 2.1.11, 2.2.1, master

Postgres version: 12

Elasticsearch version: opensearch 1.2.3

Redis version: 6.2.6

Python version: 3.7.12

Problem Description: 
I have a simple schema with a pivot table and a child table (one-to-one relationship). Before adding a plugin, if I update the child table, the ES index gets synced correctly. After adding a plugin, 
1. the initial sync works correctly, 
2. updating the pivot table also sync to ES correctly,
3. but updating the child table doesn't sync to ES anymore.

The Redis count is increased when the child table is updated. But the Elastic count is NOT. See below.
```
Sync app Xlog: [0] => Db: [4] => Redis: [total = 4 pending = 0] => Elastic: [33] ...

Sync app Xlog: [0] => Db: [5] => Redis: [total = 5 pending = 0] => Elastic: [33] ...
```

Error Message (if any): 
No error message. But I do notice that the plugin's `transform()` method is not called when the child table is updated.
```


```

**Comment by toluaina** [comment]
Can you share more details about what the plugin is doing?
Are you saying the child is updated correctly without the plugin but not with.
Can we narrow it down to the plugin being the cause?

**Comment by chuanma** [comment]
> Can you share more details about what the plugin is doing?

Some of my child table's data is stored in a jsonb field. So I need to transform them into a proper format for Elastic. I just followed your tutorial at https://pgsync.com/tutorial/plugins/.
```
class MyIndexPlugin(plugin.Plugin):
    name = "MyIndex"

    def transform(self, doc, **kwargs):
        print(doc)

        if kwargs["_index"] != "my_index":
            return doc

        new_doc = self.index_pivot_table(doc)
        if doc["<child_table_name>"] is not None:
            new_doc["<child_table_name>"] =  self.index_child_table(doc["<child_table_name>"])

        print(new_doc)
        return new_doc
```
Another possibly related info is that the 2 tables don't have foreign key constraint in my Postgres database. So I have to add the `foreign_key` in schema.json
```
                    "relationship": {
                        "variant": "object",
                        "type": "one_to_one",
                        "foreign_key": {
                            "child": [
                                "id"
                            ],
                            "parent": [
                                "child_table_id"
                            ]
                        }
                    }
```
And the child_table_id field (in the pivot table) is indexed and nullable
```
    child_table_id = Column(String, nullable=True, index=True)
```

> Are you saying the child is updated correctly without the plugin but not with.

Yes. Without the plugin, the child update is synced correctly. With the plugin, the child update is not. Also the plugin is not even called. Very strange behavior.

> Can we narrow it down to the plugin being the cause?

What I did was to add/remove the `plugins` in schema.json, and then update the child table to see if it's synced to Elasticsearch.  The child field I updated is a jsonb field. Maybe this is also part of the cause? 

But it's all good before adding the plugin. So I feel it should be caused by the plugin.

**Comment by chuanma** [comment]
I just updated a DateTime field in the child table and it didn't work as well. So it should not be tied to the jsonb field type.

**Comment by toluaina** [comment]
if its the plugin, can you please narrow down a bit more or create a fork with the minimal changes to your branch somewhere. 
TBH we are getting down to very specific details here .

**Comment by chuanma** [comment]
After so many experiments and lots of pgsync code review, I've figured out the root cause:

   A plugin's transform() function should always copy the "_meta" field from the original doc, because pgsync relies on the "_meta" field to find the parent table rows that are linked by these child row ids (see [source code](https://github.com/toluaina/pgsync/blob/master/pgsync/elastichelper.py#L224-L228)).

```
    def transform(self, doc, **kwargs):
       ....
        new_doc["_meta"] = doc["_meta"]
        ....
        return new_doc
```
