### ISSUE TITLE
[airbnb example]: Many to one relationship is not working properly

### ISSUE THREAD

**Issue by Wild-Soul** [toluaina/pgsync#294]
PGSync version: Latest version

Hardware: Mac with M1

Postgres version:  14

Elasticsearch version: 7.17.3

Redis version: Redis server v=7.0.1

Python version: python:3.7

Problem Description: 
While following the airbnb database example, I realised that some of the documents are not getting indexed in elasticsearch. There were no error logs on elasticsearch or pgsync docker instances.

Here's the steps that I followed :
1. git clone the repo (master branch).
2. docker-compose up, to get the instances started. I did modified the 
3. Added few more users. <br/>`insert into users (email) values('cicada@gmail.com');
insert into users (email) values('jadecicada@gmail.com');`

4.  Added bookings history for the newly created users : <br/> `insert into bookings (user_id, place_id, price_per_night, num_nights) values(7, 1, 900, 4);`
`insert into bookings (user_id, place_id, price_per_night, num_nights) values(7, 1, 1000, 4);`
`insert into bookings (user_id, place_id, price_per_night, num_nights) values(8, 1, 1100, 1);`
`insert into bookings (user_id, place_id, price_per_night, num_nights) values(7, 2, 1000, 2);`

5. Not all the documents were reflected in ES.
6. After adding another record for booking with start_date and end_date I realised that the records are being overwrite.

So, here's a rough up situation :
One user can have multiple bookings for the same place, maybe at different time stamps. So now there's a many-to-one  relationship between bookings table and places table.

Here's some screenshots for better visualisation 

**Overall ER diagram**
<img width="793" alt="Screenshot 2022-06-10 at 1 12 09 PM" src="https://user-images.githubusercontent.com/30602486/173015953-07ab3158-cada-497c-8cf7-ada84a617b47.png">

**Users table after all insertions**
<img width="325" alt="Screenshot 2022-06-10 at 1 14 05 PM" src="https://user-images.githubusercontent.com/30602486/173016468-06106ffe-48b9-4761-b2d9-31c383fc923e.png">

**Bookings table after all insertions**
<img width="1026" alt="Screenshot 2022-06-10 at 1 15 29 PM" src="https://user-images.githubusercontent.com/30602486/173016665-9bb857c3-e8dc-40e7-a2d1-8be854f5769f.png">

**Comment by toluaina** [comment]
Can you please provide your schema.json config?

**Comment by toluaina** [comment]
Also I'm assuming this is a variation of the original airbnb example?
Which documents were not indexed?

**Comment by Wild-Soul** [comment]
> Can you please provide your schema.json config?

It's the same Schema file as in examples/airbnb Schema.json.

> Also I'm assuming this is a variation of the original airbnb example? Which documents were not indexed?

Yes it's the same example. From bookings table (screenshot), row number 7,8 and 10 were not indexed in ES. Actually they were indexed but as I kept creating new booking for same user, the document was updated on ES side.
