### ISSUE TITLE
Mutliple postgres schemas bootstrap doesn't respect postgres schema for _view table

### ISSUE THREAD

**Issue by jyanay** [toluaina/pgsync#303]
PGSync version: 
2.3.0
Postgres version: 
13.7
Elasticsearch version: 
Opensearch 1.2
Redis version: 
4.0.9
Python version: 
3.9.13
Problem Description: 
When running bootstrap with a schema that defines a parent table with a postgres schema 'aaa' and a child table with a schema 'bbb', the child table has a ```_view``` created with schema 'aaa' and the parent table tries to create a _view with a schema 'public' which in my case doesn't exist.

Error Message (if any): 

```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.InvalidSchemaName) schema "public" does not exist

```

I believe the intended functionality would be that child table ```_view``` is created as 'bbb._view' and the parent table is created as 'aaa._view'.

**Comment by toluaina** [comment]
Hmm. You are right. The original intention was to keep things simple and just have a single global `_view` in the public schema. 
But as you pointed out this simplification has some downsides. 
I've changed the bootstrap logic to create the `_view` in the destination schema. 
Can you try try and let me know

**Comment by jyanay** [comment]
I've tried it out and it now works as expected. Thank you
