### ISSUE TITLE
display of resulting ES record structure

### ISSUE THREAD

**Issue by eichmann** [toluaina/pgsync#305]
PGSync version: 2.3.0

Postgres version: 

Elasticsearch version: 

Redis version: 

Python version: 

Problem Description: 

Just upgraded to 2.3.0 from 2.2.1 (materialized views!). All seems fine, but batch and pgsync no longer display the ES record structure, which was extremely useful in debugging config files during development. Could we have a command line flag or an environment variable to support emitting this info?  Thanks!

Error Message (if any): 

```


```

**Comment by toluaina** [comment]
- Hmm this was definitely not changed if anything it was enhanced.
- both `bootstrap` and `pgsync` still show the document structure. 
- The only addition was the inclusion of the schema name in the tree
- Can you send me a screen shot of what you are seeing.

**Comment by toluaina** [comment]
Closing this for now. Please feel free to reopen
