### ISSUE TITLE
I can't run multiple example with daemon mode

### ISSUE THREAD

**Issue by huytxx** [toluaina/pgsync#308]
PGSync version: 2.3.1

Postgres version: 14

Elasticsearch version: 7.17.4

Redis version: latest

Python version: 3.7

Problem Description: 
I can't run multiple example with daemon mode, it only runs with the first example
<img width="941" alt="ảnh" src="https://user-images.githubusercontent.com/63434038/177693733-9a1ca130-b985-4e23-98a7-9d181be2b4b7.png">

<img width="967" alt="ảnh" src="https://user-images.githubusercontent.com/63434038/177693891-00714e00-e111-4eb9-84b1-ed0f11988d17.png">

**Comment by toluaina** [comment]
You would need to create the database for those examples.
You can run 
`./examples/bootstrap.sh ancestry `

**Comment by huytxx** [comment]
<img width="1013" alt="ảnh" src="https://user-images.githubusercontent.com/63434038/177841174-8e8f206e-375f-4165-ab4b-8343c7147d7c.png">

maybe that's not the problem, it only has a single index, because it can't run down to the bootstrap config line for ancestry
