### ISSUE TITLE
relation "public._view" does not exist at character 61

### ISSUE THREAD

**Issue by hookenful** [toluaina/pgsync#309]
Hello there!

I am having this error. How can I fix it ?

![image](https://user-images.githubusercontent.com/31849464/177721095-d393c33f-52c1-4456-b44d-f8a606c3f6e1.png)

**Comment by toluaina** [comment]
what command are you running and what version of Postgres are you running here?

**Comment by mmbfreitas** [comment]
Hi we are facing same issue here, Have you found any solution??

PGSync version: 2.3.2

Postgres version: 12.11

Elasticsearch version: 7.10

Redis version: 6.2.6

Python version: 3.10.8
