### ISSUE TITLE
Elastic not index more than 2 tables

### ISSUE THREAD

**Issue by lephuhung** [toluaina/pgsync#312]
PGSync version: 2.1.1

Postgres version: 13
Elasticsearch version: 8.2.2

Redis version: 

Python version: 3.7

Problem Description: 
I'm using docker and my schema.json is:
[
  {
    "database": "postgres",
    "index": "datadoc",
    "nodes": {
      "table": "datadoc",
      "schema": "public",
      "columns": []
    }
  },
  {
    "database": "postgres",
    "index": "comment",
    "nodes": {
      "table": "comment",
      "schema": "public",
      "columns": []
    }
  },
  {
    "database": "postgres",
    "index": "post",
    "nodes": {
      "table": "post",
      "schema": "public",
      "columns": []
    }
  }
]

Error Message (if any): 

```
Pgsync not index nodes 'post' (just 'datadoc' and 'comment'), when i switch node comment and post, index is 'datadoc' and 'post'. Not 3 tables index, just 2 first

```

**Comment by lephuhung** [comment]
database:
CREATE TABLE datadoc (
	article_id  text  PRIMARY KEY,
	topic text,
	href text,
	publish_date date,
	newspaper text,
	created_date date,
	language text,
	sapo text,
	content text,
	feature_image text
);
CREATE TABLE page (
  id_page SERIAL PRIMARY KEY,
  id_fb_page text,
  name_page text,
  link_page text
);

CREATE TABLE post (
  id_post SERIAL PRIMARY KEY,
  id_fb_post text,
  publish_time date,
  content text
);

CREATE TABLE comment (
  id_comment SERIAL PRIMARY KEY,
  id_post int,
  id_user text,
  content text,
  publish_time date
);

**Comment by toluaina** [comment]
Did you bootstrap the schema successfully?
was there an error?
Can you please check the value of `max_replication_slots` in postgres

**Comment by lephuhung** [comment]
Thank, It work!!!!

**Comment by lephuhung** [comment]
Close!
