### ISSUE TITLE
Postgres array type data are sorted when syncing

### ISSUE THREAD

**Issue by dasherzx** [toluaina/pgsync#314]
PGSync version: 
2.3.1
Postgres version: 
14.2
Elasticsearch version: 
8.3.2
Redis version: 
6.2
Python version: 
3.7

Problem Description: 
I'm syncing a column consisting of text arrays from postgres to elasticsearch. The operation is successful but the array is sorted within elasticsearch itself. I have already indexed the data type to "keyword".
E.g. in postgres the data looks like ["cover","0","1","2","3"]
In elasticsearch its stored as ["0","1","2","3","cover"]

I have a requirement that the array order is maintained exactly as is. I'm wondering if there's a way to do it. 
Thank you. 

Error Message (if any):

**Comment by toluaina** [comment]
This has been reported once before. I will fix this very soon

**Comment by toluaina** [comment]
This has now been resolved in the master branch. Can you please try and confirm ?

**Comment by dasherzx** [comment]
it works as expected now. thank you.
