### ISSUE TITLE
PGSync is stuck and is not progressing at all.

### ISSUE THREAD

**Issue by AbhiLitmus** [toluaina/pgsync#320]
PGSync version: 2.3.1

Postgres version: 14.2

Elasticsearch version: 7.10.1

Redis version: 4.0.9

Python version: 2.7.17

Problem Description: After setting up the schema.json and adding env variables I do 
`pgsync --config /home/lbtest/pgsync/schema.json --daemon`
and then this result comes, usually if I use simple schema then it sends all data to ES but now with all the required data in schema.json when I try it's stuck on zero for hours.

```
  metadata.reflect(self.__engine, views=True)
 - public.universal_search_counter
   |- public.company
   |- public.candidate_details
   |- public.candidate_education_details
   |- public.campaign_candidate_mapping
   |   - public.campaign
   |- public.candidate
   |- public.stage_step_master
   |- public.ccm_cv_parsing_details
   |- public.l1_responses
   |- public.l2_responses
   |- public.job_candidate_mapping
   |   - public.job
   |- public.stage_step_master
    - public.cv_parsing_details
  [--------------------------------------------------]  0/1894165    0%
```

Error Message (if any): Not getting any error message, but the process is stuck at zero only.

**Comment by jkugsiya** [comment]
I am also facing the same issue, some documents are getting synced but when it comes to huge data it is just stuck at 0 for forever.

**Comment by AbhiLitmus** [comment]
in my case there's a text field in cv_parsing_details table which takes huge texts(resume as text), I guess that is creating this issue. @jkugsiya did you find any solution in your case?

**Comment by jkugsiya** [comment]
@AbhiLitmus I haven't found a solution yet but removing the children fields that have huge data for ex. 520,000 rows is getting it to atleast sync.

**Comment by AbhiLitmus** [comment]
> @AbhiLitmus I haven't found a solution yet but removing the children fields that have huge data for ex. 520,000 rows is getting it to atleast sync.

Okay

**Comment by toluaina** [comment]
are you able to debug this further to isolate why that field is problematic?
Can you try just this field alone in your schema.
How big is the field in question.

**Comment by jkugsiya** [comment]
Hi @toluaina, there is problem when having some fields with multiple children and hierarchy of children.

**Comment by AbhiLitmus** [comment]
@toluaina I tried that field alone, it took some time but then it started indexing properly. So, I kept the all the fields required and then left for some time as I was expecting that it will take time, it got synced properly, just had to wait a little more.
