### ISSUE TITLE
PGsync continuity after stopping it

### ISSUE THREAD

**Issue by AbhiLitmus** [toluaina/pgsync#324]
PGSync version: 2.3.1

Postgres version: 14.2

Elasticsearch version: 7.10.1

Redis version: 4.0.9

Python version: 2.7.17

Problem Description: I have a doubt, if I run pgsync to sync all data and after completion I stopped it for some reason. If I will again run the pgsync then will it start from where I left or it will start syncing again from begining?

**Comment by toluaina** [comment]
- PGSync periodically dumps the state to a checkpoint file.
- This is a hidden file in the current directory starting with a dot.
- PGSync uses the contents of this file to resume from where it left off.

**Comment by toluaina** [comment]
closing this
