### ISSUE TITLE
docs: add documentation around Redis

### ISSUE THREAD

**Issue by andy-clapson** [toluaina/pgsync#340]
We are trying out `pgsync` here for the first time, and we were surprised about the requirement to have a running Redis server. We have one, it was just not mentioned in the docs (although I do see it in the env var list)

Could this be added somewhere in the tutorial setup or checklist?

I'd be happy to add it in a pull request as well, for review.

**Comment by toluaina** [comment]
Sorry about this I have added Redis to the docs in the main [page](https://pgsync.com/requirements/)
This was already on the Github [README](https://github.com/toluaina/pgsync)

**Comment by toluaina** [comment]
Also closing as resolved
