### ISSUE TITLE
Sync process stops updating data in Elasticsearch after a period of time

### ISSUE THREAD

**Issue by briansexton** [toluaina/pgsync#343]
PGSync version: 2.3.2

Postgres version: 13.7

Elasticsearch version: 7.13

Redis version: 5.0.7

Python version: 3.8.10

Problem Description: 
The sync between Postgres and Elasticsearch appears to hang without any errors in the logs. We have setup the pgsync process to run in daemon mode but at some point the data stops getting updated into the ES indexes. There is no increase in the replication slot lag and the only indication in the logs is a mismatch in the numbers 

![image](https://user-images.githubusercontent.com/26006057/191591658-4c1ca2fc-71f4-40a4-a2cc-462a9ebe3dda.png)

We have to restart the pgsync process daily to try and keep it running.

Error Message (if any): 

```


```

**Comment by toluaina** [comment]
- Can you please try  the latest version or pull from the main branch.
- This provides you more detail in the state of each component.
- e.g `Sync book Xlog: [0] => Db: [0] => Redis: [total = 0 pending = 0] => Elastic: [8] ...`
- I couldn't see the last line in the logs. I would check the connection with Redis so see if this is the cause.

**Comment by toluaina** [comment]
Also what happens upon a restart?

**Comment by toluaina** [comment]
Pending = 0 implies there is nothing in the Redis cache. 
One possibility is that the queries are taking time to complete. Maybe its just slow.
Do you have the database correctly indexed? 

Try running `pgsync -c schema.json -a` and see if you need to create any indices

**Comment by briansexton** [comment]
Excellent. That highlighted a number of indexes that needed to be created. Im going to update all of those indexes now and ill let you know if thats resolved the issue.

**Comment by briansexton** [comment]
Yes this has resolved the issue for us now. Thanks for the help
