### ISSUE TITLE
Missing data sync

### ISSUE THREAD

**Issue by orangehaired** [toluaina/pgsync#344]
PGSync version: 
Version: 2.3.2

Postgres version: 
PostgreSQL 14.1 (Debian 14.1-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

Elasticsearch version: 
8.4.2

Redis version: 
Redis server v=5.0.7 sha=00000000:0 malloc=jemalloc-5.2.1 bits=64 build=66bd629f924ac924

Python version: 
3.8

Problem Description: 
select count(*) from messages; -- 245670967 message 
select count(*) from chats; -- 2565418 chats 

Elasticsearch has more missing data. (I have 3 nodes).  Documents seems to be missing. While waiting for 256 thousand chats, it remained at 238 thousand and it has been like this since last night. 

```
health status index                                     uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   messages                                  asbwGwFdT2y6EEP91qbPiw   1   1  245523440       160717    166.3gb         83.2gb
green  open   chats                                     mG6VoTObQDWQAKvpxTCxWg   1   1    2388000            0    806.3mb        393.8mb
```
Error Message (if any): 

```


```

**Comment by toluaina** [comment]
- what is the status printed in the console?
- Also are there any pending records in Redis?  you can use `./scripts/cat_redis.sh `

**Comment by orangehaired** [comment]
Thanks @toluaina. All data is now sync :)

**Comment by toluaina** [comment]
Thanks for the update. Closing this as resolved
