### ISSUE TITLE
The **airbnb** example is broken when run with the pgconfig installed with pip

### ISSUE THREAD

**Issue by ppedrozzi** [toluaina/pgsync#347]
PGSync version: 

Postgres version: 

Elasticsearch version: 

Redis version: 

Python version: 

Problem Description: 
The **airbnb** example is broken at  the line 10 of the file **examples/airbnb/schema.py** when run with docker-compose because the function **load_config** has been committed recently and is not yet available in the version distributed with pip

Error Message (if any): 

```


```

**Comment by cinzunza** [comment]
Yes, I've noticed the same issue on 2.3.2 version, previous version2.3.1 which not includes load_config works normally.

**Comment by toluaina** [comment]
Apologies, this has happened before. I have fixed this once and for all by always installing from the Github repo.

**Comment by toluaina** [comment]
closing as resolved
