### ISSUE TITLE
pip install pgsync doesn't work

### ISSUE THREAD

**Issue by judasane** [toluaina/pgsync#35]
Python version: 3.6

Problem Description: 
When trying to install pgsync from pip, it throws an error 

Error Message (if any): 

```
pip install pgsync
ERROR: Could not find a version that satisfies the requirement pgsync (from versions: none)
ERROR: No matching distribution found for pgsync

```

**Comment by toluaina** [comment]
Interesting. What OS are you running?

**Comment by judasane** [comment]
Windows 10 version 1909 ISO compilation 18363.1016.

I ran under Ubuntu for windows (WSL) and it worked, but it's not working directly from Windows

**Comment by toluaina** [comment]
Yes, window binaries are not available yet. 
This will change soon when the code is made public

**Comment by toluaina** [comment]
pgsync is now open source. closing this
