### ISSUE TITLE
[Question] Can I access request.user in plugin?

### ISSUE THREAD

**Issue by ssandr1kka** [toluaina/pgsync#353]
First of all thank you for reading my question.
Here is the issue,

Django model
```
Object:
  -id
  -name
  -Owners (List of owners)
  ...
```

Right now I have a schema in django ninja:
```
ObjectSchema:
   -id
   -name
   -am_owner? (I use resolver to fetch owner model)

ObjectResolver:
  return Owner.models.filter(user_id=request.user.id, object_id=object.id) (I am being concise here)
```

It would be fantastic to switch to elk, however I would only be able to do so if there is a way to have a plugin where I could make this happen.
I appreciate your help!

**Comment by toluaina** [comment]
The plugin runs in the PGSync space so its decoupled from Django.
That said you should have access to the `user_id` in the plugin if you are including this field in your schema.json.

**Comment by ssandr1kka** [comment]
Hmm thank you
