### ISSUE TITLE
sqlalchemy.exc.OperationalError

### ISSUE THREAD

**Issue by Pavangj959** [toluaina/pgsync#354]
PGSync version: 2.1.9

Postgres version: 14

Elasticsearch version: 

Python version: 3.6

Problem Description: 
Hi All,
When I executed the bootstrap --config schema.json, I am getting this error 

Error Message (if any): 
sqlalchemy.exc.OperationalError: (psycopg2.errors.UndefinedFile) could not access file "test_decoding": No such file or directory

[SQL: SELECT *
FROM PG_CREATE_LOGICAL_REPLICATION_SLOT(%(PG_CREATE_LOGICAL_REPLICATION_SLOT_1)s, %(PG_CREATE_LOGICAL_REPLICATION_SLOT_2)s)]
[parameters: {'PG_CREATE_LOGICAL_REPLICATION_SLOT_1': 'postgres_userindex1', 'PG_CREATE_LOGICAL_REPLICATION_SLOT_2': 'test_decoding'}]

any help would be appreciated.

Thank You

**Comment by toluaina** [comment]
Can you check that you have the `test_decoding` plugin installed in your PostgreSQL installation.
Most PostgreSQL installations ship with this.
Can you provide more details on your Postgres setup?

**Comment by LeoKaynan** [comment]
Upgrade to version 15 aurora pg.

https://docs.aws.amazon.com/pt_br/AmazonRDS/latest/AuroraPostgreSQLReleaseNotes/AuroraPostgreSQL.Updates.html

**Comment by Pavangj959** [comment]
It got resolved by installing postgresql[version]-contrib package.
