### ISSUE TITLE
If I add new data when redis pod is down and restart redis it doesn't sync

### ISSUE THREAD

**Issue by goktugbati** [toluaina/pgsync#385]
PGSync version: latest

Elasticsearch version: 

Redis version:  latest

Python version: 3.7

Problem Description: 
I was testing a failure scenario and I'm using a materialized view.\
Materialized view didn't refresh when I tested the following steps
1.Kill redis pod
2.Add new data
3.Restart redis
4.Make sure pgsync is up and running again
5.Check elasticsearch and the materialized view
6.Materialized view did not contain the data that was added in step 2.
7.Refreshed the materialized view manually and saw that the data was added to elastic search

**Comment by toluaina** [comment]
Sorry is this an underlying issue with running with kubernetes or just a problem with materialized view support. 

Can you confirm if this failure scenario works with or without a materialzed view?

**Comment by toluaina** [comment]
adding new data when the redis pod is down should be fine as long as pgsync itself is also down.
pgsync will NOT run without redis anyway.

**Comment by goktugbati** [comment]
Hi, I confirmed that it does sync when I try the same scenario with a table. I should have confirmed it before opening the issue I'm sorry. So it only happens when a materialized view is used.
I came up with a table based solution with triggers but it doesn't feel right it would be great if you can fix this.
