### ISSUE TITLE
pgsync doesn't support "completion" type

### ISSUE THREAD

**Issue by parisa-mghd** [toluaina/pgsync#417]
PGSync version: 

Postgres version: 

Elasticsearch version: 

Redis version: 

Python version: 

Problem Description: 
I am trying implement suggest completion to my index mapping,but it seems that pgsync doesn't suppot it

Error Message (if any): 

```
RuntimeError: Invalid Elasticsearch type completion

```
```
[
    {
        "database": "",
        "index": "",
        "nodes": {
            "table": "",
            "columns": [
                "id",
                "name"
            ],
            "transform": {
                    "mapping": {
                        "name": {"type": "completion"}
            
                        }
                    }                
            
        }
    }
]
```

**Comment by toluaina** [comment]
I have now added this to the main branch.

**Comment by toluaina** [comment]
Closing as resolved, thanks

**Comment by parisa-mghd** [comment]
still not working 
RuntimeError: Invalid Elasticsearch type compeletion

**Comment by abhishek72850** [comment]
Its still not supported completely, setting completion type works, but adding context doesn't work
https://github.com/toluaina/pgsync/issues/591
