### ISSUE TITLE
Max_replication_slots value and Checkpoint file generation

### ISSUE THREAD

**Issue by accelq** [toluaina/pgsync#421]
PGSync version: Latest

Postgres version: 10

Elasticsearch version: 8.6.2 

Redis version: 6.0.16

Python version: 3.11.2

Problem Description: 
1. Can you let me know the minimum number of replication slots required in max_replication_slots field?
2. During execution of bootstrap command it says no checkpoint file found? What shall I do here? Is it a setup or something I need to perform?
![image](https://user-images.githubusercontent.com/40689807/222095355-7cc93e99-a526-47be-ac96-8011fbc9b7d7.png)
https://pgsync.com/getting-started/setup/

Error Message (if any): 
Here it says max_replication_slots = 1, is minimum required. But during run of bootstrap -c command it fails due to the reason it tries to create more slots one with name `_tmp_` and one more.
```

```

**Comment by toluaina** [comment]
Hi.

- The minimum number for `max_replication_slots` is 1.
    - replication slots requires resources . You basically need one for each node in your schema.json

- Can you send me the exact stark trace for the checkpoint error?
  - You can set the checkpoint location with `CHECKPOINT_PATH`

Also what is you schema structure?
