### ISSUE TITLE
Bootstrap fail to execute because try to recognize tables from other schema

### ISSUE THREAD

**Issue by svilensabev** [toluaina/pgsync#43]
PGSync version: 

Postgres version: 11.7

Elasticsearch version: 7.9.1 

Redis version: 6.0.8

Python version: 

Problem Description: 

PGsync is a great software but currently it fails when trying to bootstrap over existing database. 

I have multiple schemas in my db called `app`

Here is my simple `schema.json`. Syncing data from `public.slot`

```
[
    {
        "database": "app",
        "index": "slots",
        "nodes": [
            {
                "table": "slot",
                "schema": "public",
                "columns": [
                  "id",
                  "name"
                ]
            }
        ]
    }
]

```

This is the structure that I have for `public.slot`

```
CREATE TABLE public.slot (
  id                UUID PRIMARY KEY
                    DEFAULT uuid_generate_v4(),
  name              TEXT NOT NULL
);

insert into public.slot (name) values ('test');
insert into public.slot (name) values ('test 2'); 
```

But I also have another schema `api` with a lot of tables.

```
CREATE EXTENSION citext;
CREATE SCHEMA api;

BEGIN;

  CREATE TABLE api.user (
    id                UUID PRIMARY KEY
                      CONSTRAINT slot_pkey
                      DEFAULT uuid_generate_v4(),
    name         CITEXT NOT NULL
  );

COMMIT;
```

The message that I see is because the table `api.user` is having type citext. Remember, this table is in `api` schema, not in `public` 

Error Message (if any): 

```
root@f024d67dd716:/code# bootstrap --config examples/public/schema.json
 - slot
/usr/local/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/base.py:3131: SAWarning: Did not recognize type 'citext' of column 'name'
  "Did not recognize type '%s' of column '%s'" % (attype, name)

```

I also see errors when running `bootstrap` if TimescaleDB extension is enabled (which apparently we use) .

```
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/reflection.py", line 679, in reflecttable
    raise exc.NoSuchTableError(table.name)
sqlalchemy.exc.NoSuchTableError: cache_inval_hypertable

```

Please explain why it is necessary for `bootstrap` to read other schemas structures, if they are not placed in `schema.json` file

**Comment by toluaina** [comment]
Interesting. 
I will look into the TimescaleDB compatibility separately. I am guessing TimeScale contains some system 
tables which pgsync needs to be aware of such as`cache_inval_hypertable`

pgsync uses the [auto reflection](https://docs.sqlalchemy.org/en/13/core/metadata.html?highlight=reflect#sqlalchemy.schema.MetaData.params.reflect) mechanism in SQLAlchemy 

So this is what is happening 

```
import sqlalchemy as sa
engine = sa.create_engine('postgresql://user@localhost/app')
metadata = sa.MetaData()
metadata.reflect(engine)
```
So you can ignore this warning

**Comment by svilensabev** [comment]
Thanks for the answer @toluaina 

Apologize for misleading information in my first post. 

Error for column with data type `citext` was only a warning. Desired replication was created. 

I knock down the issues on my existing database to following:

* There is incompatibility with TimescaleDB extension. Bootstrap is unable to complete and replication is not created. This extension is nice to have for our stack but not really mandatory.
* There is incompatibility with Postgis extension. I started investigating pg-sync because I want to sync a postgres table with geo points that has data type `geometry`. Bootstrap is unable to complete and replication is not created even if column with `geometry` is in another table in another schema. Postgis is a must have extension for us due to geo data we present in our application. 

I've seen there is this python package that supports postgis in sqlalchemy
https://geoalchemy-2.readthedocs.io/en/latest/ 

Would you like to close this issue and track compatibility of postgis and timescaledb as separate issues?
Please let me know what you think.

Thanks

**Comment by toluaina** [comment]
@svilensabev 

thanks for the update. We can leave this ticket open and I will track the compatibility issues here.

**Comment by toluaina** [comment]
Can you please confirm that you are able to bootstrap a Postgres db with Postis extension but without Timescale DB enabled?
This currently works fine so I am trying to understand the error you got whilst running the bootstrap.
Can you provide a preview of your db schema? 

@svilensabev

**Comment by svilensabev** [comment]
@toluaina 

I think the issue appears once there is a field with `geometry` (or `geography`) type attached to a table. Its in my `api` schema and I tried to bootstrap a table in `public` schema. Ideally I would like to bootstrap directly the table in `api` schema

Here is a sample table definition

```
CREATE TABLE api.slot (
  id                UUID PRIMARY KEY
                    DEFAULT uuid_generate_v4(),
  name         TEXT NOT NULL,
  location      GEOMETRY(POINT,4326)
);
```

And here is what I get when bootstrap

```
root@f024d67dd716:/code# bootstrap --config examples/public/schema.json
 - slot
/usr/local/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/base.py:3131: SAWarning: Did not recognize type 'geometry' of column 'location'
  "Did not recognize type '%s' of column '%s'" % (attype, name)
```

Let me know if you can reproduce the problem. Thanks a lot for your involvement

**Comment by toluaina** [comment]
So, this message is just a warning and not treated as an error. I believe this is a known issue with SQLAlchemy.
Basically, the bootstrap process succeeded and you can continue and run pgsync. 
You can inspect the target table and you sill see some triggers created against the table, 

I am looking into Timescale compatibility as a separate issue.

**Comment by svilensabev** [comment]
Hey @toluaina 

You are right. Postgis extension is compatible and that was just a warning. 

The `location` field was converted to text in elasticsearch mapping

```
        "location": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
``` 

Wonder if there is option in pgsync to convert `location` mapped as `geo_point` in ES. Like exposing as string e.g. `CONCAT(ST_Y(location),',',ST_X(location))::TEXT as location`. The index in ES has to be created first and mapping set correctly.

---

My latest debug is (without Timescale) that a specific constraint was problematic.

Here is my schema

```

BEGIN;

  CREATE TABLE api.slot (
    id                UUID PRIMARY KEY
                      CONSTRAINT slot_pkey
                      DEFAULT uuid_generate_v4(),
    name              TEXT NOT NULL,
    location          GEOGRAPHY(POINT,4326) NOT NULL
  );

COMMIT;


BEGIN;

  CREATE TABLE api.slot_booking (
    id                UUID
                      DEFAULT uuid_generate_v4(),
    slot_id           UUID NOT NULL
                      REFERENCES api.slot
                      ON DELETE CASCADE,
    start_time        TIMESTAMPTZ NOT NULL DEFAULT now(),
    end_time          TIMESTAMPTZ NOT NULL,
    created_at        TIMESTAMPTZ DEFAULT now() NOT NULL,

    PRIMARY KEY (id, start_time)
  );

  -- Gist index with exclude allows constraints between start_time, end_time and overlapping
  ALTER TABLE api.slot_booking
    ADD CONSTRAINT no_overlapping_timestamps
    EXCLUDE USING gist (
      slot_id WITH =,
      start_time WITH <>,
      tstzrange(start_time, end_time) WITH &&
    );

  --SELECT create_hypertable('api.slot_booking', 'start_time');

COMMIT;
```

The boostrap ends with warning but the replication was not created. 

```
/usr/local/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/base.py:3462: SAWarning: Skipped unsupported reflection of expression-based index no_overlapping_timestamps
  "expression-based index %s" % idx_name
 - slot
```

IF I drop the constraint and bootsrap or remove the `slot_booking` table, the replication slot is created

```
ALTER TABLE api.slot_booking
    drop CONSTRAINT no_overlapping_timestamps;
```

Hope this reveals a bit more insight about my case.

**Comment by toluaina** [comment]
You can specify the `type` for the field as indicated in the [docs](https://pgsync.com/tutorial/transform-nodes/).
It seems you are trying to transform a composite field in Elasticsearch.
I will look into this in a bit more detail.
are you simply trying to concatenate them?

**Comment by toluaina** [comment]
Some transformations are now supported including concatenation. More sophisticated operations are in the pipeline
