### ISSUE TITLE
Bootstraping multiple indices in multiple schema files

### ISSUE THREAD

**Issue by virtualaidev** [toluaina/pgsync#432]
PGSync version: latest

Postgres version: debezium/postgres:15

Elasticsearch version: docker.elastic.co/elasticsearch/elasticsearch:7.17.6

Redis version: none

Python version: 3.7

Problem Description:
I have multiple indices where I separate them into their own schema.json. For instance, for the Foo index, I have placed it into its own file (foo.json), same thing with Bar index.

How do you bootstrap and run multiple indices from multiple files, for instance foo.json and bar.json.

**Comment by toluaina** [comment]
- bootstrap requires an argument which is the schema.json 
- So you would need to run bootstrap command for each.
- You could also merge foo and bar but the downside of this is that its bad for performance

```
bootstrap -c foo.json 
bootstrap -c bar.json
```

**Comment by virtualaidev** [comment]
Hi @toluaina do you also do the same when running the pgsync?

```
pgsync -c foo.json -d
pgsync -c bar.json -d
```
