### ISSUE TITLE
pgsync gets killed without throwing error

### ISSUE THREAD

**Issue by CE-Creates** [toluaina/pgsync#44]
I ran the following as usual
```
$ pgsync --config staging_schema.json
[=====================================-------------] 74.6% Killed
$
```

Where can I see the error? how do i debug this ?

**Comment by toluaina** [comment]
It looks like an external process might have killed it. Possibly the OOM Killer 
Can you run it with verbose enabled:

`pgsync --verbose --config staging_schema.json`

My guess is that the memory requirement is exceeding the resources available. 
Maybe you can also run `top` command to see how much memory is being used

**Comment by toluaina** [comment]
This issue has been addressed above
