### ISSUE TITLE
How can I config analyzers

### ISSUE THREAD

**Issue by CE-Creates** [toluaina/pgsync#45]
WIth my basic knowledge with elastic search, we could configure analyzers like snowball. 
how do we achieve it with pgsync ?

**Comment by toluaina** [comment]
This is now possible with the latest version 1.1.14. 
You can provide the Elasticsearch setting in the schema.json config.
This has been added to the [doc](https://pgsync.com/schema/) under **setting**

@CE-Creates

**Comment by toluaina** [comment]
Support for analyzers has been added and documented
