### ISSUE TITLE
pgsnc.exc.foreignkeyerror: no foreign key relationship between tableA and tableB

### ISSUE THREAD

**Issue by bydeath** [toluaina/pgsync#46]
PGSync version: 1.1.6

Postgres version: 11.7

Elasticsearch version: 7.9.2
Redis version: 5.0.7

Python version: 3.6.3

Problem Description: 
It raises an error when I execute `pgsync --config schema.json`. Yes, there is no foreign key between the tables? Is it necessary to define a foreign key? 

Error Message (if any): 

```


pgsnc.exc.foreignkeyerror: no foreign key relationship between tableA and tableB

```

**Comment by toluaina** [comment]
Yes, you need to have foreign key relationship defined between **tableA** and **tableB** otherwise pgsync wouldn't know how to connect these tables

**Comment by bydeath** [comment]
> Yes, you need to have foreign key relationship defined between **tableA** and **tableB** otherwise pgsync wouldn't know how to connect these tables

Thanks for your kind reply. 
Pgsync is powerful tool. But there are no foreign keys defined in my case. I am thinking why not give user another way to specify how two tables are connected? for examples by specifing a fields pair. Below is an schema example that I expect.  There is a key `connect_pair` to specify how the table `blog` and `tag` are connected.
```json
[
    {
        "database": "mydb",
        "index": "myindex",
        "nodes": [
            {
                "table": "blog",
                "schema": "public",
                "columns": [
                ],
                "children": [
                    {
                        "table": "tag",
                        "label": "tag_list",
                        "schema": "public",
                        "columns": [],
                        "relationship": {
                            "variant": "scalar",
                            "type": "one_to_many"
                        },
                        "connect_pair": ["blog.id", "tag.blog_id"]
                    }
                ]
            }
        ]
    }
]
```

**Comment by toluaina** [comment]
Thanks and I see your point. I think this feature had been asked once before but I wanted to avoid defining foreign key relationships in the config because it makes pgsync a bit more cumbersome to use. 

We need to structure the config so that it can support compound foreign key relationships. 
I will start assessing the scope of this.

**Comment by toluaina** [comment]
Defining a foeign key is now supported in the schema.
[Here](https://github.com/toluaina/pgsync/blob/master/examples/book/schema.json#L81) is an example .

Feel free to re-open if you need more clarification.
