### ISSUE TITLE
Large Memory Demands When Initializing Sync 

### ISSUE THREAD

**Issue by collinpu** [toluaina/pgsync#47]
PGSync version: 1.1.14

Postgres version: 12-alpine

Elasticsearch version: 7.7.0

Redis version: 6.0.8

Python version: 3.7

Problem Description: 

I just (10/16/20) created a fresh install using docker and your provided docker-compose file. I am trying to sync from a large postgres database (~600GB) and am experiencing memory issues. This is particularly true for large tables (~350M rows). I have found that reducing QUERY_CHUNK_SIZE from 10k to 1k helps a lot but am still experiencing ram usage upwards of 90GB during the initial sync (docker exec -it pgessync_pgsync_1 --config /code/myschema.json --daemon -v). When running with -v I noticed that the ram utilization problem occurs while executing the "Query"  phase. Do you have any recommendations/solutions for keeping memory utilization low when syncing from a large postgres database/know what is causing this?

**Comment by toluaina** [comment]
This depends on your relational data model. Do you have wide tables? I would consider dropping QUERY_CHUNK_SIZE even further especially since you indicate this had a significant effect. 

How many child tables are present in your schema? Or can you share your schema.

**Comment by toluaina** [comment]
Also, what was the ratio of RAM utilization when dropping QUERY_CHUNK_SIZE from 10k to 1k

**Comment by toluaina** [comment]
Closing this for now. feel free to re-open if this continues
