### ISSUE TITLE
Cannot install via pypi

### ISSUE THREAD

**Issue by shauryashahi** [toluaina/pgsync#48]
Error Message (if any): 

```
(env) ~ $ pip install pgsync
ERROR: Could not find a version that satisfies the requirement pgsync (from versions: none)

```

**Comment by toluaina** [comment]
Just published version 1.1.16. Can you try now

**Comment by Bramwellde** [comment]
Hey Tolouaina,
I just pulled version 1.1.16, whenever I try to run pgsync or bootstrap im met with the following error:
Traceback (most recent call last):
  File "/usr/local/bin/pgsync", line 4, in <module>
    from pgsync import sync
ModuleNotFoundError: No module named 'pgsync'


I tried across mac, centos, and ubuntu both inside and outside venv's
Any tips -- before this error i was experiencing the same thing as shauryashahi.

**Comment by toluaina** [comment]
Sorry about this. This was a packaging bug. This has been fixed and version 1.1.17 published

**Comment by Bramwellde** [comment]
Awesome I can confirm this works :L)
Follow up question - im having problems with bootstrap not reading the .env settings. is there somewhere in particular i should put it for it to work? Thanks

**Comment by shauryashahi** [comment]
i realised i use a managed gcp cloud sql. can't edit config for `wal_level` ... anyways...I am going with a celery signal processor via https://github.com/django-es/django-elasticsearch-dsl for now to sync some of my Postgres models to Elastic.

I guess, consistency is something I have to give up with an async approach , but it's ok for now...

**Comment by toluaina** [comment]
> Awesome I can confirm this works :L)
> Follow up question - im having problems with bootstrap not reading the .env settings. is there somewhere in particular i should put it for it to work? Thanks

You just need to create. **.env** file where you run the application. There is a sample env in the [repository](https://github.com/toluaina/pgsync/blob/master/.env.sample) 

@Bramwellde

**Comment by toluaina** [comment]
Closing as all issues have been addressed
