### ISSUE TITLE
pgsync have understand   ltree 

### ISSUE THREAD

**Issue by Barolina** [toluaina/pgsync#484]
PGSync version:  0.8.0

Postgres version:  11

Elasticsearch version:   

Redis version: 

Python version:  3.7

Problem Description: 

My  database  is  ltree. 

My first  step:  i run  bootstrap for my scheme.json 

Error Message (if any): 

```
usr/local/lib/python3.7/dist-packages/pgsync/base.py:205: SAWarning: Did not recognize type 'ltree' of column 'path'
  metadata.reflect(self.engine, views=True)
/usr/local/lib/python3.7/dist-packages/pgsync/base.py:205: SAWarning: Skipped unsupported reflection of expression-based index register_search_vector_index_md_5

```

**Comment by toluaina** [comment]
This warning originates from SQLAlchemy. That custom type is unknown to SQLAlchemy. This is just a warning so feel free to ignore.

**Comment by Barolina** [comment]
thank you
