### ISSUE TITLE
Manual configuration , python is not able to detect pgsync even after installing it . Tried even going to the folder of pgsync to run it 

### ISSUE THREAD

**Issue by ksrdj** [toluaina/pgsync#50]
Postgres version:  9.4

Elasticsearch version: 7

Redis version: 6.0.9

Python version: 3,7

Problem Description: 

Unable to use pgsync 

Error Message (if any): 'pgsync' is not recognized as an internal or external command,
operable program or batch file.

```


```

**Comment by toluaina** [comment]
Did you create a virtualenv and install via pip?
Also, can you provide more detail on your installation environment?

**Comment by ksrdj** [comment]
No i did not create a virtual environment . I installed it via pip to my default environment . 

I have anaconda  -  python 3.7 running in windows 10 

Redis 6.0.9 and elasticsearch 7 , postgres 9.4

Redis and pg_config is added to the system variable

**Comment by toluaina** [comment]
I'm guessing the Python bin directory is not included in your PATH env variable. 
I am not entirely familiar with the setup on win 10. 
You can try [this](https://datatofish.com/add-python-to-windows-path/). 

if you` echo $PATH` you should see your current PATH

**Comment by toluaina** [comment]
Di you have any success with this?

**Comment by ksrdj** [comment]
Hi .
In windows  even after changing the path variable it dint work .
So I installed linux os (ubantu 20.04) and tried to run it manually . It worked .
Maybe you can specify that in readme that currently it supports only linux based os and not windows . So it may help someone .
Thank you so much for your efforts and support  and this is  a great tool .
