### ISSUE TITLE
how to make the logs display the pgsync process

### ISSUE THREAD

**Issue by Barolina** [toluaina/pgsync#509]
I am executing the command 

```
  sudo python3 bin/bootstrap --config scheme.json
```

And  i have  60к records  in BD

Now,  the  result  is a view

```
 metadata.reflect(self.engine, views=True)
 - public.ed
   |- public.save_type
   |- public.ed_cipher
   |- public.dossier
   |  |- public.di_kind
   |  |  |- public.di_save_period
   |  |   - public.di_kind_group
   |  |      - public.di_classifier
   |   - public.register
   |     |- public.register_status
   |     |- public.archive
   |      - public.fund
   |- public.ed_status
   |- public.subdivision
   |- public.file
   |   - public.file_content
    - public.media_type_ed
  [--------------------------------------------------]  0/60539    0%


```
about 20 min.

What do i do? How  to make the logs display  a process  and   data ?  

Please

**Comment by zPabloMorales** [comment]
using --verbose flag
  
  sudo python3 bin/bootstrap --verbose --config scheme.json

**Comment by Barolina** [comment]
how  about  command  pg_sync?

**Comment by Barolina** [comment]
> using --verbose flag
> 
> sudo python3 bin/bootstrap --verbose --config scheme.json

can i  write log in  file   a result  for  bootstrap and   pgsync ?

**Comment by zPabloMorales** [comment]
If you use redirect stdout, you can write logs in a file. 

bootstrap --verbose --config $EXAMPLE_DIR/schema.json >& log.txt
pgsync --verbose --config $EXAMPLE_DIR/schema.json --daemon >& log2.txt 

https://stackoverflow.com/questions/11255447/what-does-mean

**Comment by Barolina** [comment]
thank you
