### ISSUE TITLE
Explanation of schema.json?

### ISSUE THREAD

**Issue by AdityaAnand1** [toluaina/pgsync#51]
Trying to use pgsync, but I was only able to find samples of schema.json but no document explaining the general structure, possible nodes, properties, their meanings etc.

Also, is there a way to auto generate schema.json from an postgresql table? Or any utilities that can help map a index schema to a table definition or query or view definition?

What if I'd like a complex query mapped on to a elasticsearch index? E.g.: Say there's a one-to-many mapping of objects to categories, and I would like a column that `string_agg()`'s the categories into one index property? Is this possible? (E.g. Obj o of table T, would have a property `category` containing categories c1, c2...cn from table C)

**Comment by toluaina** [comment]
There is documentation on the main page: https://pgsync.com/
You can also have a look at the tutorial and user guide.

**Comment by toluaina** [comment]
Closing this issue as the doc is provided as indicated above.
