### ISSUE TITLE
SERVERGOT HACK TO MAKE GAMBLING ONLINE AND SPAM

### ISSUE THREAD

**Issue by OLIV853** [toluaina/pgsync#536]
![pgsync](https://github.com/toluaina/pgsync/assets/153894964/64f7320d-d046-4d27-9db5-269255240bf2)

Hello Sir,

I want to inform that  Your Server site already got hacked to make so many sub domain for gambling online site that's ilegal to do.

You can check in google use this keyword :
slot site:pgsync.com

it will display so many this is serveral of the links:
http://huft.pgsync.com/

and if you click on mobile google it will direct you to this link :
https://miracleboy.ikantaki.xyz/kasihpaham/
https://idagent138go.art/

Please Remove,Banned also Track the Hacker and make the Hacker go to Jail.

As an Indonesian citizen, I want to emphasize that online gambling is clearly prohibited by Indonesian law. In accordance with Article 27 paragraph (2) of the ITE Law, this act is a prohibited act. Therefore, individuals are prohibited from distributing, transmitting or making accessible gambling content online.

I have attached clear photographic evidence related to this case. My request is that you immediately take the necessary action to delete this sub-domain and online gambling page, or at least suspend access immediately so that online gambling content cannot be accessed. I hope that firm steps will be taken to ensure the integrity of the father's name is maintained and to avoid potential legal problems in the future.

I am grateful for the attention and action taken regarding this matter. I am sure that you will uphold ethics and legal compliance in carrying out your services.

Yours faithfully,

**Comment by mpaolino** [comment]
@toluaina ^

**Comment by NOBLES5E** [comment]
I thought it's a joke but it turns out to be true :joy_cat:
