### ISSUE TITLE
Command 'pgsync' not found

### ISSUE THREAD

**Issue by AdityaAnand1** [toluaina/pgsync#56]
```
Command 'pgsync' not found, did you mean:

  command 'pkgsync' from deb pkgsync

Try: sudo apt install <deb name>
```

Reproduction steps:

1. sudo apt get update
2. sudo apt install python3-pip
3. pip3 install pgsync
4. pgsync
5. (above output)

**Comment by toluaina** [comment]
what is the default python version?
Do you have multiple versions of pythons installed?

**Comment by toluaina** [comment]
?
@AdityaAnand1

**Comment by toluaina** [comment]
Closing as this has been answered. Feel free to reopen if this comes up again,

**Comment by lehuuthien2** [comment]
I use wsl for windows 10
python 3.8.10
![image](https://user-images.githubusercontent.com/43700083/156292056-a73d9541-d6be-48a1-b506-744cdf8862ee.png)

**Comment by toluaina** [comment]
I believe you need to add the runtime bin directory to your PATH. This is the directory that contains `pgsync`
