### ISSUE TITLE
Error when running with schema

### ISSUE THREAD

**Issue by bling683** [toluaina/pgsync#562]
PGSync version: 3.2.0

Postgres version: v12

Elasticsearch/OpenSearch version: Opensearch 2.15.0

Redis version: 7.0.0

Python version: 3.12

Problem Description: 
Error when running `pgsync --config schema.json --daemon`

Error Message (if any): 
```
psycopg2.errors.UndefinedFunction: function max(pg_lsn) does not exist
LINE1: SELECT max(pg_current_wal_lsn) AS max_1

HINT: No function matches the given name and argument types. You might need to add explicit type casts.

```

**Comment by bling683** [comment]
Any insight to what this is happening above?

**Comment by zaschim** [comment]
@bling683 I see you closed this issue but I'm running into it. What was the resolution?

**Comment by Slayug** [comment]
I had to do the following change to make it works
```python
     @property
     def current_wal_lsn(self) -> str:
         return self.fetchone(
-            sa.select(sa.func.MAX(sa.text("pg_current_wal_lsn"))).select_from(
-                sa.func.PG_CURRENT_WAL_LSN()
-            )
+            sa.select(sa.func.PG_CURRENT_WAL_LSN())
         )[0]

``` 
max function seems to not support the lsn type.
