### ISSUE TITLE
Is it possible to keep multiple tables/indices synced with a single pgsync process?

### ISSUE THREAD

**Issue by AdityaAnand1** [toluaina/pgsync#58]
Currently, it appears that multiple instances of pgsync need to be run in daemon mode if I want to sync multiple tables with their indices, with each instance managing a single schema json file.

Is it possible to specify more than one schema within a single command?

Perhaps something like:

```
pgsync --config_dir ./configs
```

Where `./configs` has a bunch of schema files

```
./schema-1.json
./schema-2.json
...

```

**Comment by toluaina** [comment]
You can have multiple schema views in the same config. 

i.e 

```
[
    {
        "database": "db1",
        "index": "index1",
        "nodes": [
            {
                "table": "book",
            }
        ]
    },
    {
        "database": "db2",
        "index": "index2",
        "nodes": [
            {
                "table": "book",
            }
        ]
    }
]
```

**Comment by noyb34** [comment]
@toluaina  Given the example above, can you do something like the below?
`[
    {
        "database": "db1",
        "index": "index1",
        "nodes": [
            {
                "table": "book",
            }
        ]
    },
    {
        "database": "db1",
        "index": "index2",
        "nodes": [
            {
                "table": "book",
            }
        ]
    }
]`
Thanks

**Comment by toluaina** [comment]
> index2

Yes, absolutely, You can totally do this.

@noyb34

**Comment by toluaina** [comment]
Closing as this issue has been resolved
