### ISSUE TITLE
Referencing root table in reference chain breaks change event updates

### ISSUE THREAD

**Issue by manuelwaldner** [toluaina/pgsync#586]
PGSync version: pip install git+https://github.com/toluaina/pgsync.git

Postgres version: postgres:17

Elasticsearch/OpenSearch version: elasticsearch:7.17.13

Redis version: redis:latest (sha256:590b81f2fea1af9798db4580a6299dafba020c2f5dc7d8d734663e7fa5299ca0)

Python version: 3.9

Operating System: Windows

WSL-Version: 2.2.4.0
Kernelversion: 5.15.153.1-2
WSLg-Version: 1.0.61
MSRDC-Version: 1.2.5326
Direct3D-Version: 1.611.1-81528511
DXCore-Version: 10.0.26091.1-240325-1447.ge-release
Windows-Version: 10.0.22631.4460

Problem Description: 
I use the docker-compose from your repository to start a local test with the following database info:
Database: circular_test
Schema: landlord
Tables:
- customer
  - id (PK)
- property
  - id (PK)
  - customer_id (FK to customer.id)
- customer_cooperation_property_delegation
  - id (PK)
  - sender_property_id (FK to property.id)
  - receiver_property_id (FK to property.id)

You can use the setup_schema.sql inside the attached zip to create the schema and input sample data into it.

I put the schema.json, either `_not_working` or `working` which are contained in the zip too, into another folder inside the `examples` folder, e.g. `circular_test` and changed the Dockerfile to have the `EXAMPLE_NAME` variable to be `circular_test`.

When having the second level children added (`_not_working` postfix), any update on any table does not lead to an update of the document in elasticsearch. The initial sync on startup works though.
If you remove the second level children (`_working` postfix), the updates are getting synced to elasticsearch again.
The change events are getting recognized by pgsync, but after reading the change event from redis and doing some postgres statements (i guess fetching the needed data), the update is not synced to elasticsearch.
I tried to see if there are any additional info with  LOG_LEVEL=DEBUG and CONSOLE_LOGGING_HANDLER_MIN_LEVEL=DEBUG, but this didn't help.

[files.zip](https://github.com/user-attachments/files/17990348/files.zip)

**Comment by toluaina** [comment]
Can you please try using the version on the master branch now

**Comment by manuelwaldner** [comment]
Hi,
thank you for your fast response. The updates are now recognized. But there is another issue now.
The children are not part of the Elasticsearch Documents anymore, when you adjust one of the children (even the one, of the root node).

I updated the Database schema and the schema_not_working.json.

The initial startup-sync is working fine, but when executing the following update statement, the `partner` and `portals` are missing from the `senderCounterpart`. Only the `id` of the `senderCounterpart` is there:
```
UPDATE landlord.portal 
SET status = 'NEW'
WHERE id = 42;
```

The updated files:
[files_updated.zip](https://github.com/user-attachments/files/18033556/files_updated.zip)

**Comment by toluaina** [comment]
Got it thanks. Can you try once again please.

**Comment by manuelwaldner** [comment]
Hey, just tested it.
Seems to work correctly. 
Thank you very much 👍🏻
