### ISSUE TITLE
Pgsync can't config a schema containing multiple children from the same table

### ISSUE THREAD

**Issue by anis-b-amara** [toluaina/pgsync#60]
PGSync version: 

Postgres version: 12

Elasticsearch version: 7.10.0

Redis version: 6.0.9

Python version: python3.7-dev

Problem Description: 

Let's say I have a table called `distributors` which has two columns: `previous_intervention` and `next_intervention` (both reference to another table called `interventions`).

Here is the possible schema I want to create:
```json
[
  {
    "database": "db",
    "index": "distributors",
    "nodes": [
      {
        "table": "distributors",
        "columns": [
          "id",
          "name"
        ],
        "children: [
          // Put previous_intervention and next_intervention from table interventions
        ]
      }
    ]
  }
]
```

I couldn't find a way to create two children that point to the same table but reference to different columns. The relationship to both children is `one_to_one`.

**Comment by sl-vincentaugerot** [comment]
We have the same problem. When we have a children with two foreign keys pointing to the same table pgsync do not synchronize the children.

In schema.json we have the following relation passing through zone_relation_neighbor
` {
                        "table": "zone",
                        "schema": "cassini",
                        "columns": [
                            "id",
                        ],
                        "label": "parents",
                        "relationship": {
                            "variant": "object",
                            "type": "one_to_many",
                            "through_tables": [
                                "zone_relation_parent"
                            ]
                        }
                    }`

Our table : 
`CREATE TABLE zone_relation_parent
(
    zone_id text COLLATE pg_catalog."default" NOT NULL,
    zone_id_relation text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT zone_relation_parent_zone_id_fkey FOREIGN KEY (zone_id)
        REFERENCES zone (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT zone_relation_parent_zone_id_relation_fkey FOREIGN KEY (zone_id_relation)
        REFERENCES zone (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;`

It works well through table that don't have two foreign keys on the same tables. Any ideas please ?

**Comment by toluaina** [comment]
> ```json
> next_intervention
> ```



> PGSync version:
> 
> Postgres version: 12
> 
> Elasticsearch version: 7.10.0
> 
> Redis version: 6.0.9
> 
> Python version: python3.7-dev
> 
> Problem Description:
> 
> Let's say I have a table called `distributors` which has two columns: `previous_intervention` and `next_intervention` (both reference to another table called `interventions`).
> 
> Here is the possible schema I want to create:
> 
> ```json
> [
>   {
>     "database": "db",
>     "index": "distributors",
>     "nodes": [
>       {
>         "table": "distributors",
>         "columns": [
>           "id",
>           "name"
>         ],
>         "children: [
>           // Put previous_intervention and next_intervention from table interventions
>         ]
>       }
>     ]
>   }
> ]
> ```
> 
> I couldn't find a way to create two children that point to the same table but reference to different columns. The relationship to both children is `one_to_one`.


Can you do something as simple as 

```

[
    {
        "database": "db",
        "index": "distributors",
        "nodes": [
            {
                "table": "distributors",
                "columns": [
                    "previous_intervention",
                    "next_intervention"
                ] 
            }
        ]
    }
]
```

Perhaps not. Could you possibly send me your db schema?

**Comment by toluaina** [comment]
> {
>     "table": "zone",
>     "schema": "cassini",
>     "columns": [
>         "id",
>     ],
>     "label": "parents",
>     "relationship": {
>         "variant": "object",
>         "type": "one_to_many",
>         "through_tables": [
>             "zone_relation_parent"
>         ]
>     }
> }

I am a little unsure of what you are trying to accomplish. Only child nodes can have relationships. 
But the schema contains just a root node with a relationship.

**Comment by sl-vincentaugerot** [comment]
> > {
> > "table": "zone",
> > "schema": "cassini",
> > "columns": [
> > "id",
> > ],
> > "label": "parents",
> > "relationship": {
> > "variant": "object",
> > "type": "one_to_many",
> > "through_tables": [
> > "zone_relation_parent"
> > ]
> > }
> > }
> 
> I am a little unsure of what you are trying to accomplish. Only child nodes can have relationships.
> But the schema contains just a root node with a relationship.

Thank you for your response.
I have only send you a snippet on my schema.

The full schema is : 
```
{
        "database": "lu",
        "index": "zones",
        "setting": {},
        "nodes": [
            {
                "table": "zone",
                "schema": "cassini",
                "columns": [
                    "cassini_id",
                    "country_code",
                    "admin_level",
                    "geometry_json",
                    "bounding_box_json"
                ],
                "children": [
                    {
                        "table": "metadata",
                        "schema": "cassini",
                        "columns": [
                            "key",
                            "value",
                            "type"
                        ],
                        "label": "metadatas",
                        "relationship": {
                            "variant": "object",
                            "type": "one_to_many",
                            "through_tables": [
                                "zone_metadata"
                            ]
                        }
                    },
                    {
                        "table": "zone",
                        "schema": "cassini",
                        "columns": [
                            "cassini_id",
                            "country_code",
                            "admin_level"
                        ],
                        "label": "parents",
                        "relationship": {
                            "variant": "object",
                            "type": "one_to_many",
                            "through_tables": [
                                "zone_relation_parent"
                            ]
                        }
                    }
                ],
                "transform": {
                    "rename": {
                        "cassini_id": "cassiniId",
                        "country_code": "countryCode",
                        "admin_level": "adminLevel",
                        "geometry_json": "geometry",
                        "bounding_box_json": "boundingBox"
                    }
                }
            }
        ]
    }
```

The  "label": "metadatas" relation is working well but the  "label": "parents" have always a null property. And the only difference is see between my two tables : zone_metadata and zone_relation_parent is that zone_relation_parent have two foreign key targeting to the same table "zones". I think pgsync is not working correctly when the through_tables property table is filled with a table that have at least two properties pointing to the same table. Do i have wrong ? I think is an issue

**Comment by anis-b-amara** [comment]
@toluaina 

Thank you for your response.

I share with you my PostgreSQL Schema, so the problem is how i can implement this schema with PGSync,

NB: In this Schema, i have two columns that point to the same table (next_intervention_id, previous_intervention_id) reference on interventions.

```
CREATE TABLE public.distributors
(
    "createdAt" timestamp without time zone NOT NULL DEFAULT now(),
    "updatedAt" timestamp without time zone NOT NULL DEFAULT now(),
    id integer NOT NULL DEFAULT nextval('distributors_id_seq'::regclass),
    name character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'Distributeur'::character varying,
    address character varying COLLATE pg_catalog."default" NOT NULL,
    site character varying COLLATE pg_catalog."default",
    contact character varying COLLATE pg_catalog."default",
    contact_phone character varying COLLATE pg_catalog."default",
    uuid character varying COLLATE pg_catalog."default",
    latitude character varying COLLATE pg_catalog."default" NOT NULL,
    longitude character varying COLLATE pg_catalog."default" NOT NULL,
    status character varying COLLATE pg_catalog."default",
    request_date date,
    gel_level integer NOT NULL DEFAULT 100,
    battery_level integer NOT NULL DEFAULT 100,
    picture_url character varying COLLATE pg_catalog."default",
    comment character varying COLLATE pg_catalog."default",
    "previous_intervention_id " integer,
    "next_intervention_id " integer,
    total_dose_delivered integer DEFAULT 0,
    last_used_at timestamp with time zone,
    first_used_at timestamp with time zone,
    CONSTRAINT "PK_a3741291eb0af96f795b25d90b4" PRIMARY KEY (id),
    CONSTRAINT "UQ_257784d75a0b2324e4d74b13c8a" UNIQUE (uuid),
    CONSTRAINT "FK_3d82fbb721f10577b601f9dad36" FOREIGN KEY ("previous_intervention_id ")
        REFERENCES public.interventions (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_7032ebe7e7987661d32dc219d5c" FOREIGN KEY ("next_intervention_id ")
        REFERENCES public.interventions (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
)
```

**Comment by toluaina** [comment]
@anis-b-amara 
I think you can do something like this 

```
[
    {
        "database": "db",
        "index": "distributors",
        "nodes": [
            {
                "table": "distributors",
                "columns": [
                  "id",
                  "name"
                ],
                "children": [
                    {
                        "table": "interventions",
                        "columns": [
                             intervention columns goes here ...
                        ],
                        "relationship": {
                            "variant": "object",
                            "type": "one_to_one"
                        }
                    }
                ]
            }
        ]
    }
]
```

**Comment by toluaina** [comment]
@sl-vincentaugerot 

I feel this is a separate issue. 
Your schema will result in a self-referential query through zone_relation_parent.
So zone is a child of zone and has a foreign key through zone_relation_parent.

Perhaps indeed this is a limitation that I have not explored.  
Would you mind opening a separate issue for this to track this?

**Comment by sl-vincentaugerot** [comment]
> @sl-vincentaugerot
> 
> I feel this is a separate issue.
> Your schema will result in a self-referential query through zone_relation_parent.
> So zone is a child of zone and has a foreign key through zone_relation_parent.
> 
> Perhaps indeed this is a limitation that I have not explored.
> Would you mind opening a separate issue for this to track this?

Hi @toluaina , first happy new year for you 
I have created a separate issue here : [Issue with through_tables when foreigns keys target the same table](https://github.com/toluaina/pgsync/issues/63)
I hope you can help us make this particular case work

**Comment by toluaina** [comment]
Closing this. I think the secondary issue was reolved elswhere. re-open if this is not the case.
