### ISSUE TITLE
Issue when Running in Docker

### ISSUE THREAD

**Issue by HinaAziz-graana** [toluaina/pgsync#61]
PGSync version: 

Postgres version: 

Elasticsearch version: 
elasticsearch:7.9.3
Redis version: 

Python version: 
python:3.7
Problem Description: 
I try to run pgysnc in docker and after executing for some time.It starts throwing following errors

Error Message (if any): 
 Exception in thread Thread-15:
pgsync_1         | Traceback (most recent call last):
pgsync_1         |   File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
pgsync_1         |     self.run()
pgsync_1         |   File "/usr/local/lib/python3.7/threading.py", line 870, in run
pgsync_1         |     self._target(*self._args, **self._kwargs)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 816, in poll_db
pgsync_1         |     conn.poll()
pgsync_1         | psycopg2.OperationalError: SSL SYSCALL error: EOF detected
```


```

**Comment by toluaina** [comment]
Can you provide more details on this? e.g do you have SSL enabled? Also what OS are you running on ?

**Comment by toluaina** [comment]
I think the solution proposed in [this thread](https://github.com/docker/for-mac/issues/3679#issuecomment-642885218) might be relevant.
It appears what is shared in common is long-running queries running under Docker?

My suggestion is to add these variables to your compose 
```
    sysctls:
        - net.ipv4.tcp_keepalive_time=200
        - net.ipv4.tcp_keepalive_intvl=200
        - net.ipv4.tcp_keepalive_probes=5 
```

**Comment by toluaina** [comment]
Closing this for now. Please try the latest changes from master
