### ISSUE TITLE
Issue with through_tables when foreigns keys target the same table

### ISSUE THREAD

**Issue by sl-vincentaugerot** [toluaina/pgsync#63]
First, thanks for your awesome tool :)
When we have a children with two foreign keys targetting the same table pgsync do not synchronize the children.

PGSync version: 1.1.14
Postgres version: 11.4
Elasticsearch version: 7.4
Redis version: 5.0.0

In schema.json we have the following relation passing through zone_relation_parent
```
 {
    "table": "zone",
    "schema": "cassini",
    "columns": [
        "id",
    ],
    "label": "parents",
    "relationship": {
        "variant": "object",
        "type": "one_to_many",
        "through_tables": [
            "zone_relation_parent"
        ]
    }
}
```

Our table : 
``` 

CREATE TABLE zone
(
    id text COLLATE pg_catalog."default" NOT NULL DEFAULT nextval('zone_sequence'::regclass),
    cassini_id text COLLATE pg_catalog."default",
    CONSTRAINT zone_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

CREATE TABLE zone_relation_parent
(
    zone_id text COLLATE pg_catalog."default" NOT NULL,
    zone_id_relation text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT zone_relation_parent_zone_id_fkey FOREIGN KEY (zone_id)
        REFERENCES zone (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT zone_relation_parent_zone_id_relation_fkey FOREIGN KEY (zone_id_relation)
        REFERENCES zone (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;
```

The full schema.json is : 
```
{
        "database": "lu",
        "index": "zones",
        "setting": {},
        "nodes": [
            {
                "table": "zone",
                "schema": "cassini",
                "columns": [
                    "cassini_id",
                    "country_code",
                    "admin_level",
                    "geometry_json",
                    "bounding_box_json"
                ],
                "children": [
                    {
                        "table": "metadata",
                        "schema": "cassini",
                        "columns": [
                            "key",
                            "value",
                            "type"
                        ],
                        "label": "metadatas",
                        "relationship": {
                            "variant": "object",
                            "type": "one_to_many",
                            "through_tables": [
                                "zone_metadata"
                            ]
                        }
                    },
                    {
                        "table": "zone",
                        "schema": "cassini",
                        "columns": [
                            "cassini_id",
                            "country_code",
                            "admin_level"
                        ],
                        "label": "parents",
                        "relationship": {
                            "variant": "object",
                            "type": "one_to_many",
                            "through_tables": [
                                "zone_relation_parent"
                            ]
                        }
                    }
                ],
                "transform": {
                    "rename": {
                        "cassini_id": "cassiniId",
                        "country_code": "countryCode",
                        "admin_level": "adminLevel",
                        "geometry_json": "geometry",
                        "bounding_box_json": "boundingBox"
                    }
                }
            }
        ]
    }
```

The  "label": "metadatas" relation is working well but the  "label": "parents" have always a null property. 

The only difference is see between my two tables : zone_metadata and zone_relation_parent is that zone_relation_parent have two foreigns keys targeting to the same table "zones". 

I think pgsync is not working correctly when the through_tables property table is filled with a table that have at least two properties pointing to the same table. Do i have wrong ? 

I think is an issue
Thanks in advance

**Comment by sl-vincentaugerot** [comment]
Any news about this issue please ?

**Comment by toluaina** [comment]
Sorry. Taking a look at this now.

**Comment by toluaina** [comment]
OK I have made a change to support this in the master branch. Can you try this out and let me know

@sl-vincentaugerot

**Comment by sl-vincentaugerot** [comment]
Hi @toluaina thank you for your help.
Unfortunatly we have tested with master branch but the property parent is always null in eslastic after running pgsync
![image](https://user-images.githubusercontent.com/70574013/107345857-50671800-6ac4-11eb-897f-91fcb62a7d50.png)

How can we help you to debug ?

**Comment by toluaina** [comment]
That's a bit odd. I am going by the Postgres schema and pgsync schema you provided above.

Can you try the ffw:

> git pull 
> git checkout through_tables_when_foreigns_keys_target_the_same_table_63
> source .pythonpath 
> ./examples/bootstrap.sh sandbox

In the scenario, above you will see that the elastic search index [here](http://localhost:9200/zone/_search?pretty=true&q=*:*&size=100) shows the 
parents property is not null.

Alternatively when you run `pgsync` in your **own** environment. can you add -v and send me the output.
PS: make sure you mask out any sensitive info

**Comment by sl-marcsoufflet** [comment]
Hello,

I am working with Vincent. Thank you a lot for your help.
We integrated your code into the docker image (provided on your repo) to try it under linux environment. (we can provide you this integrated code if it can help? We will need to be allowed to make PR on this branch.)
Sadly, it seem its still not working for us:

There is the result:
![image](https://user-images.githubusercontent.com/73581371/107498264-d900b980-6b93-11eb-98fd-33e2bc7746eb.png)


And the logs:
[logs.txt](https://github.com/toluaina/pgsync/files/5957502/logs.txt)

Thank you in advance.

Regards

**Comment by toluaina** [comment]
Sorey for the delay. Can you provide me with directions to the integrated code you are using. I was merely going by the schema provided previously. In the mean time I will take a look at the logs agin

**Comment by sl-marcsoufflet** [comment]
Hello,

Thank you for your answer. There is the code based on your through_tables_when_foreigns_keys_target_the_same_table_63 branch which we updated, to make your code working with docker & docker-compose. We only did that. I invite you to check the commit on this "fork" and advise us if you can see any mistake ? Thank you a lot.

[pgsyncupdated.zip](https://github.com/toluaina/pgsync/files/5964156/pgsyncupdated.zip)

Regards

**Comment by toluaina** [comment]
I think I know whats going on. The leatest code changes are not in the container. 
I would suggest you do a 

> docker system prune -a
> docker volume prune

**Comment by toluaina** [comment]
I believe the container is pulling the package from pypi using pip. So it appears you are not using the changes in master. 
I was waiting for you to verify it was working before publishihg the next release

**Comment by toluaina** [comment]
I have published 1.1.26 which includes these changes to make it easier. Can you please re-run docker compose

**Comment by sl-marcsoufflet** [comment]
Hello,

Its working now ! Thanks you very much. 
We also tried directly in our code, it's all good !

Thank you again.

Regards

**Comment by sl-vincentaugerot** [comment]
@toluaina Very good job, thanks for your help and your reactivity 👍

**Comment by foboni** [comment]
PGSync version: 2.2.1

Postgres version: 14.2

Elasticsearch version: 7.16.2

I have got similar use case like the one explained above

#### Tables:

```sql
CREATE TABLE zone
(
    id text NOT NULL PRIMARY KEY,
    place_name text
);

CREATE TABLE zone_relation_parent
(
    zone_id text  NOT NULL REFERENCES zone (id),
    zone_id_relation text NOT NULL REFERENCES zone (id)
);

INSERT INTO zone VALUES ('1', 'abc'), ('2', 'bcd'), ('3', 'cde');

INSERT INTO zone_relation_parent VALUES ('1', '2'), ('1', '3'), ('2', '3');
```

#### Schema:

```json
[
    {
        "database": "mydb",
        "index": "zones",
        "nodes": {
            "table": "zone",
            "columns": [
                "id",
                "place_name"
            ],
            "children": [
                {
                    "table": "zone",
                    "columns": [
                        "id",
                        "place_name"
                    ],
                    "label": "parents",
                    "relationship": {
                        "variant": "object",
                        "type": "one_to_many",
                        "through_tables": [
                            "zone_relation_parent"
                        ]
                    }
                }
            ]
        }
    }
]
```

But when I use, pgsync it is not able to replicate the one-to-many mapping

#### Elasticsearch

```json
{
  "took" : 0,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 3,
      "relation" : "eq"
    },
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "zones",
        "_type" : "_doc",
        "_id" : "1",
        "_score" : 1.0,
        "_source" : {
          "id" : "1",
          "parents" : [
            null
          ],
          "place_name" : "abc",
          "_meta" : { }
        }
      },
      {
        "_index" : "zones",
        "_type" : "_doc",
        "_id" : "2",
        "_score" : 1.0,
        "_source" : {
          "id" : "2",
          "parents" : [
            null
          ],
          "place_name" : "bcd",
          "_meta" : { }
        }
      },
      {
        "_index" : "zones",
        "_type" : "_doc",
        "_id" : "3",
        "_score" : 1.0,
        "_source" : {
          "id" : "3",
          "parents" : [
            null
          ],
          "place_name" : "cde",
          "_meta" : { }
        }
      }
    ]
  }
}
```

For `_id` "1"

I'm expecting it to populated parents like this,

```json
[{"id": 2, "place_name": "bcd"}, {"id": 3, "place_name": "cde"}]
```

and for `_id` "2"

```json
[{"id": 3, "place_name": "cde"}]
```
