### ISSUE TITLE
Error in trigger postgres 9.6

### ISSUE THREAD

**Issue by masterlexa** [toluaina/pgsync#64]
PGSync version: 1.1.24

Postgres version: 9.6

Elasticsearch version: latest

Redis version: latest

Python version: 3.8

Problem Description: 
![image](https://user-images.githubusercontent.com/47365555/105752920-f4937f80-5f58-11eb-8d71-9c2a338ef111.png)

Error Message (if any): 

```
could not find array type for data type information_schema

```

**Comment by toluaina** [comment]
Thanks for reporting this. This has been fixed in the latest release
