### ISSUE TITLE
Use old version with fixes

### ISSUE THREAD

**Issue by masterlexa** [toluaina/pgsync#72]
PGSync version: 1.1.8

Postgres version: 9.6

Elasticsearch version: latest

Redis version: latest

Python version: 3.7

Problem Description: 
I true to use 1.1.25, but this trigger heavily loads the database.
I want to revert to the old version, but I need to decide the problem with cleaning pg_replication_slots

**Comment by toluaina** [comment]
I have updated the trigger template on master so it performs fewer joins. Can you try this out

**Comment by masterlexa** [comment]
You should change it to ARRAY_AGG(column_name::TEXT)

**Comment by toluaina** [comment]
Thanks you are right. Fixed in master
