### ISSUE TITLE
Message":"Request size exceeded 104857600 bytes"}

### ISSUE THREAD

**Issue by HinaAziz-graana** [toluaina/pgsync#73]
PGSync version: 

Postgres version: 

Elasticsearch version:
elasticsearch:7.9.3
Redis version:

Python version:
python:3.7

Problem Description: 

I am using aws elastic search with 100MB Max http payload size but on pgsync  it is giving me this error
Is there any workaround this so that I can make pgsync with 100mb payload size as increasing payload is size of es is really costly but can I change any configurations of elasticsearchhelper.py to make this work

Error Message (if any): 
elasticsearch.exceptions.TransportError: TransportError(413, '{"Message":"Request size exceeded 104857600 bytes"}')
```


```

**Comment by toluaina** [comment]
This is an exception from Elasticsearch. You can limit the request size with the environment variable 
`ELASTICSEARCH_MAX_CHUNK_BYTES`
This is also documented [here](https://pgsync.com/env-vars/)

**Comment by HinaAziz-graana** [comment]
yes I have already did that and changed its value like 500 but even then getting the same error
i m using docker-compose on mac with aws elastcisearch 100MB max payload size

**Comment by toluaina** [comment]
Can you log the value of `ELASTICSEARCH_MAX_CHUNK_BYTES` [here](https://github.com/toluaina/pgsync/blob/master/pgsync/elastichelper.py#L69)?

My suspicion is that that variable is not passed on

**Comment by HinaAziz-graana** [comment]
yes I did and its 500
![Uploading image.png…]()

**Comment by toluaina** [comment]
Not sure if you made any progress on this?
Perhaps you can try reducing `ELASTICSEARCH_CHUNK_SIZE` as well

**Comment by HinaAziz-graana** [comment]
No success with that either

**Comment by toluaina** [comment]
Could it be the state of the cluster?
Can you try a new ES index with the adjusted settings.

**Comment by HinaAziz-graana** [comment]
![Uploading image.png…]()

**Comment by HinaAziz-graana** [comment]
None of the recommended solutions are working for me

**Comment by toluaina** [comment]
I think you are hitting the [Request circuit breaker](https://www.elastic.co/guide/en/elasticsearch/reference/current/circuit-breaker.html).

It really depends on your data. My suggestion is to gradually reduce the **ELASTICSEARCH_CHUNK_SIZE** and **QUERY_CHUNK_SIZE** towards 0 to determine out the limit

**Comment by HinaAziz-graana** [comment]
I have reduced QUERY_CHUNK_SIZE and ELASTICSEARCH_CHUNK_SIZE both equal to 2 but still not working

**Comment by HinaAziz-graana** [comment]
it tied to upload data 4 times as you can see and I have changed the value of this env variable ELASTICSEARCH_QUEUE_SIZE =1 in docker-compose 
![image](https://user-images.githubusercontent.com/74229753/109138316-0e083100-777c-11eb-9aea-94f7db74ddb0.png)

**Comment by tinger2** [comment]
Can you run the airbnb example on your host?

**Comment by toluaina** [comment]
Sorry about the delay. 
Can you run the airbnb example using your current configurations. 
i.e **_redis_**, **_elasticsearch_** and **_postgres_** host

**Comment by toluaina** [comment]
Tempted to close this as this has not received any response in a while. Reopen if you wish to continue exploring solutions
