### ISSUE TITLE
Transform rename not working inside children

### ISSUE THREAD

**Issue by sl-vincentaugerot** [toluaina/pgsync#75]
PGSync version: pgsync-1.1.26
Postgres version: 11.4
Elasticsearch version: 7.4
Redis version: 5.0.0

Problem Description: 

When we used transform (rename) inside a children node, it does not rename the fields.
Transform (rename) working well if we are inside the root node.

Our json :
`[
    {
        "database": "lu",
        "index": "zoneslight",
        "setting": {},
        "nodes": [
            {
                "table": "zone",
                "schema": "cassini",
                "columns": [
                    "cassini_id",
                    "country_code",
                    "admin_level"
                ],
                "transform": {
                    "rename": {
                        "cassini_id": "cassiniId",
                        "country_code": "countryCode",
                        "admin_level": "adminLevel"
                    }
                },
                "children": [
                    {
                        "table": "zone_light",
                        "schema": "cassini",
                        "columns": [
                            "geometry_json"
                        ],
                        "label": "polygon",
                        "relationship": {
                            "variant": "object",
                            "type": "one_to_one"
                        },
                        "transform": {
                            "rename": {
                                "geometry_json": "geometry"
                            }
                        }
                    },
                    {
                        "table": "metadata",
                        "schema": "cassini",
                        "columns": [
                            "key",
                            "value",
                            "type"
                        ],
                        "label": "metadatas",
                        "relationship": {
                            "variant": "object",
                            "type": "one_to_many",
                            "through_tables": [
                                "zone_metadata"
                            ]
                        }
                    },
                    {
                        "table": "zone",
                        "schema": "cassini",
                        "columns": [
                            "id",
                            "admin_level"
                        ],
                        "label": "parents",
                        "relationship": {
                            "variant": "object",
                            "type": "one_to_many",
                            "through_tables": [
                                "zone_relation_parent"
                            ]
                        },
                        "transform": {
                            "rename": {
                                "admin_level": "adminLevel"
                            }
                        }
                    }
                ]
            }
        ]
    }
]`

The only transform which work well for us is : 
`                "transform": {
                    "rename": {
                        "cassini_id": "cassiniId",
                        "country_code": "countryCode",
                        "admin_level": "adminLevel"
                    }
                },`

Other transformations inside the children node have no effect on the renaming

Thanks in advance for your help

EDIT : Impossible to correctly formate code inside github today  (dont know why so i zip the json in attachment for better read)
[exemple json transform rename.zip](https://github.com/toluaina/pgsync/files/6003182/exemple.json.transform.rename.zip)

**Comment by sl-vincentaugerot** [comment]
`[
    {
        "database": "lu",
        "index": "zoneslight",
        "setting": {},
        "nodes": [
            {
                "table": "zone",
                "schema": "cassini",
                "columns": [
                    "cassini_id",
                    "country_code",
                    "admin_level"
                ],
                "transform": {
                    "rename": {
                        "cassini_id": "cassiniId",
                        "country_code": "countryCode",
                        "admin_level": "adminLevel"
                    }
                },
                "children": [
                    {
                        "table": "zone_light",
                        "schema": "cassini",
                        "columns": [
                            "geometry_json"
                        ],
                        "label": "polygon",
                        "relationship": {
                            "variant": "object",
                            "type": "one_to_one"
                        },
                        "transform": {
                            "rename": {
                                "geometry_json": "geometry"
                            }
                        }
                    },
                    {
                        "table": "metadata",
                        "schema": "cassini",
                        "columns": [
                            "key",
                            "value",
                            "type"
                        ],
                        "label": "metadatas",
                        "relationship": {
                            "variant": "object",
                            "type": "one_to_many",
                            "through_tables": [
                                "zone_metadata"
                            ]
                        }
                    },
                    {
                        "table": "zone",
                        "schema": "cassini",
                        "columns": [
                            "id",
                            "admin_level"
                        ],
                        "label": "parents",
                        "relationship": {
                            "variant": "object",
                            "type": "one_to_many",
                            "through_tables": [
                                "zone_relation_parent"
                            ]
                        },
                        "transform": {
                            "rename": {
                                "admin_level": "adminLevel"
                            }
                        }
                    }
                ]
            }
        ]
    }
]`

**Comment by toluaina** [comment]
Nested transformations appear to work even with your provided schema. 
Can you do an experiment and try a brand new index?
I wonder if it is due to the immutable mapping you already created.

**Comment by sl-vincentaugerot** [comment]
I have tried with dropping all index in elastic search but the result is the same, only root renaming is working. It always not renaming properties specified in children node

Exemple of _search result from ES:
`{"took":3,"timed_out":false,"_shards":{"total":5,"successful":5,"skipped":0,"failed":0},"hits":{"total":{"value":4173,"relation":"eq"},"max_score":1.0,"hits":[{"_index":"zonesboundingbox","_type":"_doc","_id":"be1","_score":1.0,"_source":{"cassiniId":"cbe_a9_e4.18971_n50.48131","countryCode":"be","adminLevel":9,"polygon":{"geometry_json":"{\"type\":\"Polygon\",\"coordinates\":[[[4.1573282,50.461172599],[4.1573282,50.505174799],[4.2134758,50.505174799],[4.2134758,50.461172599],[4.1573282,50.461172599]]]}"},"metadatas":null,"parents":[{"id":"be1","admin_level":9},{"id":"be2199","admin_level":2}],"_meta":{"zone_boundingbox":{"zone_id":["be1"]},"zone":{"id":["be1","be2199"]},"zone_relation_parent":{}}}},{"_index":"zonesboundingbox","_type":"_doc","_id":"be2","_score":1.0,"_source":{"cassiniId":"cbe_a9_e6.13093_n50.50268","countryCode":"be","adminLevel":9,"polygon":{"geometry_json":"{\"type\":\"Polygon\",\"coordinates\":[[[6.0631247,50.441321499],[6.0631247,50.570420899],[6.1983499,50.570420899],[6.1983499,50.441321499],[6.0631247,50.441321499]]]}"},"metadatas":null,"parents":[{"id":"be2199","admin_level":2},{"id":"be2","admin_level":9}],"_meta":{"zone_boundingbox":{"zone_id":["be2"]},"zone":{"id":["be2","be2199"]},"zone_relation_parent":{}}}},{"_index":"zonesboundingbox","_type":"_doc","_id":"be11","_score":1.0,"_source":{"cassiniId":"cbe_a8_e5.34092_n50.80478","countryCode":"be","adminLevel":8,"polygon":{"geometry_json":"{\"type\":\"Polygon\",\"coordinates\":[[[5.2503757,50.769464199],[5.2503757,50.845426799],[5.4076408,50.845426799],[5.4076408,50.769464199],[5.2503757,50.769464199]]]}"},"metadatas":[{"key":"Wikidata","value":"Q499609","type":1},{"key":"BeIns","value":"73009","type":1}],"parents":[{"id":"be11","admin_level":8},{"id":"be532","admin_level":9}],"_meta":{"zone_boundingbox":{"zone_id":["be11"]},"metadata":{"id":[1991,2517]},"zone_metadata":{},"zone":{"id":["be11","be532"]},"zone_relation_parent":{}}}},{"_index":"zonesboundingbox","_type":"_doc","_id":"be17","_score":1.0,"_source":{"cassiniId":"cbe_a8_e5.25046_n51.11740","countryCode":"be","adminLevel":8,"polygon":{"geometry_json":"{\"type\":\"Polygon\",\"coordinates\":[[[5.2014863,51.095868199],[5.2014863,51.147150499],[5.3008701,51.147150499],[5.3008701,51.095868199],[5.2014863,51.095868199]]]}"},"metadatas":[{"key":"Wikidata","value":"Q736120","type":1},{"key":"BeIns","value":"71034","type":1}],"parents":[{"id":"be17","admin_level":8},{"id":"be866","admin_level":9}],"_meta":{"zone_boundingbox":{"zone_id":["be17"]},"metadata":{"id":[153,1375]},"zone_metadata":{},"zone":{"id":["be17","be866"]},"zone_relation_parent":{}}}},{"_index":"zonesboundingbox","_type":"_doc","_id":"be32","_score":1.0,"_source":{"cassiniId":"cbe_a8_e4.14757_n50.74419","countryCode":"be","adminLevel":8,"polygon":{"geometry_json":"{\"type\":\"Polygon\",\"coordinates\":[[[4.071963,50.705588999],[4.071963,50.789806999],[4.2025124,50.789806999],[4.2025124,50.705588999],[4.071963,50.705588999]]]}"},"metadatas":[{"key":"Wikidata","value":"Q646037","type":1},{"key":"BeIns","value":"23064","type":1}],"parents":[{"id":"be731","admin_level":9},{"id":"be32","admin_level":8}],"_meta":{"zone_boundingbox":{"zone_id":["be32"]},"metadata":{"id":[542,1230]},"zone_metadata":{},"zone":{"id":["be32","be731"]},"zone_relation_parent":{}}}},{"_index":"zonesboundingbox","_type":"_doc","_id":"be37","_score":1.0,"_source":{"cassiniId":"cbe_a9_e5.20590_n49.79270","countryCode":"be","adminLevel":9,"polygon":{"geometry_json":"{\"type\":\"Polygon\",\"coordinates\":[[[5.1807574,49.7715331],[5.1807574,49.827957499],[5.2330684,49.827957499],[5.2330684,49.7715331],[5.1807574,49.7715331]]]}"},"metadatas":[{"key":"BeIns","value":"84009D","type":1}],"parents":[{"id":"be2199","admin_level":2},{"id":"be37","admin_level":9}],"_meta":{"zone_boundingbox":{"zone_id":["be37"]},"metadata":{"id":[1179]},"zone_metadata":{},"zone":{"id":["be2199","be37"]},"zone_relation_parent":{}}}},{"_index":"zonesboundingbox","_type":"_doc","_id":"be39","_score":1.0,"_source":{"cassiniId":"cbe_a8_e4.65617_n51.10713","countryCode":"be","adminLevel":8,"polygon":{"geometry_json":"{\"type\":\"Polygon\",\"coordinates\":[[[4.6051395,51.075206599],[4.6051395,51.135209499],[4.7005561,51.135209499],[4.7005561,51.075206599],[4.6051395,51.075206599]]]}"},"metadatas":[{"key":"BeIns","value":"12002","type":1},{"key":"Wikidata","value":"Q723774","type":1}],"parents":[{"id":"be924","admin_level":9},{"id":"be39","admin_level":8}],"_meta":{"zone_boundingbox":{"zone_id":["be39"]},"metadata":{"id":[1922,2202]},"zone_metadata":{},"zone":{"id":["be39","be924"]},"zone_relation_parent":{}}}},{"_index":"zonesboundingbox","_type":"_doc","_id":"be45","_score":1.0,"_source":{"cassiniId":"cbe_a10_e4.70272_n50.87000","countryCode":"be","adminLevel":10,"polygon":{"geometry_json":"{\"type\":\"Polygon\",\"coordinates\":[[[4.6986468,50.868317099],[4.6986468,50.872145399],[4.7077214,50.872145399],[4.7077214,50.868317099],[4.6986468,50.868317099]]]}"},"metadatas":[{"key":"Wikidata","value":"Q17153542","type":1}],"parents":[{"id":"be839","admin_level":9},{"id":"be45","admin_level":10}],"_meta":{"zone_boundingbox":{"zone_id":["be45"]},"metadata":{"id":[370]},"zone_metadata":{},"zone":{"id":["be45","be839"]},"zone_relation_parent":{}}}},{"_index":"zonesboundingbox","_type":"_doc","_id":"be46","_score":1.0,"_source":{"cassiniId":"cbe_a8_e2.83029_n50.77549","countryCode":"be","adminLevel":8,"polygon":{"geometry_json":"{\"type\":\"Polygon\",\"coordinates\":[[[2.7130028,50.708256199],[2.7130028,50.827323299],[2.9605015,50.827323299],[2.9605015,50.708256199],[2.7130028,50.708256199]]]}"},"metadatas":[{"key":"Wikidata","value":"Q822755","type":1},{"key":"BeIns","value":"33039","type":1}],"parents":[{"id":"be2199","admin_level":2},{"id":"be46","admin_level":8}],"_meta":{"zone_boundingbox":{"zone_id":["be46"]},"metadata":{"id":[598,920]},"zone_metadata":{},"zone":{"id":["be2199","be46"]},"zone_relation_parent":{}}}},{"_index":"zonesboundingbox","_type":"_doc","_id":"be58","_score":1.0,"_source":{"cassiniId":"cbe_a9_e5.23241_n49.74819","countryCode":"be","adminLevel":9,"polygon":{"geometry_json":"{\"type\":\"Polygon\",\"coordinates\":[[[5.1982444,49.7166064],[5.1982444,49.7759271],[5.2686507,49.7759271],[5.2686507,49.7166064],[5.1982444,49.7166064]]]}"},"metadatas":[{"key":"BeIns","value":"85011F","type":1}],"parents":[{"id":"be2199","admin_level":2},{"id":"be58","admin_level":9}],"_meta":{"zone_boundingbox":{"zone_id":["be58"]},"metadata":{"id":[620]},"zone_metadata":{},"zone":{"id":["be2199","be58"]},"zone_relation_parent":{}}}}]}}`

**Comment by toluaina** [comment]
This is odd. I am simply unable to reproduce this even with your schema. Can you change [these](https://github.com/toluaina/pgsync/blob/master/pgsync/sync.py#L697-L701) lines to the code below and send the output of the first few rows. Or better yet can you print the result of a row before and after transform on [this](https://github.com/toluaina/pgsync/blob/master/pgsync/sync.py#L688) line

```
pprint.pprint(row)
print('-' * 10)
```

**Comment by sl-vincentaugerot** [comment]
Hi @toluaina 
I have added peace of code you need for better log.

You can find the log inside the following zip:
[pgsync.zip](https://github.com/toluaina/pgsync/files/6021190/pgsync.zip)

You will find key "Pkeys before:" and "Pkeys after:" in the log.
I hope it will help you.

**Comment by toluaina** [comment]
Hmm, still not enough to tell what's going on. 
Can you also log the value of `nodes[0` [here](https://github.com/toluaina/pgsync/blob/master/pgsync/sync.py#L688)?

**Comment by sl-vincentaugerot** [comment]
Of course, the new log with "Pkeys before nodes[0]" string to log nodes[0]
Hope it's help
[pgsync.zip](https://github.com/toluaina/pgsync/files/6027732/pgsync.zip)

**Comment by toluaina** [comment]
Thanks for the logging data. This has now been fixed in the master branch

**Comment by sl-vincentaugerot** [comment]
I confirm every renaming work well now on the master branch. Thank you for your reactivity
