### ISSUE TITLE
Design question on mix use notify and slot

### ISSUE THREAD

**Issue by jiamo** [toluaina/pgsync#77]
Not an issue  but a question on design.

I see code 

```
        # now sync up to txmax to capture everything we might have missed
        self.logical_slot_changes(txmin=txmin, txmax=txmax)
```
In`pull_db`  use postgres sql notify system to pull data to redis then to elasticsearch.
And in `pull`.  postgres logic replication slot get the changes and pull to es too.
Do we  index same data second times to elasticsearch (one by notify one by slot change)?

**Comment by toluaina** [comment]
PGSync operates in an event-driven mode using pg-notify most of the time.
However, when the daemon is stopped for a period, events via pg notify will be missed and lost forever. 
The replication slot is replayed on startup and then pgsync reverts back to using pg-notify.
We carefully use the txids to avoid indexing the same data more than once.

**Comment by jiamo** [comment]
thanks

**Comment by jiamo** [comment]
From  https://issuetracker.google.com/issues/70756171 we can't use logic replication slot on gcp postgresql instance .
Is it possible using pgsync without replication slot (With a option like --no-slot)

**Comment by toluaina** [comment]
This is unfortunately correct. The problem is that without the replication slots, you need the pgsync process running all the time for it to work properly, 

There is no way to capture the changes made when the process halts. pg-notify sends it once and assumes the listener is up
