### ISSUE TITLE
How to configure connections?

### ISSUE THREAD

**Issue by rafaelvascc** [toluaina/pgsync#79]
PGSync version: 1.1.27

Postgres version: 12.xx

Elasticsearch version: 7.xx

Redis version: 

Python version: 

Problem Description: 
Hi, i wanted to use pgsyn to keep a postgres database on AWS in sync with elasticsearch also in AWS, but 'im not finding any way to configure connections in the docs.
Could someone point me to the connection configuration section or show me how to configure connections?
Thanks.

Error Message (if any): 

```


```

**Comment by toluaina** [comment]
You can configure these with the environment variables e.g `PG_HOST`...
These are documented here https://pgsync.com/env-vars/

**Comment by toluaina** [comment]
cloains as this has been resolved
