### ISSUE TITLE
Specify ingest pipeline for additional processing

### ISSUE THREAD

**Issue by nikokon** [toluaina/pgsync#80]
FEATURE REQUEST:
Would it be possible to specify an ingest pipeline for further processing in elastic.
I figure it would probably be a minor change as it should be supported in the bulk API.

Just started experimenting with PGSYNC and figured it could be a nice addition.

Really nice project BTW! 👍

**Comment by toluaina** [comment]
Thanks. I have added support for this in the master branch. You can now add the pipeline in the schema.json. There is an example is the books example. Let me know what you think

**Comment by toluaina** [comment]
closing this as this has been addressed. reopen if you feel something is still missing.

**Comment by Serioussamko** [comment]
> Thanks. I have added support for this in the master branch. You can now add the pipeline in the schema.json. There is an example is the books example. Let me know what you think

Hello, I don't find where the ingest pipeline is used in the schema.json of the book example.
