### ISSUE TITLE
Pgync is not working in window 10

### ISSUE THREAD

**Issue by chauvinhphuoc** [toluaina/pgsync#83]
When I install Pgsync by pip, pgsync and bootstrap command are not considered as a application (.exe)  in python scripts folder. So I cannot use `bootstrap --config schema.json` or `pgsync --config schema.json`
![image](https://user-images.githubusercontent.com/62022374/111070375-12667500-8504-11eb-9655-65ce7fd0a2d3.png)

**Comment by toluaina** [comment]
I'm afraid windows is not supported out of the box. 
You will need to update your system or user path to point to the bin directory and set the connection variables useing **set** or the equivalent

**Comment by toluaina** [comment]
I've seen this done, Basically:
- install pgsync
- remove the shebang or first line in [bootstrap](https://github.com/toluaina/pgsync/blob/master/bin/bootstrap) and [pgsync](https://github.com/toluaina/pgsync/blob/master/bin/pgsync)
- add the bin path to your system PATH and them make these scripts executable.
