### ISSUE TITLE
Replication slot does not exist

### ISSUE THREAD

**Issue by i-lukyanchik** [toluaina/pgsync#84]
PGSync version: 1.1.28

Postgres: debezium/postgres:13-alpine

Elasticsearch version: 7.10.2

Redis version: latest from DockerHub

Python version: 3.7

Problem Description: 
Hey guys! Thanks for this cool tool, I really appreciate your work.

After `bootstrap -c path/to/schema.json` command executed I have the error that the replication slot does not exist. And pgsync docker container exited with code 1. But when I created logical_replication_slot manually everything is fine. Can you please help me with this problem?

Also, I have an issue with `sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DuplicateObject) trigger "posts_notify" for relation "posts" already exists` even when before that I dropped trigger manually. I managed to fix that by commenting `bootstrap` command after replication slot was manually created by myself and triggers were created by pgsync. But this solution is not very nice. I saw your comment to [this issue](https://github.com/toluaina/pgsync/issues/74) and used 

```
bootstrap -t -c schema/schema.json
bootstrap -c schema/schema.json
```

but it didn't help me. 

Error Message (if any): 

```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedObject) replication slot "database_index" does not exist

[SQL: SELECT xid, data

FROM PG_LOGICAL_SLOT_PEEK_CHANGES(%(PG_LOGICAL_SLOT_PEEK_CHANGES_1)s, NULL, NULL)

WHERE CAST(CAST(xid AS TEXT) AS BIGINT) < %(param_1)s]

[parameters: {'PG_LOGICAL_SLOT_PEEK_CHANGES_1': 'database_index', 'param_1': 5956}]

sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DuplicateObject) trigger "posts_notify" for relation "posts" already exists

(Background on this error at: http://sqlalche.me/e/13/f405)

```
Thank you in advance!

**Comment by toluaina** [comment]
- Can you provide some more details. 
- are you running the docker example?
- also is the current user running the pgsync program able to create replication slots?
- bootstrap needs to run without errors unless some prerequisite has not been met. 
- maybe teardown everything and re-run bootstrap alone and send the output

**Comment by toluaina** [comment]
Closing... re-open if you need to
