### ISSUE TITLE
PostGIS POINT to Elasticsearch geo_point mapping not working inside children

### ISSUE THREAD

**Issue by i-lukyanchik** [toluaina/pgsync#85]
PGSync version: 1.1.28

Postgres: debezium/postgres:13-alpine

Elasticsearch version: 7.10.2

Redis version: latest from DockerHub

Python version: 3.7

Problem Description: 
Hi! I have column 'location' in the table which is stored as PostGIS GEOMETRY(POINT, 4326) and after PGSync saved it in Elasticsearch as children it has the following structure `{"location":{"type":"Point","coordinates":[128.4,10.4]}`. Everything is fine except for the type of coordinates is the array of double and I want it to be geo_point. I wrote the following transformation mapping in schema.json: 
```
          {
            "table": "post_locations",
            "columns": [
              "location",
              "geohash"
            ],
            "label": "locations",
            "relationship": {
              "type": "one_to_many",
              "variant": "object"
            },
            "children": [],
            "transform": {
              "mapping": {
                "location.coordinates": "geo_point"
              }
            }
          }
```
But the type of location didn't change.

![image](https://user-images.githubusercontent.com/73501523/111221240-46689580-85eb-11eb-8e68-5801a545e9b3.png)

I also tried to use the whole location mapping to geo_point, but I got `TypeError: string indices must be integers`. Can you help me with this problem?

Error Message (if any): 

```
TypeError: string indices must be integers
```

**Comment by toluaina** [comment]
Unfortunately this type of transformation is not supported yet. pgsync currently offers limited transformation functionality.

**Comment by toluaina** [comment]
Sorry for the late response. 
I have added support for plugins which is the most generic way for solving this. 
This is documented [here](https://pgsync.com/tutorial/plugins/) and there is an example in the book [example](https://github.com/toluaina/pgsync/blob/master/examples/book/schema.json)

Let me know if you need any help implementting this.

**Comment by toluaina** [comment]
Closing this. This has been adressed in the latest version
