### ISSUE TITLE
Schema can't handle more foreign keys from same table

### ISSUE THREAD

**Issue by DanielZavacky** [toluaina/pgsync#90]
PGSync version: 1.1.28

Postgres version: 13.1

Elasticsearch version: 7.10.1

Redis version: 6.2.1

Python version: 3.7

**Problem Description:** 
Hi. Is there a way to define schema, which would process case, where there are two foreign keys (itemOneID and itemTwoID) from same source table?
Database example:
![two_fks](https://user-images.githubusercontent.com/45260819/112181813-09109300-8bfd-11eb-98b2-81a4e097ea90.jpg)
Expected result:
![two_fks_result_exp](https://user-images.githubusercontent.com/45260819/112181263-8daee180-8bfc-11eb-84d2-612575b597a8.jpg)

**Comment by toluaina** [comment]
Sorry this use case is currently not supported. There are plans to support explicit Foreign Key definition which would address this.

**Comment by toluaina** [comment]
This feature has been added to the mater branch (unpublished). See its usage [here](https://github.com/toluaina/pgsync/blob/master/examples/book/schema.json#L81) 

Can you try it out and let me know?

@DanielZavacky

**Comment by DanielZavacky** [comment]
@toluaina Hi. It seems to work well. If I'll notice any error related to this functionality, I'll let you know.
Thank you for the quick implementation

**Comment by toluaina** [comment]
Closing as this seems to have been resolved.
