### ISSUE TITLE
Fails when Document size has a lot of fields - psycopg2.errors.TooManyArguments cannot pass more than 100 arguments to a function

### ISSUE THREAD

**Issue by spitfiredd** [toluaina/pgsync#93]
PGSync version: 1.1.30

Postgres version: 10.9

Elasticsearch version: 7.9.1

Redis version: 4.0.9

Python version: 3.7 and 3.8

Problem Description: I have an index that gets denormalized in Elasticsearch into 70 fields, and when I run pgsync I run into an error where I can't pass more than 100 arguments into a function.

Error Message (if any): 
`sqlalchemy.exc.OperationalError: (psycopg2.errors.TooManyArguments) cannot pass more than 100 arguments to a function`

```


```

**Comment by toluaina** [comment]
Seems you've hit a database server limit - [max_function_args](https://www.postgresql.org/docs/current/runtime-config-preset.html#max_function_args
).
Unfortunately, this can only be changed when building the server.

**Comment by spitfiredd** [comment]
That's a bummer, in a version update I will most likely look into reducing the number of fields since there is a lot that I don't even index, mostly put them on elastic so that they can be served from an API.

**Comment by toluaina** [comment]
Closing this as this has been answered.
