### ISSUE TITLE
Missing type issue with Elasticsearch 6.8.15

### ISSUE THREAD

**Issue by Ebsan** [toluaina/pgsync#96]
### Versions
- PGSync version: 1.1.32
- Postgres version: debezium/postgres:13-alpine
- Elasticsearch version: 6.8.15
- Redis version: (latest docker image)
- Python version: 3.7

### Problem Description
I have the following `schema.json`:
```
[
  {
    "database": "asp",
    "index": "apk_index",
    "nodes": [
      {
        "table": "apk"
      }
    ]
  }
]
```
When it tries to sync I get an error from Elasticsearch saying I have a missing type. It looks like Elasticsearch is complaining that the document type is missing but I'm not sure. Is this because I'm using Elasticsearch 6.8.15?

### Error Message

```
2021-04-09 21:58:28.492:ERROR:pgsync.sync: Exception RequestError(400, 'action_request_validation_exception', 'Validation Failed: 1: type is missing;2: type is missing;3: type is missing;4: type is missing;5: type is missing;6: type is missing;7: type is missing;8: type is missing;9: type is missing;')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pgsync/sync.py", line 730, in sync
    self.es.bulk(self.index, docs)
```

**Comment by toluaina** [comment]
Hi, This should be fixed now. Can you please try using the master branch
@Ebsan

**Comment by fdeschenes** [comment]
@toluaina I'm also using 6.8.15 and was having the issue above. I also have a very simple schema and using the master branch, I now get a different error which may or not be related:

```
Malformed action/metadata line [1], expected a simple value for field [_type] but found [START_ARRAY]
```

**Comment by Ebsan** [comment]
Yeah I'm getting the same error:

```
File "/usr/local/lib/python3.8/dist-packages/elasticsearch-7.12.0-py3.8.egg/elasticsearch/connection/base.py", line 322, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.RequestError: RequestError(400, 'illegal_argument_exception', 'Malformed action/metadata line [1], expected a simple value for field [_type] but found [START_ARRAY]')
```

**Comment by fdeschenes** [comment]
@toluaina In addition to the pull request above, I also created #101 which adds `_doc` to the mappings which fixes an issue when bootstrapping if using `mapping` under `transform`.

**Comment by toluaina** [comment]
Thanks to fdeschenes this can now be closed
