### ISSUE TITLE
ELASTICSEARCH_SCHEME and ELASTICSEARCH_PORT not working when connecting to AWS Elasticsearch

### ISSUE THREAD

**Issue by AndresERojasI** [toluaina/pgsync#98]
PGSync version:  1.1.32

Postgres version: PostgreSQL 13.2 (Debian 13.2-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit

Elasticsearch version: 7.9

Redis version: 6.2.1

Python version: 3.8

Problem Description: 
When setting up the .env file with the required variables, pgsync does not recognize the next variables: ELASTICSEARCH_PORT, ELASTICSEARCH_SCHEME. The problem is that it is trying to connect to the wrong URL causing a timeout and crashing.

In my .env I have the next variables:
ELASTICSEARCH_HOST=xxx.es.amazonaws.com
ELASTICSEARCH_PORT=443 (I'm using 443 to force https, I'm not sure if there is a way to not pass the port)
ELASTICSEARCH_SCHEME=https
ELASTICSEARCH_USER=xxxxxxxxx
ELASTICSEARCH_PASS=xxxxxxxxxx

Thanks in advance for your help guys!

Error Message (if any): 
![image](https://user-images.githubusercontent.com/9145492/114344792-13e88480-9b26-11eb-8526-4f9425eda148.png)

```
pgsync            | 2021-04-12 05:15:58.298:WARNING:elasticsearch: HEAD http://xxxxxxxxxx.es.amazonaws.com:9200/index [status:N/A request:20.129s]
pgsync            | Traceback (most recent call last):
pgsync            |   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
pgsync            |     conn = connection.create_connection(
pgsync            |   File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 96, in create_connection
pgsync            |     raise err
pgsync            |   File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection
pgsync            |     sock.connect(sa)
pgsync            | socket.timeout: timed out
```

**Comment by toluaina** [comment]
I see you are using the provided docker-compose,yml to start the services. 
I don't think this is reading the .env file , Can you try setting the port and scheme directly in [here](https://github.com/toluaina/pgsync/blob/master/docker-compose.yml#L46-L48) 

The compose file was provided as an example to quickly showcase the features

**Comment by toluaina** [comment]
I think the solution here is to create an` .env `file for your environment for [docker-compose ](https://docs.docker.com/compose/environment-variables/)

**Comment by toluaina** [comment]
any luck with this ?

**Comment by toluaina** [comment]
Closing this as well. I think this has been resolved.

**Comment by AndresERojasI** [comment]
Hey @toluaina, sorry I never responded to your messages, COVID got to me and kept me from working for a month. Thanks for taking your time on this project, I managed now to fix my issues. 

For anyone having this same issue, the key is to really understand how env vars work with Docker and DockerCompose, this article really helped me: [https://vsupalov.com/docker-arg-env-variable-guide/](https://vsupalov.com/docker-arg-env-variable-guide/)

Cheers!
