### ISSUE TITLE
Multiple Nodes

### ISSUE THREAD

**Issue by Ebsan** [toluaina/pgsync#99]
### Versions

- PGSync version: 1.1.32
- Postgres version: 13
- Elasticsearch version: 7.9.3
- Redis version: (latest docker version)
- Python version: 3.8

### Problem Description
I've looked at #32 but I'm still confused about having multiple nodes in a given database/index combo. For example I would assume the following would grab the `book,` `magazine,` and `tape` tables and sync them all in the elasticsearch `library_index` index.

```
  {
    "database": "db01",
    "index": "library_index",
    "nodes": [
      {
        "table": "book",
        "columns": ["id", "name"]
      },
      {
        "table": "magazine",
        "columns": ["id", "name"]
      },
      {
        "table": "tape",
        "columns": ["id", "name"]
      }
    ]
  }
```

But running this only syncs the book table to _library_index_; `magazine` and `tape` are not synced.

**Comment by toluaina** [comment]
Good question. Nodes were originally intended to be top-level collections.
But you are right and this can/should be flattened into a singular attribute - node as they can't stand on their own.
I will do this in the next major version as a breaking change.

```
[
    {
        "database": "mydb",
        "index": "mydb-index",
        "node": {
            "table": "table1",
            "schema": "public",
            "columns": []
        }
    },
    {
        "database": "mydb1",
        "index": "mydb-index2",
         "node": {
            "table": "table1",
            "schema": "public",
            "columns": []
        }
    }
]
```

**Comment by Ebsan** [comment]
Do you have a suggestion on how to sync multiple tables into a single index? I can see it being difficult to do with pgsync as you'd have to make sure the columns being synced have to match labels. Could this be done with a plugin of sorts?

**Comment by toluaina** [comment]
The typical use case is to group unrelated tables into separate indices. 
You can slo group them into the same index with a relationship.

Having them in a separate index would be the easiest thing

**Comment by Ebsan** [comment]
That makes sense, thank you.
